// AMQP 0-9-1 (RabbitMQ) annotations for protoc-gen-asyncapi
// (protoc-gen-amqp-asyncapi).
//
// These annotations carry only AMQP concepts: exchanges, queues and the
// bindings between them, publishing and consuming, request/reply, and AMQP
// specifics of servers and authentication. Everything generic (info,
// servers, security schemes, tags, summaries, examples, headers, ...) uses
// the asyncapi.v3 annotations (asyncapi/v3/annotations.proto).
//
// The generated documents use the official AsyncAPI AMQP bindings (0.3.0).
// RabbitMQ features the bindings do not cover (queue types and arguments,
// bindings, prefetch, streams, ...) are added to them as x-rabbitmq
// extensions.
//
// A service only needs enough annotations to say "this is an AMQP API";
// everything else is inferred from the Protobuf schema and its comments:
//
//   - request/reply vs. publish vs. subscribe is inferred from the rpc shape,
//     as documented on Pattern;
//   - routing keys default to "<package>.<service>.<method>" in snake_case,
//     published to the default exchange, which delivers to the queue of the
//     same name;
//   - `{name}` placeholders in routing keys are AsyncAPI channel parameters,
//     bound to payload fields with the same name. Queues bound to them match
//     any word ("*").
//
// Durations are strings in Go syntax, e.g. "500ms", "30s", "24h".

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: amqp/asyncapi/v1/annotations.proto

package amqpv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Mechanism lists the SASL mechanisms of RabbitMQ.
type Mechanism int32

const (
	Mechanism_MECHANISM_UNSPECIFIED Mechanism = 0
	// PLAIN: username and password.
	Mechanism_MECHANISM_PLAIN Mechanism = 1
	// AMQPLAIN: username and password (legacy).
	Mechanism_MECHANISM_AMQPLAIN Mechanism = 2
	// EXTERNAL: the TLS client certificate identifies the user.
	Mechanism_MECHANISM_EXTERNAL Mechanism = 3
)

// Enum value maps for Mechanism.
var (
	Mechanism_name = map[int32]string{
		0: "MECHANISM_UNSPECIFIED",
		1: "MECHANISM_PLAIN",
		2: "MECHANISM_AMQPLAIN",
		3: "MECHANISM_EXTERNAL",
	}
	Mechanism_value = map[string]int32{
		"MECHANISM_UNSPECIFIED": 0,
		"MECHANISM_PLAIN":       1,
		"MECHANISM_AMQPLAIN":    2,
		"MECHANISM_EXTERNAL":    3,
	}
)

func (x Mechanism) Enum() *Mechanism {
	p := new(Mechanism)
	*p = x
	return p
}

func (x Mechanism) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Mechanism) Descriptor() protoreflect.EnumDescriptor {
	return file_amqp_asyncapi_v1_annotations_proto_enumTypes[0].Descriptor()
}

func (Mechanism) Type() protoreflect.EnumType {
	return &file_amqp_asyncapi_v1_annotations_proto_enumTypes[0]
}

func (x Mechanism) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Mechanism.Descriptor instead.
func (Mechanism) EnumDescriptor() ([]byte, []int) {
	return file_amqp_asyncapi_v1_annotations_proto_rawDescGZIP(), []int{0}
}

// ExchangeType is the routing algorithm of an exchange.
type ExchangeType int32

const (
	// DIRECT.
	ExchangeType_EXCHANGE_TYPE_UNSPECIFIED ExchangeType = 0
	// Routes to queues whose binding key equals the routing key.
	ExchangeType_EXCHANGE_TYPE_DIRECT ExchangeType = 1
	// Routes to every bound queue.
	ExchangeType_EXCHANGE_TYPE_FANOUT ExchangeType = 2
	// Routes by pattern: "*" matches one word, "#" zero or more.
	ExchangeType_EXCHANGE_TYPE_TOPIC ExchangeType = 3
	// Routes by message headers (x-match all or any).
	ExchangeType_EXCHANGE_TYPE_HEADERS ExchangeType = 4
)

// Enum value maps for ExchangeType.
var (
	ExchangeType_name = map[int32]string{
		0: "EXCHANGE_TYPE_UNSPECIFIED",
		1: "EXCHANGE_TYPE_DIRECT",
		2: "EXCHANGE_TYPE_FANOUT",
		3: "EXCHANGE_TYPE_TOPIC",
		4: "EXCHANGE_TYPE_HEADERS",
	}
	ExchangeType_value = map[string]int32{
		"EXCHANGE_TYPE_UNSPECIFIED": 0,
		"EXCHANGE_TYPE_DIRECT":      1,
		"EXCHANGE_TYPE_FANOUT":      2,
		"EXCHANGE_TYPE_TOPIC":       3,
		"EXCHANGE_TYPE_HEADERS":     4,
	}
)

func (x ExchangeType) Enum() *ExchangeType {
	p := new(ExchangeType)
	*p = x
	return p
}

func (x ExchangeType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ExchangeType) Descriptor() protoreflect.EnumDescriptor {
	return file_amqp_asyncapi_v1_annotations_proto_enumTypes[1].Descriptor()
}

func (ExchangeType) Type() protoreflect.EnumType {
	return &file_amqp_asyncapi_v1_annotations_proto_enumTypes[1]
}

func (x ExchangeType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ExchangeType.Descriptor instead.
func (ExchangeType) EnumDescriptor() ([]byte, []int) {
	return file_amqp_asyncapi_v1_annotations_proto_rawDescGZIP(), []int{1}
}

// QueueType is the RabbitMQ queue type (x-queue-type).
type QueueType int32

const (
	// CLASSIC.
	QueueType_QUEUE_TYPE_UNSPECIFIED QueueType = 0
	QueueType_QUEUE_TYPE_CLASSIC     QueueType = 1
	// Replicated, durable queues (Raft).
	QueueType_QUEUE_TYPE_QUORUM QueueType = 2
	// Append-only, replayable logs.
	QueueType_QUEUE_TYPE_STREAM QueueType = 3
)

// Enum value maps for QueueType.
var (
	QueueType_name = map[int32]string{
		0: "QUEUE_TYPE_UNSPECIFIED",
		1: "QUEUE_TYPE_CLASSIC",
		2: "QUEUE_TYPE_QUORUM",
		3: "QUEUE_TYPE_STREAM",
	}
	QueueType_value = map[string]int32{
		"QUEUE_TYPE_UNSPECIFIED": 0,
		"QUEUE_TYPE_CLASSIC":     1,
		"QUEUE_TYPE_QUORUM":      2,
		"QUEUE_TYPE_STREAM":      3,
	}
)

func (x QueueType) Enum() *QueueType {
	p := new(QueueType)
	*p = x
	return p
}

func (x QueueType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (QueueType) Descriptor() protoreflect.EnumDescriptor {
	return file_amqp_asyncapi_v1_annotations_proto_enumTypes[2].Descriptor()
}

func (QueueType) Type() protoreflect.EnumType {
	return &file_amqp_asyncapi_v1_annotations_proto_enumTypes[2]
}

func (x QueueType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use QueueType.Descriptor instead.
func (QueueType) EnumDescriptor() ([]byte, []int) {
	return file_amqp_asyncapi_v1_annotations_proto_rawDescGZIP(), []int{2}
}

// Overflow is the behaviour of a full queue.
type Overflow int32

const (
	// DROP_HEAD.
	Overflow_OVERFLOW_UNSPECIFIED Overflow = 0
	// Drops the oldest messages.
	Overflow_OVERFLOW_DROP_HEAD Overflow = 1
	// Rejects new messages.
	Overflow_OVERFLOW_REJECT_PUBLISH Overflow = 2
	// Rejects new messages and dead-letters them.
	Overflow_OVERFLOW_REJECT_PUBLISH_DLX Overflow = 3
)

// Enum value maps for Overflow.
var (
	Overflow_name = map[int32]string{
		0: "OVERFLOW_UNSPECIFIED",
		1: "OVERFLOW_DROP_HEAD",
		2: "OVERFLOW_REJECT_PUBLISH",
		3: "OVERFLOW_REJECT_PUBLISH_DLX",
	}
	Overflow_value = map[string]int32{
		"OVERFLOW_UNSPECIFIED":        0,
		"OVERFLOW_DROP_HEAD":          1,
		"OVERFLOW_REJECT_PUBLISH":     2,
		"OVERFLOW_REJECT_PUBLISH_DLX": 3,
	}
)

func (x Overflow) Enum() *Overflow {
	p := new(Overflow)
	*p = x
	return p
}

func (x Overflow) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Overflow) Descriptor() protoreflect.EnumDescriptor {
	return file_amqp_asyncapi_v1_annotations_proto_enumTypes[3].Descriptor()
}

func (Overflow) Type() protoreflect.EnumType {
	return &file_amqp_asyncapi_v1_annotations_proto_enumTypes[3]
}

func (x Overflow) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Overflow.Descriptor instead.
func (Overflow) EnumDescriptor() ([]byte, []int) {
	return file_amqp_asyncapi_v1_annotations_proto_rawDescGZIP(), []int{3}
}

// Match is the x-match argument of headers exchange bindings.
type Match int32

const (
	// ALL.
	Match_MATCH_UNSPECIFIED Match = 0
	Match_MATCH_ALL         Match = 1
	Match_MATCH_ANY         Match = 2
)

// Enum value maps for Match.
var (
	Match_name = map[int32]string{
		0: "MATCH_UNSPECIFIED",
		1: "MATCH_ALL",
		2: "MATCH_ANY",
	}
	Match_value = map[string]int32{
		"MATCH_UNSPECIFIED": 0,
		"MATCH_ALL":         1,
		"MATCH_ANY":         2,
	}
)

func (x Match) Enum() *Match {
	p := new(Match)
	*p = x
	return p
}

func (x Match) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Match) Descriptor() protoreflect.EnumDescriptor {
	return file_amqp_asyncapi_v1_annotations_proto_enumTypes[4].Descriptor()
}

func (Match) Type() protoreflect.EnumType {
	return &file_amqp_asyncapi_v1_annotations_proto_enumTypes[4]
}

func (x Match) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Match.Descriptor instead.
func (Match) EnumDescriptor() ([]byte, []int) {
	return file_amqp_asyncapi_v1_annotations_proto_rawDescGZIP(), []int{4}
}

// Pattern is the messaging pattern of an rpc. When unspecified it is
// inferred from the rpc's shape, which only picks core AsyncAPI operations:
//
//   - an rpc with a response, streaming or not, is REQUEST_REPLY;
//   - a server streaming rpc without request (google.protobuf.Empty)
//     PUBLISHes;
//   - an rpc returning google.protobuf.Empty SUBSCRIBEs;
//   - a bidirectional streaming rpc is a PROCESS.
//
// A client streaming rpc with a response must set the pattern.
type Pattern int32

const (
	Pattern_PATTERN_UNSPECIFIED Pattern = 0
	// The service consumes requests and answers each one on the reply_to
	// queue of the request (RPC).
	Pattern_PATTERN_REQUEST_REPLY Pattern = 1
	// The service publishes messages.
	Pattern_PATTERN_PUBLISH Pattern = 2
	// The service consumes messages.
	Pattern_PATTERN_SUBSCRIBE Pattern = 3
	// The service receives the input on the operation's channel and sends the
	// output (the response) on the output channel, without replying: two
	// operations, e.g. a stream processor.
	Pattern_PATTERN_PROCESS Pattern = 4
)

// Enum value maps for Pattern.
var (
	Pattern_name = map[int32]string{
		0: "PATTERN_UNSPECIFIED",
		1: "PATTERN_REQUEST_REPLY",
		2: "PATTERN_PUBLISH",
		3: "PATTERN_SUBSCRIBE",
		4: "PATTERN_PROCESS",
	}
	Pattern_value = map[string]int32{
		"PATTERN_UNSPECIFIED":   0,
		"PATTERN_REQUEST_REPLY": 1,
		"PATTERN_PUBLISH":       2,
		"PATTERN_SUBSCRIBE":     3,
		"PATTERN_PROCESS":       4,
	}
)

func (x Pattern) Enum() *Pattern {
	p := new(Pattern)
	*p = x
	return p
}

func (x Pattern) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Pattern) Descriptor() protoreflect.EnumDescriptor {
	return file_amqp_asyncapi_v1_annotations_proto_enumTypes[5].Descriptor()
}

func (Pattern) Type() protoreflect.EnumType {
	return &file_amqp_asyncapi_v1_annotations_proto_enumTypes[5]
}

func (x Pattern) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Pattern.Descriptor instead.
func (Pattern) EnumDescriptor() ([]byte, []int) {
	return file_amqp_asyncapi_v1_annotations_proto_rawDescGZIP(), []int{5}
}

// DeliveryMode is the delivery_mode property.
type DeliveryMode int32

const (
	DeliveryMode_DELIVERY_MODE_UNSPECIFIED DeliveryMode = 0
	// Kept in memory only (1).
	DeliveryMode_DELIVERY_MODE_TRANSIENT DeliveryMode = 1
	// Written to disk by durable queues (2).
	DeliveryMode_DELIVERY_MODE_PERSISTENT DeliveryMode = 2
)

// Enum value maps for DeliveryMode.
var (
	DeliveryMode_name = map[int32]string{
		0: "DELIVERY_MODE_UNSPECIFIED",
		1: "DELIVERY_MODE_TRANSIENT",
		2: "DELIVERY_MODE_PERSISTENT",
	}
	DeliveryMode_value = map[string]int32{
		"DELIVERY_MODE_UNSPECIFIED": 0,
		"DELIVERY_MODE_TRANSIENT":   1,
		"DELIVERY_MODE_PERSISTENT":  2,
	}
)

func (x DeliveryMode) Enum() *DeliveryMode {
	p := new(DeliveryMode)
	*p = x
	return p
}

func (x DeliveryMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeliveryMode) Descriptor() protoreflect.EnumDescriptor {
	return file_amqp_asyncapi_v1_annotations_proto_enumTypes[6].Descriptor()
}

func (DeliveryMode) Type() protoreflect.EnumType {
	return &file_amqp_asyncapi_v1_annotations_proto_enumTypes[6]
}

func (x DeliveryMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DeliveryMode.Descriptor instead.
func (DeliveryMode) EnumDescriptor() ([]byte, []int) {
	return file_amqp_asyncapi_v1_annotations_proto_rawDescGZIP(), []int{6}
}

// Document holds the AMQP specifics of a document. When several files are
// merged into one AsyncAPI document, the settings of all files (and of the
// files they import) are combined.
type Document struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// AMQP details of servers declared in (asyncapi.v3.document).servers.
	Servers []*Server `protobuf:"bytes,1,rep,name=servers,proto3" json:"servers,omitempty"`
	// Authentication mechanism of security schemes declared in
	// (asyncapi.v3.document).security_schemes.
	Auth []*Auth `protobuf:"bytes,2,rep,name=auth,proto3" json:"auth,omitempty"`
	// Exchanges of the topology.
	Exchanges []*Exchange `protobuf:"bytes,3,rep,name=exchanges,proto3" json:"exchanges,omitempty"`
	// Queues of the topology, with their bindings.
	Queues []*Queue `protobuf:"bytes,4,rep,name=queues,proto3" json:"queues,omitempty"`
	// Exchange-to-exchange bindings.
	ExchangeBindings []*ExchangeBinding `protobuf:"bytes,5,rep,name=exchange_bindings,json=exchangeBindings,proto3" json:"exchange_bindings,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Document) Reset() {
	*x = Document{}
	mi := &file_amqp_asyncapi_v1_annotations_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Document) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Document) ProtoMessage() {}

func (x *Document) ProtoReflect() protoreflect.Message {
	mi := &file_amqp_asyncapi_v1_annotations_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Document.ProtoReflect.Descriptor instead.
func (*Document) Descriptor() ([]byte, []int) {
	return file_amqp_asyncapi_v1_annotations_proto_rawDescGZIP(), []int{0}
}

func (x *Document) GetServers() []*Server {
	if x != nil {
		return x.Servers
	}
	return nil
}

func (x *Document) GetAuth() []*Auth {
	if x != nil {
		return x.Auth
	}
	return nil
}

func (x *Document) GetExchanges() []*Exchange {
	if x != nil {
		return x.Exchanges
	}
	return nil
}

func (x *Document) GetQueues() []*Queue {
	if x != nil {
		return x.Queues
	}
	return nil
}

func (x *Document) GetExchangeBindings() []*ExchangeBinding {
	if x != nil {
		return x.ExchangeBindings
	}
	return nil
}

// Server adds AMQP details to a server declared with the asyncapi.v3
// annotations. They are rendered as the server's x-amqp binding (AsyncAPI
// reserves the amqp server binding).
type Server struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name of the (asyncapi.v3.document) server.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Default virtual host of the server's exchanges and queues. Defaults to
	// "/".
	Vhost string `protobuf:"bytes,2,opt,name=vhost,proto3" json:"vhost,omitempty"`
	// Connections use TLS (amqps).
	Tls bool `protobuf:"varint,3,opt,name=tls,proto3" json:"tls,omitempty"`
	// Heartbeat timeout requested by clients, e.g. "60s".
	Heartbeat string `protobuf:"bytes,4,opt,name=heartbeat,proto3" json:"heartbeat,omitempty"`
	// Maximum frame size in bytes (frame_max).
	FrameMax uint32 `protobuf:"varint,5,opt,name=frame_max,json=frameMax,proto3" json:"frame_max,omitempty"`
	// Maximum number of channels per connection (channel_max).
	ChannelMax    uint32 `protobuf:"varint,6,opt,name=channel_max,json=channelMax,proto3" json:"channel_max,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Server) Reset() {
	*x = Server{}
	mi := &file_amqp_asyncapi_v1_annotations_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server) ProtoMessage() {}

func (x *Server) ProtoReflect() protoreflect.Message {
	mi := &file_amqp_asyncapi_v1_annotations_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server.ProtoReflect.Descriptor instead.
func (*Server) Descriptor() ([]byte, []int) {
	return file_amqp_asyncapi_v1_annotations_proto_rawDescGZIP(), []int{1}
}

func (x *Server) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Server) GetVhost() string {
	if x != nil {
		return x.Vhost
	}
	return ""
}

func (x *Server) GetTls() bool {
	if x != nil {
		return x.Tls
	}
	return false
}

func (x *Server) GetHeartbeat() string {
	if x != nil {
		return x.Heartbeat
	}
	return ""
}

func (x *Server) GetFrameMax() uint32 {
	if x != nil {
		return x.FrameMax
	}
	return 0
}

func (x *Server) GetChannelMax() uint32 {
	if x != nil {
		return x.ChannelMax
	}
	return 0
}

// Auth sets the SASL mechanism of a security scheme. The scheme type is
// derived from it unless the scheme sets one.
type Auth struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name of the (asyncapi.v3.document) security scheme.
	Scheme string `protobuf:"bytes,1,opt,name=scheme,proto3" json:"scheme,omitempty"`
	// SASL mechanism.
	Mechanism     Mechanism `protobuf:"varint,2,opt,name=mechanism,proto3,enum=amqp.asyncapi.v1.Mechanism" json:"mechanism,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Auth) Reset() {
	*x = Auth{}
	mi := &file_amqp_asyncapi_v1_annotations_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Auth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Auth) ProtoMessage() {}

func (x *Auth) ProtoReflect() protoreflect.Message {
	mi := &file_amqp_asyncapi_v1_annotations_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Auth.ProtoReflect.Descriptor instead.
func (*Auth) Descriptor() ([]byte, []int) {
	return file_amqp_asyncapi_v1_annotations_proto_rawDescGZIP(), []int{2}
}

func (x *Auth) GetScheme() string {
	if x != nil {
		return x.Scheme
	}
	return ""
}

func (x *Auth) GetMechanism() Mechanism {
	if x != nil {
		return x.Mechanism
	}
	return Mechanism_MECHANISM_UNSPECIFIED
}

// Exchange declares an exchange.
type Exchange struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Exchange name. The default exchange ("") is always available.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Exchange type.
	Type ExchangeType `protobuf:"varint,2,opt,name=type,proto3,enum=amqp.asyncapi.v1.ExchangeType" json:"type,omitempty"`
	// Survives broker restarts.
	Durable bool `protobuf:"varint,3,opt,name=durable,proto3" json:"durable,omitempty"`
	// Deleted when its last queue is unbound.
	AutoDelete bool `protobuf:"varint,4,opt,name=auto_delete,json=autoDelete,proto3" json:"auto_delete,omitempty"`
	// Only reachable through exchange-to-exchange bindings, not by
	// publishers.
	Internal bool `protobuf:"varint,5,opt,name=internal,proto3" json:"internal,omitempty"`
	// Virtual host; defaults to the server's.
	Vhost string `protobuf:"bytes,6,opt,name=vhost,proto3" json:"vhost,omitempty"`
	// Alternate exchange receiving messages this one cannot route.
	AlternateExchange string `protobuf:"bytes,7,opt,name=alternate_exchange,json=alternateExchange,proto3" json:"alternate_exchange,omitempty"`
	// Delayed-message exchange (rabbitmq_delayed_message_exchange): type is
	// the routing type of the delayed messages, and publishers set a delay.
	Delayed bool `protobuf:"varint,8,opt,name=delayed,proto3" json:"delayed,omitempty"`
	// Other declaration arguments as JSON values, e.g. {"x-foo": "1"}.
	Arguments     map[string]string `protobuf:"bytes,9,rep,name=arguments,proto3" json:"arguments,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Description   string            `protobuf:"bytes,10,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Exchange) Reset() {
	*x = Exchange{}
	mi := &file_amqp_asyncapi_v1_annotations_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Exchange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Exchange) ProtoMessage() {}

func (x *Exchange) ProtoReflect() protoreflect.Message {
	mi := &file_amqp_asyncapi_v1_annotations_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Exchange.ProtoReflect.Descriptor instead.
func (*Exchange) Descriptor() ([]byte, []int) {
	return file_amqp_asyncapi_v1_annotations_proto_rawDescGZIP(), []int{3}
}

func (x *Exchange) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Exchange) GetType() ExchangeType {
	if x != nil {
		return x.Type
	}
	return ExchangeType_EXCHANGE_TYPE_UNSPECIFIED
}

func (x *Exchange) GetDurable() bool {
	if x != nil {
		return x.Durable
	}
	return false
}

func (x *Exchange) GetAutoDelete() bool {
	if x != nil {
		return x.AutoDelete
	}
	return false
}

func (x *Exchange) GetInternal() bool {
	if x != nil {
		return x.Internal
	}
	return false
}

func (x *Exchange) GetVhost() string {
	if x != nil {
		return x.Vhost
	}
	return ""
}

func (x *Exchange) GetAlternateExchange() string {
	if x != nil {
		return x.AlternateExchange
	}
	return ""
}

func (x *Exchange) GetDelayed() bool {
	if x != nil {
		return x.Delayed
	}
	return false
}

func (x *Exchange) GetArguments() map[string]string {
	if x != nil {
		return x.Arguments
	}
	return nil
}

func (x *Exchange) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// Queue declares a queue.
type Queue struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Queue name.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Queue type.
	Type QueueType `protobuf:"varint,2,opt,name=type,proto3,enum=amqp.asyncapi.v1.QueueType" json:"type,omitempty"`
	// Survives broker restarts. Quorum and stream queues are always durable.
	Durable bool `protobuf:"varint,3,opt,name=durable,proto3" json:"durable,omitempty"`
	// Used by one connection only, and deleted when it closes.
	Exclusive bool `protobuf:"varint,4,opt,name=exclusive,proto3" json:"exclusive,omitempty"`
	// Deleted when its last consumer unsubscribes.
	AutoDelete bool `protobuf:"varint,5,opt,name=auto_delete,json=autoDelete,proto3" json:"auto_delete,omitempty"`
	// Virtual host; defaults to the server's.
	Vhost string `protobuf:"bytes,6,opt,name=vhost,proto3" json:"vhost,omitempty"`
	// How long messages may stay in the queue (x-message-ttl).
	MessageTtl string `protobuf:"bytes,7,opt,name=message_ttl,json=messageTtl,proto3" json:"message_ttl,omitempty"`
	// Deleted after being unused this long (x-expires).
	Expires string `protobuf:"bytes,8,opt,name=expires,proto3" json:"expires,omitempty"`
	// Maximum number of ready messages (x-max-length).
	MaxLength int64 `protobuf:"varint,9,opt,name=max_length,json=maxLength,proto3" json:"max_length,omitempty"`
	// Maximum size of ready messages in bytes (x-max-length-bytes).
	MaxLengthBytes int64 `protobuf:"varint,10,opt,name=max_length_bytes,json=maxLengthBytes,proto3" json:"max_length_bytes,omitempty"`
	// What happens when the queue is full (x-overflow).
	Overflow Overflow `protobuf:"varint,11,opt,name=overflow,proto3,enum=amqp.asyncapi.v1.Overflow" json:"overflow,omitempty"`
	// Exchange receiving dead-lettered messages (x-dead-letter-exchange).
	DeadLetterExchange string `protobuf:"bytes,12,opt,name=dead_letter_exchange,json=deadLetterExchange,proto3" json:"dead_letter_exchange,omitempty"`
	// Routing key of dead-lettered messages (x-dead-letter-routing-key).
	DeadLetterRoutingKey string `protobuf:"bytes,13,opt,name=dead_letter_routing_key,json=deadLetterRoutingKey,proto3" json:"dead_letter_routing_key,omitempty"`
	// Highest message priority, 1 to 255 (x-max-priority). Classic queues
	// only.
	MaxPriority int32 `protobuf:"varint,14,opt,name=max_priority,json=maxPriority,proto3" json:"max_priority,omitempty"`
	// Only one consumer receives messages at a time
	// (x-single-active-consumer).
	SingleActiveConsumer bool `protobuf:"varint,15,opt,name=single_active_consumer,json=singleActiveConsumer,proto3" json:"single_active_consumer,omitempty"`
	// Deliveries before a message is dropped or dead-lettered
	// (x-delivery-limit). Quorum queues only.
	DeliveryLimit int32 `protobuf:"varint,16,opt,name=delivery_limit,json=deliveryLimit,proto3" json:"delivery_limit,omitempty"`
	// Retention of stream queues (x-max-age), e.g. "168h".
	MaxAge string `protobuf:"bytes,17,opt,name=max_age,json=maxAge,proto3" json:"max_age,omitempty"`
	// Bindings of the queue to exchanges.
	Bindings []*Binding `protobuf:"bytes,18,rep,name=bindings,proto3" json:"bindings,omitempty"`
	// Other declaration arguments as JSON values.
	Arguments     map[string]string `protobuf:"bytes,19,rep,name=arguments,proto3" json:"arguments,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Description   string            `protobuf:"bytes,20,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Queue) Reset() {
	*x = Queue{}
	mi := &file_amqp_asyncapi_v1_annotations_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Queue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Queue) ProtoMessage() {}

func (x *Queue) ProtoReflect() protoreflect.Message {
	mi := &file_amqp_asyncapi_v1_annotations_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Queue.ProtoReflect.Descriptor instead.
func (*Queue) Descriptor() ([]byte, []int) {
	return file_amqp_asyncapi_v1_annotations_proto_rawDescGZIP(), []int{4}
}

func (x *Queue) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Queue) GetType() QueueType {
	if x != nil {
		return x.Type
	}
	return QueueType_QUEUE_TYPE_UNSPECIFIED
}

func (x *Queue) GetDurable() bool {
	if x != nil {
		return x.Durable
	}
	return false
}

func (x *Queue) GetExclusive() bool {
	if x != nil {
		return x.Exclusive
	}
	return false
}

func (x *Queue) GetAutoDelete() bool {
	if x != nil {
		return x.AutoDelete
	}
	return false
}

func (x *Queue) GetVhost() string {
	if x != nil {
		return x.Vhost
	}
	return ""
}

func (x *Queue) GetMessageTtl() string {
	if x != nil {
		return x.MessageTtl
	}
	return ""
}

func (x *Queue) GetExpires() string {
	if x != nil {
		return x.Expires
	}
	return ""
}

func (x *Queue) GetMaxLength() int64 {
	if x != nil {
		return x.MaxLength
	}
	return 0
}

func (x *Queue) GetMaxLengthBytes() int64 {
	if x != nil {
		return x.MaxLengthBytes
	}
	return 0
}

func (x *Queue) GetOverflow() Overflow {
	if x != nil {
		return x.Overflow
	}
	return Overflow_OVERFLOW_UNSPECIFIED
}

func (x *Queue) GetDeadLetterExchange() string {
	if x != nil {
		return x.DeadLetterExchange
	}
	return ""
}

func (x *Queue) GetDeadLetterRoutingKey() string {
	if x != nil {
		return x.DeadLetterRoutingKey
	}
	return ""
}

func (x *Queue) GetMaxPriority() int32 {
	if x != nil {
		return x.MaxPriority
	}
	return 0
}

func (x *Queue) GetSingleActiveConsumer() bool {
	if x != nil {
		return x.SingleActiveConsumer
	}
	return false
}

func (x *Queue) GetDeliveryLimit() int32 {
	if x != nil {
		return x.DeliveryLimit
	}
	return 0
}

func (x *Queue) GetMaxAge() string {
	if x != nil {
		return x.MaxAge
	}
	return ""
}

func (x *Queue) GetBindings() []*Binding {
	if x != nil {
		return x.Bindings
	}
	return nil
}

func (x *Queue) GetArguments() map[string]string {
	if x != nil {
		return x.Arguments
	}
	return nil
}

func (x *Queue) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// Binding binds a queue to an exchange.
type Binding struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Source exchange.
	Exchange string `protobuf:"bytes,1,opt,name=exchange,proto3" json:"exchange,omitempty"`
	// Binding key; topic exchanges accept "*" and "#".
	RoutingKey string `protobuf:"bytes,2,opt,name=routing_key,json=routingKey,proto3" json:"routing_key,omitempty"`
	// Headers exchanges: how the headers must match.
	Match Match `protobuf:"varint,3,opt,name=match,proto3,enum=amqp.asyncapi.v1.Match" json:"match,omitempty"`
	// Headers exchanges: the header values to match, as JSON values.
	Headers       map[string]string `protobuf:"bytes,4,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Binding) Reset() {
	*x = Binding{}
	mi := &file_amqp_asyncapi_v1_annotations_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Binding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Binding) ProtoMessage() {}

func (x *Binding) ProtoReflect() protoreflect.Message {
	mi := &file_amqp_asyncapi_v1_annotations_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Binding.ProtoReflect.Descriptor instead.
func (*Binding) Descriptor() ([]byte, []int) {
	return file_amqp_asyncapi_v1_annotations_proto_rawDescGZIP(), []int{5}
}

func (x *Binding) GetExchange() string {
	if x != nil {
		return x.Exchange
	}
	return ""
}

func (x *Binding) GetRoutingKey() string {
	if x != nil {
		return x.RoutingKey
	}
	return ""
}

func (x *Binding) GetMatch() Match {
	if x != nil {
		return x.Match
	}
	return Match_MATCH_UNSPECIFIED
}

func (x *Binding) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

// ExchangeBinding binds an exchange to another one.
type ExchangeBinding struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Source        string                 `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	Destination   string                 `protobuf:"bytes,2,opt,name=destination,proto3" json:"destination,omitempty"`
	RoutingKey    string                 `protobuf:"bytes,3,opt,name=routing_key,json=routingKey,proto3" json:"routing_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExchangeBinding) Reset() {
	*x = ExchangeBinding{}
	mi := &file_amqp_asyncapi_v1_annotations_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExchangeBinding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExchangeBinding) ProtoMessage() {}

func (x *ExchangeBinding) ProtoReflect() protoreflect.Message {
	mi := &file_amqp_asyncapi_v1_annotations_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExchangeBinding.ProtoReflect.Descriptor instead.
func (*ExchangeBinding) Descriptor() ([]byte, []int) {
	return file_amqp_asyncapi_v1_annotations_proto_rawDescGZIP(), []int{6}
}

func (x *ExchangeBinding) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *ExchangeBinding) GetDestination() string {
	if x != nil {
		return x.Destination
	}
	return ""
}

func (x *ExchangeBinding) GetRoutingKey() string {
	if x != nil {
		return x.RoutingKey
	}
	return ""
}

// Service holds defaults for every rpc of a service.
type Service struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Exchange the service's messages are published to; defaults to the
	// default exchange ("").
	Exchange string `protobuf:"bytes,1,opt,name=exchange,proto3" json:"exchange,omitempty"`
	// Prefix of the routing keys of the service's rpcs, joined with '.'.
	RoutingKeyPrefix string `protobuf:"bytes,2,opt,name=routing_key_prefix,json=routingKeyPrefix,proto3" json:"routing_key_prefix,omitempty"`
	// Queue the service consumes from, for rpcs without their own.
	Queue string `protobuf:"bytes,3,opt,name=queue,proto3" json:"queue,omitempty"`
	// Consumer prefetch (basic.qos) of the service's consumers.
	Prefetch      int32 `protobuf:"varint,4,opt,name=prefetch,proto3" json:"prefetch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Service) Reset() {
	*x = Service{}
	mi := &file_amqp_asyncapi_v1_annotations_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Service) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Service) ProtoMessage() {}

func (x *Service) ProtoReflect() protoreflect.Message {
	mi := &file_amqp_asyncapi_v1_annotations_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Service.ProtoReflect.Descriptor instead.
func (*Service) Descriptor() ([]byte, []int) {
	return file_amqp_asyncapi_v1_annotations_proto_rawDescGZIP(), []int{7}
}

func (x *Service) GetExchange() string {
	if x != nil {
		return x.Exchange
	}
	return ""
}

func (x *Service) GetRoutingKeyPrefix() string {
	if x != nil {
		return x.RoutingKeyPrefix
	}
	return ""
}

func (x *Service) GetQueue() string {
	if x != nil {
		return x.Queue
	}
	return ""
}

func (x *Service) GetPrefetch() int32 {
	if x != nil {
		return x.Prefetch
	}
	return 0
}

// Operation describes the AMQP operation of an rpc.
type Operation struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Messaging pattern; inferred when unspecified.
	Pattern Pattern `protobuf:"varint,1,opt,name=pattern,proto3,enum=amqp.asyncapi.v1.Pattern" json:"pattern,omitempty"`
	// Exchange messages are published to; defaults to the service's.
	Exchange string `protobuf:"bytes,2,opt,name=exchange,proto3" json:"exchange,omitempty"`
	// Routing key, relative to the service's routing_key_prefix. Consumers
	// may use binding patterns ("*" and "#") on topic exchanges.
	RoutingKey string `protobuf:"bytes,3,opt,name=routing_key,json=routingKey,proto3" json:"routing_key,omitempty"`
	// Queue the consumer reads from. Defaults to the service's queue, or, on
	// the default exchange, to the queue named after the routing key. The
	// queue is bound to the exchange with the routing key unless a declared
	// queue already has bindings.
	Queue string `protobuf:"bytes,4,opt,name=queue,proto3" json:"queue,omitempty"`
	// Publishing properties.
	Publish *Publish `protobuf:"bytes,5,opt,name=publish,proto3" json:"publish,omitempty"`
	// Consuming settings.
	Consume *Consume `protobuf:"bytes,6,opt,name=consume,proto3" json:"consume,omitempty"`
	// REQUEST_REPLY: queue replies are sent to (through the default
	// exchange). Defaults to RabbitMQ's direct reply-to
	// ("amq.rabbitmq.reply-to").
	ReplyQueue string `protobuf:"bytes,7,opt,name=reply_queue,json=replyQueue,proto3" json:"reply_queue,omitempty"`
	// REQUEST_REPLY: additional reply messages (full Protobuf names), e.g.
	// an error message.
	ReplyMessages []string `protobuf:"bytes,8,rep,name=reply_messages,json=replyMessages,proto3" json:"reply_messages,omitempty"`
	// PROCESS: Routing key the output is published with, on the same exchange,
	// relative to the service's routing_key_prefix. Defaults to the input routing
	// key followed by ".output".
	Output        string `protobuf:"bytes,9,opt,name=output,proto3" json:"output,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Operation) Reset() {
	*x = Operation{}
	mi := &file_amqp_asyncapi_v1_annotations_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Operation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Operation) ProtoMessage() {}

func (x *Operation) ProtoReflect() protoreflect.Message {
	mi := &file_amqp_asyncapi_v1_annotations_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Operation.ProtoReflect.Descriptor instead.
func (*Operation) Descriptor() ([]byte, []int) {
	return file_amqp_asyncapi_v1_annotations_proto_rawDescGZIP(), []int{8}
}

func (x *Operation) GetPattern() Pattern {
	if x != nil {
		return x.Pattern
	}
	return Pattern_PATTERN_UNSPECIFIED
}

func (x *Operation) GetExchange() string {
	if x != nil {
		return x.Exchange
	}
	return ""
}

func (x *Operation) GetRoutingKey() string {
	if x != nil {
		return x.RoutingKey
	}
	return ""
}

func (x *Operation) GetQueue() string {
	if x != nil {
		return x.Queue
	}
	return ""
}

func (x *Operation) GetPublish() *Publish {
	if x != nil {
		return x.Publish
	}
	return nil
}

func (x *Operation) GetConsume() *Consume {
	if x != nil {
		return x.Consume
	}
	return nil
}

func (x *Operation) GetReplyQueue() string {
	if x != nil {
		return x.ReplyQueue
	}
	return ""
}

func (x *Operation) GetReplyMessages() []string {
	if x != nil {
		return x.ReplyMessages
	}
	return nil
}

func (x *Operation) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

// Publish holds basic.publish flags and message properties set by
// publishers.
type Publish struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Returned to the publisher when no queue receives it.
	Mandatory bool `protobuf:"varint,1,opt,name=mandatory,proto3" json:"mandatory,omitempty"`
	// Delivery mode.
	DeliveryMode DeliveryMode `protobuf:"varint,2,opt,name=delivery_mode,json=deliveryMode,proto3,enum=amqp.asyncapi.v1.DeliveryMode" json:"delivery_mode,omitempty"`
	// Message priority, 0 to 255.
	Priority int32 `protobuf:"varint,3,opt,name=priority,proto3" json:"priority,omitempty"`
	// Per-message TTL (expiration), e.g. "30s".
	Expiration string `protobuf:"bytes,4,opt,name=expiration,proto3" json:"expiration,omitempty"`
	// Additional routing keys (CC header), visible to consumers.
	Cc []string `protobuf:"bytes,5,rep,name=cc,proto3" json:"cc,omitempty"`
	// Additional routing keys (BCC header), hidden from consumers.
	Bcc []string `protobuf:"bytes,6,rep,name=bcc,proto3" json:"bcc,omitempty"`
	// Validated user ID (user_id property).
	UserId string `protobuf:"bytes,7,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// Publishers set the timestamp property.
	Timestamp bool `protobuf:"varint,8,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Publisher application (app_id property).
	AppId string `protobuf:"bytes,9,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	// Publishers wait for publisher confirms.
	Confirm bool `protobuf:"varint,10,opt,name=confirm,proto3" json:"confirm,omitempty"`
	// Delay of delayed-message exchanges (x-delay header), e.g. "5m".
	Delay         string `protobuf:"bytes,11,opt,name=delay,proto3" json:"delay,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Publish) Reset() {
	*x = Publish{}
	mi := &file_amqp_asyncapi_v1_annotations_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Publish) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Publish) ProtoMessage() {}

func (x *Publish) ProtoReflect() protoreflect.Message {
	mi := &file_amqp_asyncapi_v1_annotations_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Publish.ProtoReflect.Descriptor instead.
func (*Publish) Descriptor() ([]byte, []int) {
	return file_amqp_asyncapi_v1_annotations_proto_rawDescGZIP(), []int{9}
}

func (x *Publish) GetMandatory() bool {
	if x != nil {
		return x.Mandatory
	}
	return false
}

func (x *Publish) GetDeliveryMode() DeliveryMode {
	if x != nil {
		return x.DeliveryMode
	}
	return DeliveryMode_DELIVERY_MODE_UNSPECIFIED
}

func (x *Publish) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *Publish) GetExpiration() string {
	if x != nil {
		return x.Expiration
	}
	return ""
}

func (x *Publish) GetCc() []string {
	if x != nil {
		return x.Cc
	}
	return nil
}

func (x *Publish) GetBcc() []string {
	if x != nil {
		return x.Bcc
	}
	return nil
}

func (x *Publish) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Publish) GetTimestamp() bool {
	if x != nil {
		return x.Timestamp
	}
	return false
}

func (x *Publish) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *Publish) GetConfirm() bool {
	if x != nil {
		return x.Confirm
	}
	return false
}

func (x *Publish) GetDelay() string {
	if x != nil {
		return x.Delay
	}
	return ""
}

// Consume holds basic.consume settings.
type Consume struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Consumers acknowledge automatically (no-ack) instead of explicitly.
	AutoAck bool `protobuf:"varint,1,opt,name=auto_ack,json=autoAck,proto3" json:"auto_ack,omitempty"`
	// Prefetch (basic.qos); defaults to the service's.
	Prefetch int32 `protobuf:"varint,2,opt,name=prefetch,proto3" json:"prefetch,omitempty"`
	// Exclusive consumer: the only one on the queue.
	Exclusive bool `protobuf:"varint,3,opt,name=exclusive,proto3" json:"exclusive,omitempty"`
	// Consumer tag.
	ConsumerTag string `protobuf:"bytes,4,opt,name=consumer_tag,json=consumerTag,proto3" json:"consumer_tag,omitempty"`
	// Stream queues: where consumption starts (x-stream-offset): "first",
	// "last", "next", an offset, an RFC 3339 timestamp or a duration.
	StreamOffset string `protobuf:"bytes,5,opt,name=stream_offset,json=streamOffset,proto3" json:"stream_offset,omitempty"`
	// Consumer priority (x-priority).
	Priority      int32 `protobuf:"varint,6,opt,name=priority,proto3" json:"priority,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Consume) Reset() {
	*x = Consume{}
	mi := &file_amqp_asyncapi_v1_annotations_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Consume) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Consume) ProtoMessage() {}

func (x *Consume) ProtoReflect() protoreflect.Message {
	mi := &file_amqp_asyncapi_v1_annotations_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Consume.ProtoReflect.Descriptor instead.
func (*Consume) Descriptor() ([]byte, []int) {
	return file_amqp_asyncapi_v1_annotations_proto_rawDescGZIP(), []int{10}
}

func (x *Consume) GetAutoAck() bool {
	if x != nil {
		return x.AutoAck
	}
	return false
}

func (x *Consume) GetPrefetch() int32 {
	if x != nil {
		return x.Prefetch
	}
	return 0
}

func (x *Consume) GetExclusive() bool {
	if x != nil {
		return x.Exclusive
	}
	return false
}

func (x *Consume) GetConsumerTag() string {
	if x != nil {
		return x.ConsumerTag
	}
	return ""
}

func (x *Consume) GetStreamOffset() string {
	if x != nil {
		return x.StreamOffset
	}
	return ""
}

func (x *Consume) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

// Message holds AMQP properties of a message, and optionally gives it its
// own channel, documented even when no rpc uses it.
type Message struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Channel: exchange the message is published to.
	Exchange string `protobuf:"bytes,1,opt,name=exchange,proto3" json:"exchange,omitempty"`
	// Channel: routing key of the message.
	RoutingKey string `protobuf:"bytes,2,opt,name=routing_key,json=routingKey,proto3" json:"routing_key,omitempty"`
	// Type property (message binding messageType). Defaults to the full
	// Protobuf name.
	Type string `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	// Content encoding property, e.g. "gzip".
	ContentEncoding string `protobuf:"bytes,4,opt,name=content_encoding,json=contentEncoding,proto3" json:"content_encoding,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_amqp_asyncapi_v1_annotations_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_amqp_asyncapi_v1_annotations_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_amqp_asyncapi_v1_annotations_proto_rawDescGZIP(), []int{11}
}

func (x *Message) GetExchange() string {
	if x != nil {
		return x.Exchange
	}
	return ""
}

func (x *Message) GetRoutingKey() string {
	if x != nil {
		return x.RoutingKey
	}
	return ""
}

func (x *Message) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Message) GetContentEncoding() string {
	if x != nil {
		return x.ContentEncoding
	}
	return ""
}

var file_amqp_asyncapi_v1_annotations_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.FileOptions)(nil),
		ExtensionType: (*Document)(nil),
		Field:         58340,
		Name:          "amqp.asyncapi.v1.document",
		Tag:           "bytes,58340,opt,name=document",
		Filename:      "amqp/asyncapi/v1/annotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.ServiceOptions)(nil),
		ExtensionType: (*Service)(nil),
		Field:         58340,
		Name:          "amqp.asyncapi.v1.service",
		Tag:           "bytes,58340,opt,name=service",
		Filename:      "amqp/asyncapi/v1/annotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*Operation)(nil),
		Field:         58340,
		Name:          "amqp.asyncapi.v1.operation",
		Tag:           "bytes,58340,opt,name=operation",
		Filename:      "amqp/asyncapi/v1/annotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*Message)(nil),
		Field:         58340,
		Name:          "amqp.asyncapi.v1.message",
		Tag:           "bytes,58340,opt,name=message",
		Filename:      "amqp/asyncapi/v1/annotations.proto",
	},
}

// Extension fields to descriptorpb.FileOptions.
var (
	// AMQP specifics of the document: server and authentication details and
	// the declared topology (exchanges, queues and bindings).
	//
	// optional amqp.asyncapi.v1.Document document = 58340;
	E_Document = &file_amqp_asyncapi_v1_annotations_proto_extTypes[0]
)

// Extension fields to descriptorpb.ServiceOptions.
var (
	// AMQP defaults applied to every rpc of the service.
	//
	// optional amqp.asyncapi.v1.Service service = 58340;
	E_Service = &file_amqp_asyncapi_v1_annotations_proto_extTypes[1]
)

// Extension fields to descriptorpb.MethodOptions.
var (
	// Describes the AMQP operation implemented by an rpc.
	//
	// optional amqp.asyncapi.v1.Operation operation = 58340;
	E_Operation = &file_amqp_asyncapi_v1_annotations_proto_extTypes[2]
)

// Extension fields to descriptorpb.MessageOptions.
var (
	// AMQP properties of a message, and optionally its own channel.
	//
	// optional amqp.asyncapi.v1.Message message = 58340;
	E_Message = &file_amqp_asyncapi_v1_annotations_proto_extTypes[3]
)

var File_amqp_asyncapi_v1_annotations_proto protoreflect.FileDescriptor

const file_amqp_asyncapi_v1_annotations_proto_rawDesc = "" +
	"\n" +
	"\"amqp/asyncapi/v1/annotations.proto\x12\x10amqp.asyncapi.v1\x1a google/protobuf/descriptor.proto\"\xa5\x02\n" +
	"\bDocument\x122\n" +
	"\aservers\x18\x01 \x03(\v2\x18.amqp.asyncapi.v1.ServerR\aservers\x12*\n" +
	"\x04auth\x18\x02 \x03(\v2\x16.amqp.asyncapi.v1.AuthR\x04auth\x128\n" +
	"\texchanges\x18\x03 \x03(\v2\x1a.amqp.asyncapi.v1.ExchangeR\texchanges\x12/\n" +
	"\x06queues\x18\x04 \x03(\v2\x17.amqp.asyncapi.v1.QueueR\x06queues\x12N\n" +
	"\x11exchange_bindings\x18\x05 \x03(\v2!.amqp.asyncapi.v1.ExchangeBindingR\x10exchangeBindings\"\xa0\x01\n" +
	"\x06Server\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05vhost\x18\x02 \x01(\tR\x05vhost\x12\x10\n" +
	"\x03tls\x18\x03 \x01(\bR\x03tls\x12\x1c\n" +
	"\theartbeat\x18\x04 \x01(\tR\theartbeat\x12\x1b\n" +
	"\tframe_max\x18\x05 \x01(\rR\bframeMax\x12\x1f\n" +
	"\vchannel_max\x18\x06 \x01(\rR\n" +
	"channelMax\"Y\n" +
	"\x04Auth\x12\x16\n" +
	"\x06scheme\x18\x01 \x01(\tR\x06scheme\x129\n" +
	"\tmechanism\x18\x02 \x01(\x0e2\x1b.amqp.asyncapi.v1.MechanismR\tmechanism\"\xb1\x03\n" +
	"\bExchange\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x122\n" +
	"\x04type\x18\x02 \x01(\x0e2\x1e.amqp.asyncapi.v1.ExchangeTypeR\x04type\x12\x18\n" +
	"\adurable\x18\x03 \x01(\bR\adurable\x12\x1f\n" +
	"\vauto_delete\x18\x04 \x01(\bR\n" +
	"autoDelete\x12\x1a\n" +
	"\binternal\x18\x05 \x01(\bR\binternal\x12\x14\n" +
	"\x05vhost\x18\x06 \x01(\tR\x05vhost\x12-\n" +
	"\x12alternate_exchange\x18\a \x01(\tR\x11alternateExchange\x12\x18\n" +
	"\adelayed\x18\b \x01(\bR\adelayed\x12G\n" +
	"\targuments\x18\t \x03(\v2).amqp.asyncapi.v1.Exchange.ArgumentsEntryR\targuments\x12 \n" +
	"\vdescription\x18\n" +
	" \x01(\tR\vdescription\x1a<\n" +
	"\x0eArgumentsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xd6\x06\n" +
	"\x05Queue\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12/\n" +
	"\x04type\x18\x02 \x01(\x0e2\x1b.amqp.asyncapi.v1.QueueTypeR\x04type\x12\x18\n" +
	"\adurable\x18\x03 \x01(\bR\adurable\x12\x1c\n" +
	"\texclusive\x18\x04 \x01(\bR\texclusive\x12\x1f\n" +
	"\vauto_delete\x18\x05 \x01(\bR\n" +
	"autoDelete\x12\x14\n" +
	"\x05vhost\x18\x06 \x01(\tR\x05vhost\x12\x1f\n" +
	"\vmessage_ttl\x18\a \x01(\tR\n" +
	"messageTtl\x12\x18\n" +
	"\aexpires\x18\b \x01(\tR\aexpires\x12\x1d\n" +
	"\n" +
	"max_length\x18\t \x01(\x03R\tmaxLength\x12(\n" +
	"\x10max_length_bytes\x18\n" +
	" \x01(\x03R\x0emaxLengthBytes\x126\n" +
	"\boverflow\x18\v \x01(\x0e2\x1a.amqp.asyncapi.v1.OverflowR\boverflow\x120\n" +
	"\x14dead_letter_exchange\x18\f \x01(\tR\x12deadLetterExchange\x125\n" +
	"\x17dead_letter_routing_key\x18\r \x01(\tR\x14deadLetterRoutingKey\x12!\n" +
	"\fmax_priority\x18\x0e \x01(\x05R\vmaxPriority\x124\n" +
	"\x16single_active_consumer\x18\x0f \x01(\bR\x14singleActiveConsumer\x12%\n" +
	"\x0edelivery_limit\x18\x10 \x01(\x05R\rdeliveryLimit\x12\x17\n" +
	"\amax_age\x18\x11 \x01(\tR\x06maxAge\x125\n" +
	"\bbindings\x18\x12 \x03(\v2\x19.amqp.asyncapi.v1.BindingR\bbindings\x12D\n" +
	"\targuments\x18\x13 \x03(\v2&.amqp.asyncapi.v1.Queue.ArgumentsEntryR\targuments\x12 \n" +
	"\vdescription\x18\x14 \x01(\tR\vdescription\x1a<\n" +
	"\x0eArgumentsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xf3\x01\n" +
	"\aBinding\x12\x1a\n" +
	"\bexchange\x18\x01 \x01(\tR\bexchange\x12\x1f\n" +
	"\vrouting_key\x18\x02 \x01(\tR\n" +
	"routingKey\x12-\n" +
	"\x05match\x18\x03 \x01(\x0e2\x17.amqp.asyncapi.v1.MatchR\x05match\x12@\n" +
	"\aheaders\x18\x04 \x03(\v2&.amqp.asyncapi.v1.Binding.HeadersEntryR\aheaders\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"l\n" +
	"\x0fExchangeBinding\x12\x16\n" +
	"\x06source\x18\x01 \x01(\tR\x06source\x12 \n" +
	"\vdestination\x18\x02 \x01(\tR\vdestination\x12\x1f\n" +
	"\vrouting_key\x18\x03 \x01(\tR\n" +
	"routingKey\"\x85\x01\n" +
	"\aService\x12\x1a\n" +
	"\bexchange\x18\x01 \x01(\tR\bexchange\x12,\n" +
	"\x12routing_key_prefix\x18\x02 \x01(\tR\x10routingKeyPrefix\x12\x14\n" +
	"\x05queue\x18\x03 \x01(\tR\x05queue\x12\x1a\n" +
	"\bprefetch\x18\x04 \x01(\x05R\bprefetch\"\xdd\x02\n" +
	"\tOperation\x123\n" +
	"\apattern\x18\x01 \x01(\x0e2\x19.amqp.asyncapi.v1.PatternR\apattern\x12\x1a\n" +
	"\bexchange\x18\x02 \x01(\tR\bexchange\x12\x1f\n" +
	"\vrouting_key\x18\x03 \x01(\tR\n" +
	"routingKey\x12\x14\n" +
	"\x05queue\x18\x04 \x01(\tR\x05queue\x123\n" +
	"\apublish\x18\x05 \x01(\v2\x19.amqp.asyncapi.v1.PublishR\apublish\x123\n" +
	"\aconsume\x18\x06 \x01(\v2\x19.amqp.asyncapi.v1.ConsumeR\aconsume\x12\x1f\n" +
	"\vreply_queue\x18\a \x01(\tR\n" +
	"replyQueue\x12%\n" +
	"\x0ereply_messages\x18\b \x03(\tR\rreplyMessages\x12\x16\n" +
	"\x06output\x18\t \x01(\tR\x06output\"\xc8\x02\n" +
	"\aPublish\x12\x1c\n" +
	"\tmandatory\x18\x01 \x01(\bR\tmandatory\x12C\n" +
	"\rdelivery_mode\x18\x02 \x01(\x0e2\x1e.amqp.asyncapi.v1.DeliveryModeR\fdeliveryMode\x12\x1a\n" +
	"\bpriority\x18\x03 \x01(\x05R\bpriority\x12\x1e\n" +
	"\n" +
	"expiration\x18\x04 \x01(\tR\n" +
	"expiration\x12\x0e\n" +
	"\x02cc\x18\x05 \x03(\tR\x02cc\x12\x10\n" +
	"\x03bcc\x18\x06 \x03(\tR\x03bcc\x12\x17\n" +
	"\auser_id\x18\a \x01(\tR\x06userId\x12\x1c\n" +
	"\ttimestamp\x18\b \x01(\bR\ttimestamp\x12\x15\n" +
	"\x06app_id\x18\t \x01(\tR\x05appId\x12\x18\n" +
	"\aconfirm\x18\n" +
	" \x01(\bR\aconfirm\x12\x14\n" +
	"\x05delay\x18\v \x01(\tR\x05delay\"\xc2\x01\n" +
	"\aConsume\x12\x19\n" +
	"\bauto_ack\x18\x01 \x01(\bR\aautoAck\x12\x1a\n" +
	"\bprefetch\x18\x02 \x01(\x05R\bprefetch\x12\x1c\n" +
	"\texclusive\x18\x03 \x01(\bR\texclusive\x12!\n" +
	"\fconsumer_tag\x18\x04 \x01(\tR\vconsumerTag\x12#\n" +
	"\rstream_offset\x18\x05 \x01(\tR\fstreamOffset\x12\x1a\n" +
	"\bpriority\x18\x06 \x01(\x05R\bpriority\"\x85\x01\n" +
	"\aMessage\x12\x1a\n" +
	"\bexchange\x18\x01 \x01(\tR\bexchange\x12\x1f\n" +
	"\vrouting_key\x18\x02 \x01(\tR\n" +
	"routingKey\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12)\n" +
	"\x10content_encoding\x18\x04 \x01(\tR\x0fcontentEncoding*k\n" +
	"\tMechanism\x12\x19\n" +
	"\x15MECHANISM_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fMECHANISM_PLAIN\x10\x01\x12\x16\n" +
	"\x12MECHANISM_AMQPLAIN\x10\x02\x12\x16\n" +
	"\x12MECHANISM_EXTERNAL\x10\x03*\x95\x01\n" +
	"\fExchangeType\x12\x1d\n" +
	"\x19EXCHANGE_TYPE_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14EXCHANGE_TYPE_DIRECT\x10\x01\x12\x18\n" +
	"\x14EXCHANGE_TYPE_FANOUT\x10\x02\x12\x17\n" +
	"\x13EXCHANGE_TYPE_TOPIC\x10\x03\x12\x19\n" +
	"\x15EXCHANGE_TYPE_HEADERS\x10\x04*m\n" +
	"\tQueueType\x12\x1a\n" +
	"\x16QUEUE_TYPE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12QUEUE_TYPE_CLASSIC\x10\x01\x12\x15\n" +
	"\x11QUEUE_TYPE_QUORUM\x10\x02\x12\x15\n" +
	"\x11QUEUE_TYPE_STREAM\x10\x03*z\n" +
	"\bOverflow\x12\x18\n" +
	"\x14OVERFLOW_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12OVERFLOW_DROP_HEAD\x10\x01\x12\x1b\n" +
	"\x17OVERFLOW_REJECT_PUBLISH\x10\x02\x12\x1f\n" +
	"\x1bOVERFLOW_REJECT_PUBLISH_DLX\x10\x03*<\n" +
	"\x05Match\x12\x15\n" +
	"\x11MATCH_UNSPECIFIED\x10\x00\x12\r\n" +
	"\tMATCH_ALL\x10\x01\x12\r\n" +
	"\tMATCH_ANY\x10\x02*~\n" +
	"\aPattern\x12\x17\n" +
	"\x13PATTERN_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15PATTERN_REQUEST_REPLY\x10\x01\x12\x13\n" +
	"\x0fPATTERN_PUBLISH\x10\x02\x12\x15\n" +
	"\x11PATTERN_SUBSCRIBE\x10\x03\x12\x13\n" +
	"\x0fPATTERN_PROCESS\x10\x04*h\n" +
	"\fDeliveryMode\x12\x1d\n" +
	"\x19DELIVERY_MODE_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17DELIVERY_MODE_TRANSIENT\x10\x01\x12\x1c\n" +
	"\x18DELIVERY_MODE_PERSISTENT\x10\x02:V\n" +
	"\bdocument\x12\x1c.google.protobuf.FileOptions\x18\xe4\xc7\x03 \x01(\v2\x1a.amqp.asyncapi.v1.DocumentR\bdocument:V\n" +
	"\aservice\x12\x1f.google.protobuf.ServiceOptions\x18\xe4\xc7\x03 \x01(\v2\x19.amqp.asyncapi.v1.ServiceR\aservice:[\n" +
	"\toperation\x12\x1e.google.protobuf.MethodOptions\x18\xe4\xc7\x03 \x01(\v2\x1b.amqp.asyncapi.v1.OperationR\toperation:V\n" +
	"\amessage\x12\x1f.google.protobuf.MessageOptions\x18\xe4\xc7\x03 \x01(\v2\x19.amqp.asyncapi.v1.MessageR\amessageBEZCgithub.com/AustinZhu/protoc-gen-asyncapi/pb/amqp/asyncapi/v1;amqpv1b\x06proto3"

var (
	file_amqp_asyncapi_v1_annotations_proto_rawDescOnce sync.Once
	file_amqp_asyncapi_v1_annotations_proto_rawDescData []byte
)

func file_amqp_asyncapi_v1_annotations_proto_rawDescGZIP() []byte {
	file_amqp_asyncapi_v1_annotations_proto_rawDescOnce.Do(func() {
		file_amqp_asyncapi_v1_annotations_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_amqp_asyncapi_v1_annotations_proto_rawDesc), len(file_amqp_asyncapi_v1_annotations_proto_rawDesc)))
	})
	return file_amqp_asyncapi_v1_annotations_proto_rawDescData
}

var file_amqp_asyncapi_v1_annotations_proto_enumTypes = make([]protoimpl.EnumInfo, 7)
var file_amqp_asyncapi_v1_annotations_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_amqp_asyncapi_v1_annotations_proto_goTypes = []any{
	(Mechanism)(0),                      // 0: amqp.asyncapi.v1.Mechanism
	(ExchangeType)(0),                   // 1: amqp.asyncapi.v1.ExchangeType
	(QueueType)(0),                      // 2: amqp.asyncapi.v1.QueueType
	(Overflow)(0),                       // 3: amqp.asyncapi.v1.Overflow
	(Match)(0),                          // 4: amqp.asyncapi.v1.Match
	(Pattern)(0),                        // 5: amqp.asyncapi.v1.Pattern
	(DeliveryMode)(0),                   // 6: amqp.asyncapi.v1.DeliveryMode
	(*Document)(nil),                    // 7: amqp.asyncapi.v1.Document
	(*Server)(nil),                      // 8: amqp.asyncapi.v1.Server
	(*Auth)(nil),                        // 9: amqp.asyncapi.v1.Auth
	(*Exchange)(nil),                    // 10: amqp.asyncapi.v1.Exchange
	(*Queue)(nil),                       // 11: amqp.asyncapi.v1.Queue
	(*Binding)(nil),                     // 12: amqp.asyncapi.v1.Binding
	(*ExchangeBinding)(nil),             // 13: amqp.asyncapi.v1.ExchangeBinding
	(*Service)(nil),                     // 14: amqp.asyncapi.v1.Service
	(*Operation)(nil),                   // 15: amqp.asyncapi.v1.Operation
	(*Publish)(nil),                     // 16: amqp.asyncapi.v1.Publish
	(*Consume)(nil),                     // 17: amqp.asyncapi.v1.Consume
	(*Message)(nil),                     // 18: amqp.asyncapi.v1.Message
	nil,                                 // 19: amqp.asyncapi.v1.Exchange.ArgumentsEntry
	nil,                                 // 20: amqp.asyncapi.v1.Queue.ArgumentsEntry
	nil,                                 // 21: amqp.asyncapi.v1.Binding.HeadersEntry
	(*descriptorpb.FileOptions)(nil),    // 22: google.protobuf.FileOptions
	(*descriptorpb.ServiceOptions)(nil), // 23: google.protobuf.ServiceOptions
	(*descriptorpb.MethodOptions)(nil),  // 24: google.protobuf.MethodOptions
	(*descriptorpb.MessageOptions)(nil), // 25: google.protobuf.MessageOptions
}
var file_amqp_asyncapi_v1_annotations_proto_depIdxs = []int32{
	8,  // 0: amqp.asyncapi.v1.Document.servers:type_name -> amqp.asyncapi.v1.Server
	9,  // 1: amqp.asyncapi.v1.Document.auth:type_name -> amqp.asyncapi.v1.Auth
	10, // 2: amqp.asyncapi.v1.Document.exchanges:type_name -> amqp.asyncapi.v1.Exchange
	11, // 3: amqp.asyncapi.v1.Document.queues:type_name -> amqp.asyncapi.v1.Queue
	13, // 4: amqp.asyncapi.v1.Document.exchange_bindings:type_name -> amqp.asyncapi.v1.ExchangeBinding
	0,  // 5: amqp.asyncapi.v1.Auth.mechanism:type_name -> amqp.asyncapi.v1.Mechanism
	1,  // 6: amqp.asyncapi.v1.Exchange.type:type_name -> amqp.asyncapi.v1.ExchangeType
	19, // 7: amqp.asyncapi.v1.Exchange.arguments:type_name -> amqp.asyncapi.v1.Exchange.ArgumentsEntry
	2,  // 8: amqp.asyncapi.v1.Queue.type:type_name -> amqp.asyncapi.v1.QueueType
	3,  // 9: amqp.asyncapi.v1.Queue.overflow:type_name -> amqp.asyncapi.v1.Overflow
	12, // 10: amqp.asyncapi.v1.Queue.bindings:type_name -> amqp.asyncapi.v1.Binding
	20, // 11: amqp.asyncapi.v1.Queue.arguments:type_name -> amqp.asyncapi.v1.Queue.ArgumentsEntry
	4,  // 12: amqp.asyncapi.v1.Binding.match:type_name -> amqp.asyncapi.v1.Match
	21, // 13: amqp.asyncapi.v1.Binding.headers:type_name -> amqp.asyncapi.v1.Binding.HeadersEntry
	5,  // 14: amqp.asyncapi.v1.Operation.pattern:type_name -> amqp.asyncapi.v1.Pattern
	16, // 15: amqp.asyncapi.v1.Operation.publish:type_name -> amqp.asyncapi.v1.Publish
	17, // 16: amqp.asyncapi.v1.Operation.consume:type_name -> amqp.asyncapi.v1.Consume
	6,  // 17: amqp.asyncapi.v1.Publish.delivery_mode:type_name -> amqp.asyncapi.v1.DeliveryMode
	22, // 18: amqp.asyncapi.v1.document:extendee -> google.protobuf.FileOptions
	23, // 19: amqp.asyncapi.v1.service:extendee -> google.protobuf.ServiceOptions
	24, // 20: amqp.asyncapi.v1.operation:extendee -> google.protobuf.MethodOptions
	25, // 21: amqp.asyncapi.v1.message:extendee -> google.protobuf.MessageOptions
	7,  // 22: amqp.asyncapi.v1.document:type_name -> amqp.asyncapi.v1.Document
	14, // 23: amqp.asyncapi.v1.service:type_name -> amqp.asyncapi.v1.Service
	15, // 24: amqp.asyncapi.v1.operation:type_name -> amqp.asyncapi.v1.Operation
	18, // 25: amqp.asyncapi.v1.message:type_name -> amqp.asyncapi.v1.Message
	26, // [26:26] is the sub-list for method output_type
	26, // [26:26] is the sub-list for method input_type
	22, // [22:26] is the sub-list for extension type_name
	18, // [18:22] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_amqp_asyncapi_v1_annotations_proto_init() }
func file_amqp_asyncapi_v1_annotations_proto_init() {
	if File_amqp_asyncapi_v1_annotations_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_amqp_asyncapi_v1_annotations_proto_rawDesc), len(file_amqp_asyncapi_v1_annotations_proto_rawDesc)),
			NumEnums:      7,
			NumMessages:   15,
			NumExtensions: 4,
			NumServices:   0,
		},
		GoTypes:           file_amqp_asyncapi_v1_annotations_proto_goTypes,
		DependencyIndexes: file_amqp_asyncapi_v1_annotations_proto_depIdxs,
		EnumInfos:         file_amqp_asyncapi_v1_annotations_proto_enumTypes,
		MessageInfos:      file_amqp_asyncapi_v1_annotations_proto_msgTypes,
		ExtensionInfos:    file_amqp_asyncapi_v1_annotations_proto_extTypes,
	}.Build()
	File_amqp_asyncapi_v1_annotations_proto = out.File
	file_amqp_asyncapi_v1_annotations_proto_goTypes = nil
	file_amqp_asyncapi_v1_annotations_proto_depIdxs = nil
}
