// Apache Kafka annotations for protoc-gen-asyncapi
// (protoc-gen-kafka-asyncapi).
//
// These annotations carry only Kafka concepts: topics and their
// configuration, message keys and schema registry details, producers,
// consumer groups, request/reply, and Kafka specifics of servers and
// authentication. Everything generic (info, servers, security schemes, tags,
// summaries, examples, headers, ...) uses the asyncapi.v3 annotations
// (asyncapi/v3/annotations.proto). Record headers are documented as message
// headers.
//
// The generated documents use the official AsyncAPI Kafka bindings (0.5.0);
// producer and consumer settings they do not define are added to them as
// x-kafka extensions.
//
// A service only needs enough annotations to say "this is a Kafka API";
// everything else is inferred from the Protobuf schema and its comments:
//
//   - produce vs. consume vs. request/reply is inferred from the rpc shape,
//     as documented on Pattern;
//   - topic names default to "<package>.<service>.<method>" in snake_case;
//   - `{name}` placeholders in topic names are channel parameters, bound to
//     payload fields with the same name.
//
// Durations are strings in Go syntax, e.g. "500ms", "30s", "168h".

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: kafka/asyncapi/v1/annotations.proto

package kafkav1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Mechanism lists the Kafka authentication mechanisms.
type Mechanism int32

const (
	Mechanism_MECHANISM_UNSPECIFIED Mechanism = 0
	// SASL/PLAIN (security scheme type plain).
	Mechanism_MECHANISM_PLAIN Mechanism = 1
	// SASL/SCRAM-SHA-256 (scramSha256).
	Mechanism_MECHANISM_SCRAM_SHA_256 Mechanism = 2
	// SASL/SCRAM-SHA-512 (scramSha512).
	Mechanism_MECHANISM_SCRAM_SHA_512 Mechanism = 3
	// SASL/GSSAPI, Kerberos (gssapi).
	Mechanism_MECHANISM_GSSAPI Mechanism = 4
	// SASL/OAUTHBEARER. The security scheme must be an oauth2 or
	// openIdConnect scheme with its flows or URL.
	Mechanism_MECHANISM_OAUTHBEARER Mechanism = 5
	// Mutual TLS (X509).
	Mechanism_MECHANISM_MTLS Mechanism = 6
)

// Enum value maps for Mechanism.
var (
	Mechanism_name = map[int32]string{
		0: "MECHANISM_UNSPECIFIED",
		1: "MECHANISM_PLAIN",
		2: "MECHANISM_SCRAM_SHA_256",
		3: "MECHANISM_SCRAM_SHA_512",
		4: "MECHANISM_GSSAPI",
		5: "MECHANISM_OAUTHBEARER",
		6: "MECHANISM_MTLS",
	}
	Mechanism_value = map[string]int32{
		"MECHANISM_UNSPECIFIED":   0,
		"MECHANISM_PLAIN":         1,
		"MECHANISM_SCRAM_SHA_256": 2,
		"MECHANISM_SCRAM_SHA_512": 3,
		"MECHANISM_GSSAPI":        4,
		"MECHANISM_OAUTHBEARER":   5,
		"MECHANISM_MTLS":          6,
	}
)

func (x Mechanism) Enum() *Mechanism {
	p := new(Mechanism)
	*p = x
	return p
}

func (x Mechanism) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Mechanism) Descriptor() protoreflect.EnumDescriptor {
	return file_kafka_asyncapi_v1_annotations_proto_enumTypes[0].Descriptor()
}

func (Mechanism) Type() protoreflect.EnumType {
	return &file_kafka_asyncapi_v1_annotations_proto_enumTypes[0]
}

func (x Mechanism) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Mechanism.Descriptor instead.
func (Mechanism) EnumDescriptor() ([]byte, []int) {
	return file_kafka_asyncapi_v1_annotations_proto_rawDescGZIP(), []int{0}
}

// CleanupPolicy is a cleanup.policy value.
type CleanupPolicy int32

const (
	CleanupPolicy_CLEANUP_POLICY_UNSPECIFIED CleanupPolicy = 0
	// Deletes old segments.
	CleanupPolicy_CLEANUP_POLICY_DELETE CleanupPolicy = 1
	// Keeps the latest record of each key.
	CleanupPolicy_CLEANUP_POLICY_COMPACT CleanupPolicy = 2
)

// Enum value maps for CleanupPolicy.
var (
	CleanupPolicy_name = map[int32]string{
		0: "CLEANUP_POLICY_UNSPECIFIED",
		1: "CLEANUP_POLICY_DELETE",
		2: "CLEANUP_POLICY_COMPACT",
	}
	CleanupPolicy_value = map[string]int32{
		"CLEANUP_POLICY_UNSPECIFIED": 0,
		"CLEANUP_POLICY_DELETE":      1,
		"CLEANUP_POLICY_COMPACT":     2,
	}
)

func (x CleanupPolicy) Enum() *CleanupPolicy {
	p := new(CleanupPolicy)
	*p = x
	return p
}

func (x CleanupPolicy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CleanupPolicy) Descriptor() protoreflect.EnumDescriptor {
	return file_kafka_asyncapi_v1_annotations_proto_enumTypes[1].Descriptor()
}

func (CleanupPolicy) Type() protoreflect.EnumType {
	return &file_kafka_asyncapi_v1_annotations_proto_enumTypes[1]
}

func (x CleanupPolicy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CleanupPolicy.Descriptor instead.
func (CleanupPolicy) EnumDescriptor() ([]byte, []int) {
	return file_kafka_asyncapi_v1_annotations_proto_rawDescGZIP(), []int{1}
}

// Compression is a compression codec.
type Compression int32

const (
	Compression_COMPRESSION_UNSPECIFIED Compression = 0
	Compression_COMPRESSION_NONE        Compression = 1
	Compression_COMPRESSION_GZIP        Compression = 2
	Compression_COMPRESSION_SNAPPY      Compression = 3
	Compression_COMPRESSION_LZ4         Compression = 4
	Compression_COMPRESSION_ZSTD        Compression = 5
	// Topics only: keep the producer's codec.
	Compression_COMPRESSION_PRODUCER Compression = 6
)

// Enum value maps for Compression.
var (
	Compression_name = map[int32]string{
		0: "COMPRESSION_UNSPECIFIED",
		1: "COMPRESSION_NONE",
		2: "COMPRESSION_GZIP",
		3: "COMPRESSION_SNAPPY",
		4: "COMPRESSION_LZ4",
		5: "COMPRESSION_ZSTD",
		6: "COMPRESSION_PRODUCER",
	}
	Compression_value = map[string]int32{
		"COMPRESSION_UNSPECIFIED": 0,
		"COMPRESSION_NONE":        1,
		"COMPRESSION_GZIP":        2,
		"COMPRESSION_SNAPPY":      3,
		"COMPRESSION_LZ4":         4,
		"COMPRESSION_ZSTD":        5,
		"COMPRESSION_PRODUCER":    6,
	}
)

func (x Compression) Enum() *Compression {
	p := new(Compression)
	*p = x
	return p
}

func (x Compression) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Compression) Descriptor() protoreflect.EnumDescriptor {
	return file_kafka_asyncapi_v1_annotations_proto_enumTypes[2].Descriptor()
}

func (Compression) Type() protoreflect.EnumType {
	return &file_kafka_asyncapi_v1_annotations_proto_enumTypes[2]
}

func (x Compression) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Compression.Descriptor instead.
func (Compression) EnumDescriptor() ([]byte, []int) {
	return file_kafka_asyncapi_v1_annotations_proto_rawDescGZIP(), []int{2}
}

// Pattern is the messaging pattern of an rpc. When unspecified it is
// inferred from the rpc's shape, which only picks core AsyncAPI operations:
//
//   - an rpc with a response, streaming or not, is REQUEST_REPLY;
//   - a server streaming rpc without request (google.protobuf.Empty)
//     PUBLISHes;
//   - an rpc returning google.protobuf.Empty SUBSCRIBEs;
//   - a bidirectional streaming rpc is a PROCESS.
//
// A client streaming rpc with a response must set the pattern.
type Pattern int32

const (
	Pattern_PATTERN_UNSPECIFIED Pattern = 0
	// The service consumes requests and produces each reply to reply_topic.
	Pattern_PATTERN_REQUEST_REPLY Pattern = 1
	// The service produces records.
	Pattern_PATTERN_PUBLISH Pattern = 2
	// The service consumes records.
	Pattern_PATTERN_SUBSCRIBE Pattern = 3
	// The service receives the input on the operation's channel and sends the
	// output (the response) on the output channel, without replying: two
	// operations, e.g. a stream processor.
	Pattern_PATTERN_PROCESS Pattern = 4
)

// Enum value maps for Pattern.
var (
	Pattern_name = map[int32]string{
		0: "PATTERN_UNSPECIFIED",
		1: "PATTERN_REQUEST_REPLY",
		2: "PATTERN_PUBLISH",
		3: "PATTERN_SUBSCRIBE",
		4: "PATTERN_PROCESS",
	}
	Pattern_value = map[string]int32{
		"PATTERN_UNSPECIFIED":   0,
		"PATTERN_REQUEST_REPLY": 1,
		"PATTERN_PUBLISH":       2,
		"PATTERN_SUBSCRIBE":     3,
		"PATTERN_PROCESS":       4,
	}
)

func (x Pattern) Enum() *Pattern {
	p := new(Pattern)
	*p = x
	return p
}

func (x Pattern) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Pattern) Descriptor() protoreflect.EnumDescriptor {
	return file_kafka_asyncapi_v1_annotations_proto_enumTypes[3].Descriptor()
}

func (Pattern) Type() protoreflect.EnumType {
	return &file_kafka_asyncapi_v1_annotations_proto_enumTypes[3]
}

func (x Pattern) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Pattern.Descriptor instead.
func (Pattern) EnumDescriptor() ([]byte, []int) {
	return file_kafka_asyncapi_v1_annotations_proto_rawDescGZIP(), []int{3}
}

// Acks is the producer acks setting.
type Acks int32

const (
	Acks_ACKS_UNSPECIFIED Acks = 0
	// acks=0: fire and forget.
	Acks_ACKS_NONE Acks = 1
	// acks=1: the leader.
	Acks_ACKS_LEADER Acks = 2
	// acks=all: every in-sync replica.
	Acks_ACKS_ALL Acks = 3
)

// Enum value maps for Acks.
var (
	Acks_name = map[int32]string{
		0: "ACKS_UNSPECIFIED",
		1: "ACKS_NONE",
		2: "ACKS_LEADER",
		3: "ACKS_ALL",
	}
	Acks_value = map[string]int32{
		"ACKS_UNSPECIFIED": 0,
		"ACKS_NONE":        1,
		"ACKS_LEADER":      2,
		"ACKS_ALL":         3,
	}
)

func (x Acks) Enum() *Acks {
	p := new(Acks)
	*p = x
	return p
}

func (x Acks) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Acks) Descriptor() protoreflect.EnumDescriptor {
	return file_kafka_asyncapi_v1_annotations_proto_enumTypes[4].Descriptor()
}

func (Acks) Type() protoreflect.EnumType {
	return &file_kafka_asyncapi_v1_annotations_proto_enumTypes[4]
}

func (x Acks) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Acks.Descriptor instead.
func (Acks) EnumDescriptor() ([]byte, []int) {
	return file_kafka_asyncapi_v1_annotations_proto_rawDescGZIP(), []int{4}
}

// OffsetReset is the auto.offset.reset setting.
type OffsetReset int32

const (
	OffsetReset_OFFSET_RESET_UNSPECIFIED OffsetReset = 0
	OffsetReset_OFFSET_RESET_EARLIEST    OffsetReset = 1
	OffsetReset_OFFSET_RESET_LATEST      OffsetReset = 2
	// Fail when there is no committed offset.
	OffsetReset_OFFSET_RESET_NONE OffsetReset = 3
)

// Enum value maps for OffsetReset.
var (
	OffsetReset_name = map[int32]string{
		0: "OFFSET_RESET_UNSPECIFIED",
		1: "OFFSET_RESET_EARLIEST",
		2: "OFFSET_RESET_LATEST",
		3: "OFFSET_RESET_NONE",
	}
	OffsetReset_value = map[string]int32{
		"OFFSET_RESET_UNSPECIFIED": 0,
		"OFFSET_RESET_EARLIEST":    1,
		"OFFSET_RESET_LATEST":      2,
		"OFFSET_RESET_NONE":        3,
	}
)

func (x OffsetReset) Enum() *OffsetReset {
	p := new(OffsetReset)
	*p = x
	return p
}

func (x OffsetReset) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OffsetReset) Descriptor() protoreflect.EnumDescriptor {
	return file_kafka_asyncapi_v1_annotations_proto_enumTypes[5].Descriptor()
}

func (OffsetReset) Type() protoreflect.EnumType {
	return &file_kafka_asyncapi_v1_annotations_proto_enumTypes[5]
}

func (x OffsetReset) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OffsetReset.Descriptor instead.
func (OffsetReset) EnumDescriptor() ([]byte, []int) {
	return file_kafka_asyncapi_v1_annotations_proto_rawDescGZIP(), []int{5}
}

// AssignmentStrategy is a partition.assignment.strategy.
type AssignmentStrategy int32

const (
	AssignmentStrategy_ASSIGNMENT_STRATEGY_UNSPECIFIED        AssignmentStrategy = 0
	AssignmentStrategy_ASSIGNMENT_STRATEGY_RANGE              AssignmentStrategy = 1
	AssignmentStrategy_ASSIGNMENT_STRATEGY_ROUND_ROBIN        AssignmentStrategy = 2
	AssignmentStrategy_ASSIGNMENT_STRATEGY_STICKY             AssignmentStrategy = 3
	AssignmentStrategy_ASSIGNMENT_STRATEGY_COOPERATIVE_STICKY AssignmentStrategy = 4
)

// Enum value maps for AssignmentStrategy.
var (
	AssignmentStrategy_name = map[int32]string{
		0: "ASSIGNMENT_STRATEGY_UNSPECIFIED",
		1: "ASSIGNMENT_STRATEGY_RANGE",
		2: "ASSIGNMENT_STRATEGY_ROUND_ROBIN",
		3: "ASSIGNMENT_STRATEGY_STICKY",
		4: "ASSIGNMENT_STRATEGY_COOPERATIVE_STICKY",
	}
	AssignmentStrategy_value = map[string]int32{
		"ASSIGNMENT_STRATEGY_UNSPECIFIED":        0,
		"ASSIGNMENT_STRATEGY_RANGE":              1,
		"ASSIGNMENT_STRATEGY_ROUND_ROBIN":        2,
		"ASSIGNMENT_STRATEGY_STICKY":             3,
		"ASSIGNMENT_STRATEGY_COOPERATIVE_STICKY": 4,
	}
)

func (x AssignmentStrategy) Enum() *AssignmentStrategy {
	p := new(AssignmentStrategy)
	*p = x
	return p
}

func (x AssignmentStrategy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AssignmentStrategy) Descriptor() protoreflect.EnumDescriptor {
	return file_kafka_asyncapi_v1_annotations_proto_enumTypes[6].Descriptor()
}

func (AssignmentStrategy) Type() protoreflect.EnumType {
	return &file_kafka_asyncapi_v1_annotations_proto_enumTypes[6]
}

func (x AssignmentStrategy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AssignmentStrategy.Descriptor instead.
func (AssignmentStrategy) EnumDescriptor() ([]byte, []int) {
	return file_kafka_asyncapi_v1_annotations_proto_rawDescGZIP(), []int{6}
}

// SchemaIdLocation is where records carry their schema registry ID.
type SchemaIdLocation int32

const (
	SchemaIdLocation_SCHEMA_ID_LOCATION_UNSPECIFIED SchemaIdLocation = 0
	SchemaIdLocation_SCHEMA_ID_LOCATION_PAYLOAD     SchemaIdLocation = 1
	SchemaIdLocation_SCHEMA_ID_LOCATION_HEADER      SchemaIdLocation = 2
)

// Enum value maps for SchemaIdLocation.
var (
	SchemaIdLocation_name = map[int32]string{
		0: "SCHEMA_ID_LOCATION_UNSPECIFIED",
		1: "SCHEMA_ID_LOCATION_PAYLOAD",
		2: "SCHEMA_ID_LOCATION_HEADER",
	}
	SchemaIdLocation_value = map[string]int32{
		"SCHEMA_ID_LOCATION_UNSPECIFIED": 0,
		"SCHEMA_ID_LOCATION_PAYLOAD":     1,
		"SCHEMA_ID_LOCATION_HEADER":      2,
	}
)

func (x SchemaIdLocation) Enum() *SchemaIdLocation {
	p := new(SchemaIdLocation)
	*p = x
	return p
}

func (x SchemaIdLocation) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SchemaIdLocation) Descriptor() protoreflect.EnumDescriptor {
	return file_kafka_asyncapi_v1_annotations_proto_enumTypes[7].Descriptor()
}

func (SchemaIdLocation) Type() protoreflect.EnumType {
	return &file_kafka_asyncapi_v1_annotations_proto_enumTypes[7]
}

func (x SchemaIdLocation) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SchemaIdLocation.Descriptor instead.
func (SchemaIdLocation) EnumDescriptor() ([]byte, []int) {
	return file_kafka_asyncapi_v1_annotations_proto_rawDescGZIP(), []int{7}
}

// Document holds the Kafka specifics of a document. When several files are
// merged into one AsyncAPI document, the settings of all files (and of the
// files they import) are combined.
type Document struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Kafka details of servers declared in (asyncapi.v3.document).servers.
	Servers []*Server `protobuf:"bytes,1,rep,name=servers,proto3" json:"servers,omitempty"`
	// SASL or TLS mechanism of security schemes declared in
	// (asyncapi.v3.document).security_schemes.
	Auth []*Auth `protobuf:"bytes,2,rep,name=auth,proto3" json:"auth,omitempty"`
	// Topics.
	Topics        []*Topic `protobuf:"bytes,3,rep,name=topics,proto3" json:"topics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Document) Reset() {
	*x = Document{}
	mi := &file_kafka_asyncapi_v1_annotations_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Document) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Document) ProtoMessage() {}

func (x *Document) ProtoReflect() protoreflect.Message {
	mi := &file_kafka_asyncapi_v1_annotations_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Document.ProtoReflect.Descriptor instead.
func (*Document) Descriptor() ([]byte, []int) {
	return file_kafka_asyncapi_v1_annotations_proto_rawDescGZIP(), []int{0}
}

func (x *Document) GetServers() []*Server {
	if x != nil {
		return x.Servers
	}
	return nil
}

func (x *Document) GetAuth() []*Auth {
	if x != nil {
		return x.Auth
	}
	return nil
}

func (x *Document) GetTopics() []*Topic {
	if x != nil {
		return x.Topics
	}
	return nil
}

// Server adds Kafka details to a server (a bootstrap broker) declared with
// the asyncapi.v3 annotations.
type Server struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name of the (asyncapi.v3.document) server.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// URL of the schema registry, e.g. "https://registry.acme.example".
	SchemaRegistryUrl string `protobuf:"bytes,2,opt,name=schema_registry_url,json=schemaRegistryUrl,proto3" json:"schema_registry_url,omitempty"`
	// Schema registry vendor, e.g. "confluent" or "apicurio".
	SchemaRegistryVendor string `protobuf:"bytes,3,opt,name=schema_registry_vendor,json=schemaRegistryVendor,proto3" json:"schema_registry_vendor,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *Server) Reset() {
	*x = Server{}
	mi := &file_kafka_asyncapi_v1_annotations_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server) ProtoMessage() {}

func (x *Server) ProtoReflect() protoreflect.Message {
	mi := &file_kafka_asyncapi_v1_annotations_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server.ProtoReflect.Descriptor instead.
func (*Server) Descriptor() ([]byte, []int) {
	return file_kafka_asyncapi_v1_annotations_proto_rawDescGZIP(), []int{1}
}

func (x *Server) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Server) GetSchemaRegistryUrl() string {
	if x != nil {
		return x.SchemaRegistryUrl
	}
	return ""
}

func (x *Server) GetSchemaRegistryVendor() string {
	if x != nil {
		return x.SchemaRegistryVendor
	}
	return ""
}

// Auth sets the authentication mechanism of a security scheme. The scheme
// type is derived from it unless the scheme sets one.
type Auth struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name of the (asyncapi.v3.document) security scheme.
	Scheme        string    `protobuf:"bytes,1,opt,name=scheme,proto3" json:"scheme,omitempty"`
	Mechanism     Mechanism `protobuf:"varint,2,opt,name=mechanism,proto3,enum=kafka.asyncapi.v1.Mechanism" json:"mechanism,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Auth) Reset() {
	*x = Auth{}
	mi := &file_kafka_asyncapi_v1_annotations_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Auth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Auth) ProtoMessage() {}

func (x *Auth) ProtoReflect() protoreflect.Message {
	mi := &file_kafka_asyncapi_v1_annotations_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Auth.ProtoReflect.Descriptor instead.
func (*Auth) Descriptor() ([]byte, []int) {
	return file_kafka_asyncapi_v1_annotations_proto_rawDescGZIP(), []int{2}
}

func (x *Auth) GetScheme() string {
	if x != nil {
		return x.Scheme
	}
	return ""
}

func (x *Auth) GetMechanism() Mechanism {
	if x != nil {
		return x.Mechanism
	}
	return Mechanism_MECHANISM_UNSPECIFIED
}

// Topic declares a topic and its configuration.
type Topic struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Topic name: 1 to 249 letters, digits, '.', '_' and '-'.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Number of partitions.
	Partitions int32 `protobuf:"varint,2,opt,name=partitions,proto3" json:"partitions,omitempty"`
	// Replication factor.
	Replicas int32 `protobuf:"varint,3,opt,name=replicas,proto3" json:"replicas,omitempty"`
	// cleanup.policy.
	CleanupPolicy []CleanupPolicy `protobuf:"varint,4,rep,packed,name=cleanup_policy,json=cleanupPolicy,proto3,enum=kafka.asyncapi.v1.CleanupPolicy" json:"cleanup_policy,omitempty"`
	// retention.ms, e.g. "168h"; "-1" keeps records forever.
	Retention string `protobuf:"bytes,5,opt,name=retention,proto3" json:"retention,omitempty"`
	// retention.bytes per partition; -1 for no limit.
	RetentionBytes int64 `protobuf:"varint,6,opt,name=retention_bytes,json=retentionBytes,proto3" json:"retention_bytes,omitempty"`
	// delete.retention.ms: how long tombstones of compacted topics are kept.
	DeleteRetention string `protobuf:"bytes,7,opt,name=delete_retention,json=deleteRetention,proto3" json:"delete_retention,omitempty"`
	// max.message.bytes: the largest record batch.
	MaxMessageBytes int32 `protobuf:"varint,8,opt,name=max_message_bytes,json=maxMessageBytes,proto3" json:"max_message_bytes,omitempty"`
	// min.insync.replicas: replicas that must acknowledge acks=all writes.
	MinInsyncReplicas int32 `protobuf:"varint,9,opt,name=min_insync_replicas,json=minInsyncReplicas,proto3" json:"min_insync_replicas,omitempty"`
	// compression.type of stored records.
	Compression Compression `protobuf:"varint,10,opt,name=compression,proto3,enum=kafka.asyncapi.v1.Compression" json:"compression,omitempty"`
	// confluent.key.schema.validation: brokers validate record keys against
	// the schema registry.
	KeySchemaValidation bool `protobuf:"varint,11,opt,name=key_schema_validation,json=keySchemaValidation,proto3" json:"key_schema_validation,omitempty"`
	// confluent.value.schema.validation.
	ValueSchemaValidation bool `protobuf:"varint,12,opt,name=value_schema_validation,json=valueSchemaValidation,proto3" json:"value_schema_validation,omitempty"`
	// confluent.key.subject.name.strategy, e.g. "TopicNameStrategy".
	KeySubjectNameStrategy string `protobuf:"bytes,13,opt,name=key_subject_name_strategy,json=keySubjectNameStrategy,proto3" json:"key_subject_name_strategy,omitempty"`
	// confluent.value.subject.name.strategy.
	ValueSubjectNameStrategy string `protobuf:"bytes,14,opt,name=value_subject_name_strategy,json=valueSubjectNameStrategy,proto3" json:"value_subject_name_strategy,omitempty"`
	// Other topic configurations, e.g. {"segment.ms": "3600000"}.
	Configs       map[string]string `protobuf:"bytes,15,rep,name=configs,proto3" json:"configs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Description   string            `protobuf:"bytes,16,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Topic) Reset() {
	*x = Topic{}
	mi := &file_kafka_asyncapi_v1_annotations_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Topic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Topic) ProtoMessage() {}

func (x *Topic) ProtoReflect() protoreflect.Message {
	mi := &file_kafka_asyncapi_v1_annotations_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Topic.ProtoReflect.Descriptor instead.
func (*Topic) Descriptor() ([]byte, []int) {
	return file_kafka_asyncapi_v1_annotations_proto_rawDescGZIP(), []int{3}
}

func (x *Topic) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Topic) GetPartitions() int32 {
	if x != nil {
		return x.Partitions
	}
	return 0
}

func (x *Topic) GetReplicas() int32 {
	if x != nil {
		return x.Replicas
	}
	return 0
}

func (x *Topic) GetCleanupPolicy() []CleanupPolicy {
	if x != nil {
		return x.CleanupPolicy
	}
	return nil
}

func (x *Topic) GetRetention() string {
	if x != nil {
		return x.Retention
	}
	return ""
}

func (x *Topic) GetRetentionBytes() int64 {
	if x != nil {
		return x.RetentionBytes
	}
	return 0
}

func (x *Topic) GetDeleteRetention() string {
	if x != nil {
		return x.DeleteRetention
	}
	return ""
}

func (x *Topic) GetMaxMessageBytes() int32 {
	if x != nil {
		return x.MaxMessageBytes
	}
	return 0
}

func (x *Topic) GetMinInsyncReplicas() int32 {
	if x != nil {
		return x.MinInsyncReplicas
	}
	return 0
}

func (x *Topic) GetCompression() Compression {
	if x != nil {
		return x.Compression
	}
	return Compression_COMPRESSION_UNSPECIFIED
}

func (x *Topic) GetKeySchemaValidation() bool {
	if x != nil {
		return x.KeySchemaValidation
	}
	return false
}

func (x *Topic) GetValueSchemaValidation() bool {
	if x != nil {
		return x.ValueSchemaValidation
	}
	return false
}

func (x *Topic) GetKeySubjectNameStrategy() string {
	if x != nil {
		return x.KeySubjectNameStrategy
	}
	return ""
}

func (x *Topic) GetValueSubjectNameStrategy() string {
	if x != nil {
		return x.ValueSubjectNameStrategy
	}
	return ""
}

func (x *Topic) GetConfigs() map[string]string {
	if x != nil {
		return x.Configs
	}
	return nil
}

func (x *Topic) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// Service holds defaults for every rpc of a service.
type Service struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Prefix of the topic names of the service's rpcs, joined with '.'.
	TopicPrefix string `protobuf:"bytes,1,opt,name=topic_prefix,json=topicPrefix,proto3" json:"topic_prefix,omitempty"`
	// Consumer group of the service's consumers.
	GroupId string `protobuf:"bytes,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	// client.id of the service's producers and consumers.
	ClientId      string `protobuf:"bytes,3,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Service) Reset() {
	*x = Service{}
	mi := &file_kafka_asyncapi_v1_annotations_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Service) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Service) ProtoMessage() {}

func (x *Service) ProtoReflect() protoreflect.Message {
	mi := &file_kafka_asyncapi_v1_annotations_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Service.ProtoReflect.Descriptor instead.
func (*Service) Descriptor() ([]byte, []int) {
	return file_kafka_asyncapi_v1_annotations_proto_rawDescGZIP(), []int{4}
}

func (x *Service) GetTopicPrefix() string {
	if x != nil {
		return x.TopicPrefix
	}
	return ""
}

func (x *Service) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *Service) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

// Operation describes the Kafka operation of an rpc.
type Operation struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Messaging pattern; inferred when unspecified.
	Pattern Pattern `protobuf:"varint,1,opt,name=pattern,proto3,enum=kafka.asyncapi.v1.Pattern" json:"pattern,omitempty"`
	// Topic name, relative to the service's topic_prefix.
	Topic string `protobuf:"bytes,2,opt,name=topic,proto3" json:"topic,omitempty"`
	// Consumer group; defaults to the service's for its own consumers.
	GroupId string `protobuf:"bytes,3,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	// client.id; defaults to the service's.
	ClientId string `protobuf:"bytes,4,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	// Producer settings.
	Produce *Produce `protobuf:"bytes,5,opt,name=produce,proto3" json:"produce,omitempty"`
	// Consumer settings.
	Consume *Consume `protobuf:"bytes,6,opt,name=consume,proto3" json:"consume,omitempty"`
	// REQUEST_REPLY: topic replies are produced to (required), relative to
	// the service's topic_prefix.
	ReplyTopic string `protobuf:"bytes,7,opt,name=reply_topic,json=replyTopic,proto3" json:"reply_topic,omitempty"`
	// REQUEST_REPLY: additional reply messages (full Protobuf names), e.g.
	// an error message.
	ReplyMessages []string `protobuf:"bytes,8,rep,name=reply_messages,json=replyMessages,proto3" json:"reply_messages,omitempty"`
	// REQUEST_REPLY: header correlating replies with requests. Defaults to
	// "correlation_id".
	CorrelationHeader string `protobuf:"bytes,9,opt,name=correlation_header,json=correlationHeader,proto3" json:"correlation_header,omitempty"`
	// PROCESS: Topic the output is produced to, relative to the service's
	// topic_prefix. Defaults to the input topic followed by ".output".
	Output        string `protobuf:"bytes,10,opt,name=output,proto3" json:"output,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Operation) Reset() {
	*x = Operation{}
	mi := &file_kafka_asyncapi_v1_annotations_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Operation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Operation) ProtoMessage() {}

func (x *Operation) ProtoReflect() protoreflect.Message {
	mi := &file_kafka_asyncapi_v1_annotations_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Operation.ProtoReflect.Descriptor instead.
func (*Operation) Descriptor() ([]byte, []int) {
	return file_kafka_asyncapi_v1_annotations_proto_rawDescGZIP(), []int{5}
}

func (x *Operation) GetPattern() Pattern {
	if x != nil {
		return x.Pattern
	}
	return Pattern_PATTERN_UNSPECIFIED
}

func (x *Operation) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *Operation) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *Operation) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *Operation) GetProduce() *Produce {
	if x != nil {
		return x.Produce
	}
	return nil
}

func (x *Operation) GetConsume() *Consume {
	if x != nil {
		return x.Consume
	}
	return nil
}

func (x *Operation) GetReplyTopic() string {
	if x != nil {
		return x.ReplyTopic
	}
	return ""
}

func (x *Operation) GetReplyMessages() []string {
	if x != nil {
		return x.ReplyMessages
	}
	return nil
}

func (x *Operation) GetCorrelationHeader() string {
	if x != nil {
		return x.CorrelationHeader
	}
	return ""
}

func (x *Operation) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

// Produce holds producer settings.
type Produce struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// acks: which replicas acknowledge a write.
	Acks Acks `protobuf:"varint,1,opt,name=acks,proto3,enum=kafka.asyncapi.v1.Acks" json:"acks,omitempty"`
	// enable.idempotence: exactly-once writes per partition (requires
	// acks=all).
	Idempotent bool `protobuf:"varint,2,opt,name=idempotent,proto3" json:"idempotent,omitempty"`
	// transactional.id of a transactional producer (implies idempotence).
	TransactionalId string `protobuf:"bytes,3,opt,name=transactional_id,json=transactionalId,proto3" json:"transactional_id,omitempty"`
	// compression.type of produced batches.
	Compression Compression `protobuf:"varint,4,opt,name=compression,proto3,enum=kafka.asyncapi.v1.Compression" json:"compression,omitempty"`
	// linger.ms, e.g. "5ms".
	Linger string `protobuf:"bytes,5,opt,name=linger,proto3" json:"linger,omitempty"`
	// batch.size in bytes.
	BatchSize int32 `protobuf:"varint,6,opt,name=batch_size,json=batchSize,proto3" json:"batch_size,omitempty"`
	// delivery.timeout.ms, e.g. "2m".
	DeliveryTimeout string `protobuf:"bytes,7,opt,name=delivery_timeout,json=deliveryTimeout,proto3" json:"delivery_timeout,omitempty"`
	// Partitioner, e.g. "murmur2" or a class name.
	Partitioner   string `protobuf:"bytes,8,opt,name=partitioner,proto3" json:"partitioner,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Produce) Reset() {
	*x = Produce{}
	mi := &file_kafka_asyncapi_v1_annotations_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Produce) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Produce) ProtoMessage() {}

func (x *Produce) ProtoReflect() protoreflect.Message {
	mi := &file_kafka_asyncapi_v1_annotations_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Produce.ProtoReflect.Descriptor instead.
func (*Produce) Descriptor() ([]byte, []int) {
	return file_kafka_asyncapi_v1_annotations_proto_rawDescGZIP(), []int{6}
}

func (x *Produce) GetAcks() Acks {
	if x != nil {
		return x.Acks
	}
	return Acks_ACKS_UNSPECIFIED
}

func (x *Produce) GetIdempotent() bool {
	if x != nil {
		return x.Idempotent
	}
	return false
}

func (x *Produce) GetTransactionalId() string {
	if x != nil {
		return x.TransactionalId
	}
	return ""
}

func (x *Produce) GetCompression() Compression {
	if x != nil {
		return x.Compression
	}
	return Compression_COMPRESSION_UNSPECIFIED
}

func (x *Produce) GetLinger() string {
	if x != nil {
		return x.Linger
	}
	return ""
}

func (x *Produce) GetBatchSize() int32 {
	if x != nil {
		return x.BatchSize
	}
	return 0
}

func (x *Produce) GetDeliveryTimeout() string {
	if x != nil {
		return x.DeliveryTimeout
	}
	return ""
}

func (x *Produce) GetPartitioner() string {
	if x != nil {
		return x.Partitioner
	}
	return ""
}

// Consume holds consumer settings.
type Consume struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// auto.offset.reset: where a group without committed offsets starts.
	AutoOffsetReset OffsetReset `protobuf:"varint,1,opt,name=auto_offset_reset,json=autoOffsetReset,proto3,enum=kafka.asyncapi.v1.OffsetReset" json:"auto_offset_reset,omitempty"`
	// isolation.level: read only committed transactional records.
	ReadCommitted bool `protobuf:"varint,2,opt,name=read_committed,json=readCommitted,proto3" json:"read_committed,omitempty"`
	// enable.auto.commit.
	AutoCommit bool `protobuf:"varint,3,opt,name=auto_commit,json=autoCommit,proto3" json:"auto_commit,omitempty"`
	// max.poll.records.
	MaxPollRecords int32 `protobuf:"varint,4,opt,name=max_poll_records,json=maxPollRecords,proto3" json:"max_poll_records,omitempty"`
	// session.timeout.ms, e.g. "45s".
	SessionTimeout string `protobuf:"bytes,5,opt,name=session_timeout,json=sessionTimeout,proto3" json:"session_timeout,omitempty"`
	// max.poll.interval.ms, e.g. "5m".
	MaxPollInterval string `protobuf:"bytes,6,opt,name=max_poll_interval,json=maxPollInterval,proto3" json:"max_poll_interval,omitempty"`
	// partition.assignment.strategy.
	AssignmentStrategy AssignmentStrategy `protobuf:"varint,7,opt,name=assignment_strategy,json=assignmentStrategy,proto3,enum=kafka.asyncapi.v1.AssignmentStrategy" json:"assignment_strategy,omitempty"`
	// group.instance.id for static membership, e.g. "worker-{hostname}".
	GroupInstanceId string `protobuf:"bytes,8,opt,name=group_instance_id,json=groupInstanceId,proto3" json:"group_instance_id,omitempty"`
	// Use the consumer group protocol of KIP-848 (group.protocol=consumer).
	NextGenRebalance bool `protobuf:"varint,9,opt,name=next_gen_rebalance,json=nextGenRebalance,proto3" json:"next_gen_rebalance,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Consume) Reset() {
	*x = Consume{}
	mi := &file_kafka_asyncapi_v1_annotations_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Consume) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Consume) ProtoMessage() {}

func (x *Consume) ProtoReflect() protoreflect.Message {
	mi := &file_kafka_asyncapi_v1_annotations_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Consume.ProtoReflect.Descriptor instead.
func (*Consume) Descriptor() ([]byte, []int) {
	return file_kafka_asyncapi_v1_annotations_proto_rawDescGZIP(), []int{7}
}

func (x *Consume) GetAutoOffsetReset() OffsetReset {
	if x != nil {
		return x.AutoOffsetReset
	}
	return OffsetReset_OFFSET_RESET_UNSPECIFIED
}

func (x *Consume) GetReadCommitted() bool {
	if x != nil {
		return x.ReadCommitted
	}
	return false
}

func (x *Consume) GetAutoCommit() bool {
	if x != nil {
		return x.AutoCommit
	}
	return false
}

func (x *Consume) GetMaxPollRecords() int32 {
	if x != nil {
		return x.MaxPollRecords
	}
	return 0
}

func (x *Consume) GetSessionTimeout() string {
	if x != nil {
		return x.SessionTimeout
	}
	return ""
}

func (x *Consume) GetMaxPollInterval() string {
	if x != nil {
		return x.MaxPollInterval
	}
	return ""
}

func (x *Consume) GetAssignmentStrategy() AssignmentStrategy {
	if x != nil {
		return x.AssignmentStrategy
	}
	return AssignmentStrategy_ASSIGNMENT_STRATEGY_UNSPECIFIED
}

func (x *Consume) GetGroupInstanceId() string {
	if x != nil {
		return x.GroupInstanceId
	}
	return ""
}

func (x *Consume) GetNextGenRebalance() bool {
	if x != nil {
		return x.NextGenRebalance
	}
	return false
}

// Message holds Kafka properties of a message, and optionally gives it its
// own topic, documented even when no rpc uses it.
type Message struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Topic of the message's own channel.
	Topic string `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	// Record key.
	Key *Key `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	// Where the schema registry ID of the value is stored.
	SchemaIdLocation SchemaIdLocation `protobuf:"varint,3,opt,name=schema_id_location,json=schemaIdLocation,proto3,enum=kafka.asyncapi.v1.SchemaIdLocation" json:"schema_id_location,omitempty"`
	// How the schema ID is encoded in the payload, e.g. "confluent" (magic
	// byte and 4-byte ID) or "apicurio-new".
	SchemaIdPayloadEncoding string `protobuf:"bytes,4,opt,name=schema_id_payload_encoding,json=schemaIdPayloadEncoding,proto3" json:"schema_id_payload_encoding,omitempty"`
	// Subject naming strategy of the value, e.g. "TopicNameStrategy" or
	// "RecordNameStrategy".
	SchemaLookupStrategy string `protobuf:"bytes,5,opt,name=schema_lookup_strategy,json=schemaLookupStrategy,proto3" json:"schema_lookup_strategy,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_kafka_asyncapi_v1_annotations_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_kafka_asyncapi_v1_annotations_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_kafka_asyncapi_v1_annotations_proto_rawDescGZIP(), []int{8}
}

func (x *Message) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *Message) GetKey() *Key {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *Message) GetSchemaIdLocation() SchemaIdLocation {
	if x != nil {
		return x.SchemaIdLocation
	}
	return SchemaIdLocation_SCHEMA_ID_LOCATION_UNSPECIFIED
}

func (x *Message) GetSchemaIdPayloadEncoding() string {
	if x != nil {
		return x.SchemaIdPayloadEncoding
	}
	return ""
}

func (x *Message) GetSchemaLookupStrategy() string {
	if x != nil {
		return x.SchemaLookupStrategy
	}
	return ""
}

// Key describes the record key.
type Key struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Key:
	//
	//	*Key_Field
	//	*Key_Message
	//	*Key_Schema
	Key           isKey_Key `protobuf_oneof:"key"`
	Description   string    `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Key) Reset() {
	*x = Key{}
	mi := &file_kafka_asyncapi_v1_annotations_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Key) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Key) ProtoMessage() {}

func (x *Key) ProtoReflect() protoreflect.Message {
	mi := &file_kafka_asyncapi_v1_annotations_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Key.ProtoReflect.Descriptor instead.
func (*Key) Descriptor() ([]byte, []int) {
	return file_kafka_asyncapi_v1_annotations_proto_rawDescGZIP(), []int{9}
}

func (x *Key) GetKey() isKey_Key {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *Key) GetField() string {
	if x != nil {
		if x, ok := x.Key.(*Key_Field); ok {
			return x.Field
		}
	}
	return ""
}

func (x *Key) GetMessage() string {
	if x != nil {
		if x, ok := x.Key.(*Key_Message); ok {
			return x.Message
		}
	}
	return ""
}

func (x *Key) GetSchema() string {
	if x != nil {
		if x, ok := x.Key.(*Key_Schema); ok {
			return x.Schema
		}
	}
	return ""
}

func (x *Key) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type isKey_Key interface {
	isKey_Key()
}

type Key_Field struct {
	// A field of the message is the key; its schema is the field's.
	Field string `protobuf:"bytes,1,opt,name=field,proto3,oneof"`
}

type Key_Message struct {
	// A Protobuf message (full name) is the key.
	Message string `protobuf:"bytes,2,opt,name=message,proto3,oneof"`
}

type Key_Schema struct {
	// The key's schema as JSON, e.g. {"type": "string", "format": "uuid"}.
	Schema string `protobuf:"bytes,3,opt,name=schema,proto3,oneof"`
}

func (*Key_Field) isKey_Key() {}

func (*Key_Message) isKey_Key() {}

func (*Key_Schema) isKey_Key() {}

var file_kafka_asyncapi_v1_annotations_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.FileOptions)(nil),
		ExtensionType: (*Document)(nil),
		Field:         58360,
		Name:          "kafka.asyncapi.v1.document",
		Tag:           "bytes,58360,opt,name=document",
		Filename:      "kafka/asyncapi/v1/annotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.ServiceOptions)(nil),
		ExtensionType: (*Service)(nil),
		Field:         58360,
		Name:          "kafka.asyncapi.v1.service",
		Tag:           "bytes,58360,opt,name=service",
		Filename:      "kafka/asyncapi/v1/annotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*Operation)(nil),
		Field:         58360,
		Name:          "kafka.asyncapi.v1.operation",
		Tag:           "bytes,58360,opt,name=operation",
		Filename:      "kafka/asyncapi/v1/annotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*Message)(nil),
		Field:         58360,
		Name:          "kafka.asyncapi.v1.message",
		Tag:           "bytes,58360,opt,name=message",
		Filename:      "kafka/asyncapi/v1/annotations.proto",
	},
}

// Extension fields to descriptorpb.FileOptions.
var (
	// Kafka specifics of the document: servers, authentication and topics.
	//
	// optional kafka.asyncapi.v1.Document document = 58360;
	E_Document = &file_kafka_asyncapi_v1_annotations_proto_extTypes[0]
)

// Extension fields to descriptorpb.ServiceOptions.
var (
	// Kafka defaults applied to every rpc of the service.
	//
	// optional kafka.asyncapi.v1.Service service = 58360;
	E_Service = &file_kafka_asyncapi_v1_annotations_proto_extTypes[1]
)

// Extension fields to descriptorpb.MethodOptions.
var (
	// Describes the Kafka operation implemented by an rpc.
	//
	// optional kafka.asyncapi.v1.Operation operation = 58360;
	E_Operation = &file_kafka_asyncapi_v1_annotations_proto_extTypes[2]
)

// Extension fields to descriptorpb.MessageOptions.
var (
	// Kafka properties of a message (key, schema registry), and optionally
	// its own topic.
	//
	// optional kafka.asyncapi.v1.Message message = 58360;
	E_Message = &file_kafka_asyncapi_v1_annotations_proto_extTypes[3]
)

var File_kafka_asyncapi_v1_annotations_proto protoreflect.FileDescriptor

const file_kafka_asyncapi_v1_annotations_proto_rawDesc = "" +
	"\n" +
	"#kafka/asyncapi/v1/annotations.proto\x12\x11kafka.asyncapi.v1\x1a google/protobuf/descriptor.proto\"\x9e\x01\n" +
	"\bDocument\x123\n" +
	"\aservers\x18\x01 \x03(\v2\x19.kafka.asyncapi.v1.ServerR\aservers\x12+\n" +
	"\x04auth\x18\x02 \x03(\v2\x17.kafka.asyncapi.v1.AuthR\x04auth\x120\n" +
	"\x06topics\x18\x03 \x03(\v2\x18.kafka.asyncapi.v1.TopicR\x06topics\"\x82\x01\n" +
	"\x06Server\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12.\n" +
	"\x13schema_registry_url\x18\x02 \x01(\tR\x11schemaRegistryUrl\x124\n" +
	"\x16schema_registry_vendor\x18\x03 \x01(\tR\x14schemaRegistryVendor\"Z\n" +
	"\x04Auth\x12\x16\n" +
	"\x06scheme\x18\x01 \x01(\tR\x06scheme\x12:\n" +
	"\tmechanism\x18\x02 \x01(\x0e2\x1c.kafka.asyncapi.v1.MechanismR\tmechanism\"\xb5\x06\n" +
	"\x05Topic\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1e\n" +
	"\n" +
	"partitions\x18\x02 \x01(\x05R\n" +
	"partitions\x12\x1a\n" +
	"\breplicas\x18\x03 \x01(\x05R\breplicas\x12G\n" +
	"\x0ecleanup_policy\x18\x04 \x03(\x0e2 .kafka.asyncapi.v1.CleanupPolicyR\rcleanupPolicy\x12\x1c\n" +
	"\tretention\x18\x05 \x01(\tR\tretention\x12'\n" +
	"\x0fretention_bytes\x18\x06 \x01(\x03R\x0eretentionBytes\x12)\n" +
	"\x10delete_retention\x18\a \x01(\tR\x0fdeleteRetention\x12*\n" +
	"\x11max_message_bytes\x18\b \x01(\x05R\x0fmaxMessageBytes\x12.\n" +
	"\x13min_insync_replicas\x18\t \x01(\x05R\x11minInsyncReplicas\x12@\n" +
	"\vcompression\x18\n" +
	" \x01(\x0e2\x1e.kafka.asyncapi.v1.CompressionR\vcompression\x122\n" +
	"\x15key_schema_validation\x18\v \x01(\bR\x13keySchemaValidation\x126\n" +
	"\x17value_schema_validation\x18\f \x01(\bR\x15valueSchemaValidation\x129\n" +
	"\x19key_subject_name_strategy\x18\r \x01(\tR\x16keySubjectNameStrategy\x12=\n" +
	"\x1bvalue_subject_name_strategy\x18\x0e \x01(\tR\x18valueSubjectNameStrategy\x12?\n" +
	"\aconfigs\x18\x0f \x03(\v2%.kafka.asyncapi.v1.Topic.ConfigsEntryR\aconfigs\x12 \n" +
	"\vdescription\x18\x10 \x01(\tR\vdescription\x1a:\n" +
	"\fConfigsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"d\n" +
	"\aService\x12!\n" +
	"\ftopic_prefix\x18\x01 \x01(\tR\vtopicPrefix\x12\x19\n" +
	"\bgroup_id\x18\x02 \x01(\tR\agroupId\x12\x1b\n" +
	"\tclient_id\x18\x03 \x01(\tR\bclientId\"\x8a\x03\n" +
	"\tOperation\x124\n" +
	"\apattern\x18\x01 \x01(\x0e2\x1a.kafka.asyncapi.v1.PatternR\apattern\x12\x14\n" +
	"\x05topic\x18\x02 \x01(\tR\x05topic\x12\x19\n" +
	"\bgroup_id\x18\x03 \x01(\tR\agroupId\x12\x1b\n" +
	"\tclient_id\x18\x04 \x01(\tR\bclientId\x124\n" +
	"\aproduce\x18\x05 \x01(\v2\x1a.kafka.asyncapi.v1.ProduceR\aproduce\x124\n" +
	"\aconsume\x18\x06 \x01(\v2\x1a.kafka.asyncapi.v1.ConsumeR\aconsume\x12\x1f\n" +
	"\vreply_topic\x18\a \x01(\tR\n" +
	"replyTopic\x12%\n" +
	"\x0ereply_messages\x18\b \x03(\tR\rreplyMessages\x12-\n" +
	"\x12correlation_header\x18\t \x01(\tR\x11correlationHeader\x12\x16\n" +
	"\x06output\x18\n" +
	" \x01(\tR\x06output\"\xc7\x02\n" +
	"\aProduce\x12+\n" +
	"\x04acks\x18\x01 \x01(\x0e2\x17.kafka.asyncapi.v1.AcksR\x04acks\x12\x1e\n" +
	"\n" +
	"idempotent\x18\x02 \x01(\bR\n" +
	"idempotent\x12)\n" +
	"\x10transactional_id\x18\x03 \x01(\tR\x0ftransactionalId\x12@\n" +
	"\vcompression\x18\x04 \x01(\x0e2\x1e.kafka.asyncapi.v1.CompressionR\vcompression\x12\x16\n" +
	"\x06linger\x18\x05 \x01(\tR\x06linger\x12\x1d\n" +
	"\n" +
	"batch_size\x18\x06 \x01(\x05R\tbatchSize\x12)\n" +
	"\x10delivery_timeout\x18\a \x01(\tR\x0fdeliveryTimeout\x12 \n" +
	"\vpartitioner\x18\b \x01(\tR\vpartitioner\"\xce\x03\n" +
	"\aConsume\x12J\n" +
	"\x11auto_offset_reset\x18\x01 \x01(\x0e2\x1e.kafka.asyncapi.v1.OffsetResetR\x0fautoOffsetReset\x12%\n" +
	"\x0eread_committed\x18\x02 \x01(\bR\rreadCommitted\x12\x1f\n" +
	"\vauto_commit\x18\x03 \x01(\bR\n" +
	"autoCommit\x12(\n" +
	"\x10max_poll_records\x18\x04 \x01(\x05R\x0emaxPollRecords\x12'\n" +
	"\x0fsession_timeout\x18\x05 \x01(\tR\x0esessionTimeout\x12*\n" +
	"\x11max_poll_interval\x18\x06 \x01(\tR\x0fmaxPollInterval\x12V\n" +
	"\x13assignment_strategy\x18\a \x01(\x0e2%.kafka.asyncapi.v1.AssignmentStrategyR\x12assignmentStrategy\x12*\n" +
	"\x11group_instance_id\x18\b \x01(\tR\x0fgroupInstanceId\x12,\n" +
	"\x12next_gen_rebalance\x18\t \x01(\bR\x10nextGenRebalance\"\x8f\x02\n" +
	"\aMessage\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x12(\n" +
	"\x03key\x18\x02 \x01(\v2\x16.kafka.asyncapi.v1.KeyR\x03key\x12Q\n" +
	"\x12schema_id_location\x18\x03 \x01(\x0e2#.kafka.asyncapi.v1.SchemaIdLocationR\x10schemaIdLocation\x12;\n" +
	"\x1aschema_id_payload_encoding\x18\x04 \x01(\tR\x17schemaIdPayloadEncoding\x124\n" +
	"\x16schema_lookup_strategy\x18\x05 \x01(\tR\x14schemaLookupStrategy\"|\n" +
	"\x03Key\x12\x16\n" +
	"\x05field\x18\x01 \x01(\tH\x00R\x05field\x12\x1a\n" +
	"\amessage\x18\x02 \x01(\tH\x00R\amessage\x12\x18\n" +
	"\x06schema\x18\x03 \x01(\tH\x00R\x06schema\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescriptionB\x05\n" +
	"\x03key*\xba\x01\n" +
	"\tMechanism\x12\x19\n" +
	"\x15MECHANISM_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fMECHANISM_PLAIN\x10\x01\x12\x1b\n" +
	"\x17MECHANISM_SCRAM_SHA_256\x10\x02\x12\x1b\n" +
	"\x17MECHANISM_SCRAM_SHA_512\x10\x03\x12\x14\n" +
	"\x10MECHANISM_GSSAPI\x10\x04\x12\x19\n" +
	"\x15MECHANISM_OAUTHBEARER\x10\x05\x12\x12\n" +
	"\x0eMECHANISM_MTLS\x10\x06*f\n" +
	"\rCleanupPolicy\x12\x1e\n" +
	"\x1aCLEANUP_POLICY_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15CLEANUP_POLICY_DELETE\x10\x01\x12\x1a\n" +
	"\x16CLEANUP_POLICY_COMPACT\x10\x02*\xb3\x01\n" +
	"\vCompression\x12\x1b\n" +
	"\x17COMPRESSION_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10COMPRESSION_NONE\x10\x01\x12\x14\n" +
	"\x10COMPRESSION_GZIP\x10\x02\x12\x16\n" +
	"\x12COMPRESSION_SNAPPY\x10\x03\x12\x13\n" +
	"\x0fCOMPRESSION_LZ4\x10\x04\x12\x14\n" +
	"\x10COMPRESSION_ZSTD\x10\x05\x12\x18\n" +
	"\x14COMPRESSION_PRODUCER\x10\x06*~\n" +
	"\aPattern\x12\x17\n" +
	"\x13PATTERN_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15PATTERN_REQUEST_REPLY\x10\x01\x12\x13\n" +
	"\x0fPATTERN_PUBLISH\x10\x02\x12\x15\n" +
	"\x11PATTERN_SUBSCRIBE\x10\x03\x12\x13\n" +
	"\x0fPATTERN_PROCESS\x10\x04*J\n" +
	"\x04Acks\x12\x14\n" +
	"\x10ACKS_UNSPECIFIED\x10\x00\x12\r\n" +
	"\tACKS_NONE\x10\x01\x12\x0f\n" +
	"\vACKS_LEADER\x10\x02\x12\f\n" +
	"\bACKS_ALL\x10\x03*v\n" +
	"\vOffsetReset\x12\x1c\n" +
	"\x18OFFSET_RESET_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15OFFSET_RESET_EARLIEST\x10\x01\x12\x17\n" +
	"\x13OFFSET_RESET_LATEST\x10\x02\x12\x15\n" +
	"\x11OFFSET_RESET_NONE\x10\x03*\xc9\x01\n" +
	"\x12AssignmentStrategy\x12#\n" +
	"\x1fASSIGNMENT_STRATEGY_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19ASSIGNMENT_STRATEGY_RANGE\x10\x01\x12#\n" +
	"\x1fASSIGNMENT_STRATEGY_ROUND_ROBIN\x10\x02\x12\x1e\n" +
	"\x1aASSIGNMENT_STRATEGY_STICKY\x10\x03\x12*\n" +
	"&ASSIGNMENT_STRATEGY_COOPERATIVE_STICKY\x10\x04*u\n" +
	"\x10SchemaIdLocation\x12\"\n" +
	"\x1eSCHEMA_ID_LOCATION_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aSCHEMA_ID_LOCATION_PAYLOAD\x10\x01\x12\x1d\n" +
	"\x19SCHEMA_ID_LOCATION_HEADER\x10\x02:W\n" +
	"\bdocument\x12\x1c.google.protobuf.FileOptions\x18\xf8\xc7\x03 \x01(\v2\x1b.kafka.asyncapi.v1.DocumentR\bdocument:W\n" +
	"\aservice\x12\x1f.google.protobuf.ServiceOptions\x18\xf8\xc7\x03 \x01(\v2\x1a.kafka.asyncapi.v1.ServiceR\aservice:\\\n" +
	"\toperation\x12\x1e.google.protobuf.MethodOptions\x18\xf8\xc7\x03 \x01(\v2\x1c.kafka.asyncapi.v1.OperationR\toperation:W\n" +
	"\amessage\x12\x1f.google.protobuf.MessageOptions\x18\xf8\xc7\x03 \x01(\v2\x1a.kafka.asyncapi.v1.MessageR\amessageBGZEgithub.com/AustinZhu/protoc-gen-asyncapi/pb/kafka/asyncapi/v1;kafkav1b\x06proto3"

var (
	file_kafka_asyncapi_v1_annotations_proto_rawDescOnce sync.Once
	file_kafka_asyncapi_v1_annotations_proto_rawDescData []byte
)

func file_kafka_asyncapi_v1_annotations_proto_rawDescGZIP() []byte {
	file_kafka_asyncapi_v1_annotations_proto_rawDescOnce.Do(func() {
		file_kafka_asyncapi_v1_annotations_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kafka_asyncapi_v1_annotations_proto_rawDesc), len(file_kafka_asyncapi_v1_annotations_proto_rawDesc)))
	})
	return file_kafka_asyncapi_v1_annotations_proto_rawDescData
}

var file_kafka_asyncapi_v1_annotations_proto_enumTypes = make([]protoimpl.EnumInfo, 8)
var file_kafka_asyncapi_v1_annotations_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_kafka_asyncapi_v1_annotations_proto_goTypes = []any{
	(Mechanism)(0),                      // 0: kafka.asyncapi.v1.Mechanism
	(CleanupPolicy)(0),                  // 1: kafka.asyncapi.v1.CleanupPolicy
	(Compression)(0),                    // 2: kafka.asyncapi.v1.Compression
	(Pattern)(0),                        // 3: kafka.asyncapi.v1.Pattern
	(Acks)(0),                           // 4: kafka.asyncapi.v1.Acks
	(OffsetReset)(0),                    // 5: kafka.asyncapi.v1.OffsetReset
	(AssignmentStrategy)(0),             // 6: kafka.asyncapi.v1.AssignmentStrategy
	(SchemaIdLocation)(0),               // 7: kafka.asyncapi.v1.SchemaIdLocation
	(*Document)(nil),                    // 8: kafka.asyncapi.v1.Document
	(*Server)(nil),                      // 9: kafka.asyncapi.v1.Server
	(*Auth)(nil),                        // 10: kafka.asyncapi.v1.Auth
	(*Topic)(nil),                       // 11: kafka.asyncapi.v1.Topic
	(*Service)(nil),                     // 12: kafka.asyncapi.v1.Service
	(*Operation)(nil),                   // 13: kafka.asyncapi.v1.Operation
	(*Produce)(nil),                     // 14: kafka.asyncapi.v1.Produce
	(*Consume)(nil),                     // 15: kafka.asyncapi.v1.Consume
	(*Message)(nil),                     // 16: kafka.asyncapi.v1.Message
	(*Key)(nil),                         // 17: kafka.asyncapi.v1.Key
	nil,                                 // 18: kafka.asyncapi.v1.Topic.ConfigsEntry
	(*descriptorpb.FileOptions)(nil),    // 19: google.protobuf.FileOptions
	(*descriptorpb.ServiceOptions)(nil), // 20: google.protobuf.ServiceOptions
	(*descriptorpb.MethodOptions)(nil),  // 21: google.protobuf.MethodOptions
	(*descriptorpb.MessageOptions)(nil), // 22: google.protobuf.MessageOptions
}
var file_kafka_asyncapi_v1_annotations_proto_depIdxs = []int32{
	9,  // 0: kafka.asyncapi.v1.Document.servers:type_name -> kafka.asyncapi.v1.Server
	10, // 1: kafka.asyncapi.v1.Document.auth:type_name -> kafka.asyncapi.v1.Auth
	11, // 2: kafka.asyncapi.v1.Document.topics:type_name -> kafka.asyncapi.v1.Topic
	0,  // 3: kafka.asyncapi.v1.Auth.mechanism:type_name -> kafka.asyncapi.v1.Mechanism
	1,  // 4: kafka.asyncapi.v1.Topic.cleanup_policy:type_name -> kafka.asyncapi.v1.CleanupPolicy
	2,  // 5: kafka.asyncapi.v1.Topic.compression:type_name -> kafka.asyncapi.v1.Compression
	18, // 6: kafka.asyncapi.v1.Topic.configs:type_name -> kafka.asyncapi.v1.Topic.ConfigsEntry
	3,  // 7: kafka.asyncapi.v1.Operation.pattern:type_name -> kafka.asyncapi.v1.Pattern
	14, // 8: kafka.asyncapi.v1.Operation.produce:type_name -> kafka.asyncapi.v1.Produce
	15, // 9: kafka.asyncapi.v1.Operation.consume:type_name -> kafka.asyncapi.v1.Consume
	4,  // 10: kafka.asyncapi.v1.Produce.acks:type_name -> kafka.asyncapi.v1.Acks
	2,  // 11: kafka.asyncapi.v1.Produce.compression:type_name -> kafka.asyncapi.v1.Compression
	5,  // 12: kafka.asyncapi.v1.Consume.auto_offset_reset:type_name -> kafka.asyncapi.v1.OffsetReset
	6,  // 13: kafka.asyncapi.v1.Consume.assignment_strategy:type_name -> kafka.asyncapi.v1.AssignmentStrategy
	17, // 14: kafka.asyncapi.v1.Message.key:type_name -> kafka.asyncapi.v1.Key
	7,  // 15: kafka.asyncapi.v1.Message.schema_id_location:type_name -> kafka.asyncapi.v1.SchemaIdLocation
	19, // 16: kafka.asyncapi.v1.document:extendee -> google.protobuf.FileOptions
	20, // 17: kafka.asyncapi.v1.service:extendee -> google.protobuf.ServiceOptions
	21, // 18: kafka.asyncapi.v1.operation:extendee -> google.protobuf.MethodOptions
	22, // 19: kafka.asyncapi.v1.message:extendee -> google.protobuf.MessageOptions
	8,  // 20: kafka.asyncapi.v1.document:type_name -> kafka.asyncapi.v1.Document
	12, // 21: kafka.asyncapi.v1.service:type_name -> kafka.asyncapi.v1.Service
	13, // 22: kafka.asyncapi.v1.operation:type_name -> kafka.asyncapi.v1.Operation
	16, // 23: kafka.asyncapi.v1.message:type_name -> kafka.asyncapi.v1.Message
	24, // [24:24] is the sub-list for method output_type
	24, // [24:24] is the sub-list for method input_type
	20, // [20:24] is the sub-list for extension type_name
	16, // [16:20] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_kafka_asyncapi_v1_annotations_proto_init() }
func file_kafka_asyncapi_v1_annotations_proto_init() {
	if File_kafka_asyncapi_v1_annotations_proto != nil {
		return
	}
	file_kafka_asyncapi_v1_annotations_proto_msgTypes[9].OneofWrappers = []any{
		(*Key_Field)(nil),
		(*Key_Message)(nil),
		(*Key_Schema)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kafka_asyncapi_v1_annotations_proto_rawDesc), len(file_kafka_asyncapi_v1_annotations_proto_rawDesc)),
			NumEnums:      8,
			NumMessages:   11,
			NumExtensions: 4,
			NumServices:   0,
		},
		GoTypes:           file_kafka_asyncapi_v1_annotations_proto_goTypes,
		DependencyIndexes: file_kafka_asyncapi_v1_annotations_proto_depIdxs,
		EnumInfos:         file_kafka_asyncapi_v1_annotations_proto_enumTypes,
		MessageInfos:      file_kafka_asyncapi_v1_annotations_proto_msgTypes,
		ExtensionInfos:    file_kafka_asyncapi_v1_annotations_proto_extTypes,
	}.Build()
	File_kafka_asyncapi_v1_annotations_proto = out.File
	file_kafka_asyncapi_v1_annotations_proto_goTypes = nil
	file_kafka_asyncapi_v1_annotations_proto_depIdxs = nil
}
