// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: temporal/asyncapi/v1/options.proto

package asyncapiv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Service struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Default task queue for the service's Workflows and Activities.
	TaskQueue     string `protobuf:"bytes,1,opt,name=task_queue,json=taskQueue,proto3" json:"task_queue,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Service) Reset() {
	*x = Service{}
	mi := &file_temporal_asyncapi_v1_options_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Service) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Service) ProtoMessage() {}

func (x *Service) ProtoReflect() protoreflect.Message {
	mi := &file_temporal_asyncapi_v1_options_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Service.ProtoReflect.Descriptor instead.
func (*Service) Descriptor() ([]byte, []int) {
	return file_temporal_asyncapi_v1_options_proto_rawDescGZIP(), []int{0}
}

func (x *Service) GetTaskQueue() string {
	if x != nil {
		return x.TaskQueue
	}
	return ""
}

type Operation struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Exactly one kind must be set.
	//
	// Types that are valid to be assigned to Kind:
	//
	//	*Operation_Workflow
	//	*Operation_Activity
	//	*Operation_Signal
	//	*Operation_Query
	//	*Operation_Update
	Kind          isOperation_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Operation) Reset() {
	*x = Operation{}
	mi := &file_temporal_asyncapi_v1_options_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Operation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Operation) ProtoMessage() {}

func (x *Operation) ProtoReflect() protoreflect.Message {
	mi := &file_temporal_asyncapi_v1_options_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Operation.ProtoReflect.Descriptor instead.
func (*Operation) Descriptor() ([]byte, []int) {
	return file_temporal_asyncapi_v1_options_proto_rawDescGZIP(), []int{1}
}

func (x *Operation) GetKind() isOperation_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *Operation) GetWorkflow() *Workflow {
	if x != nil {
		if x, ok := x.Kind.(*Operation_Workflow); ok {
			return x.Workflow
		}
	}
	return nil
}

func (x *Operation) GetActivity() *Activity {
	if x != nil {
		if x, ok := x.Kind.(*Operation_Activity); ok {
			return x.Activity
		}
	}
	return nil
}

func (x *Operation) GetSignal() *Signal {
	if x != nil {
		if x, ok := x.Kind.(*Operation_Signal); ok {
			return x.Signal
		}
	}
	return nil
}

func (x *Operation) GetQuery() *Query {
	if x != nil {
		if x, ok := x.Kind.(*Operation_Query); ok {
			return x.Query
		}
	}
	return nil
}

func (x *Operation) GetUpdate() *Update {
	if x != nil {
		if x, ok := x.Kind.(*Operation_Update); ok {
			return x.Update
		}
	}
	return nil
}

type isOperation_Kind interface {
	isOperation_Kind()
}

type Operation_Workflow struct {
	Workflow *Workflow `protobuf:"bytes,1,opt,name=workflow,proto3,oneof"`
}

type Operation_Activity struct {
	Activity *Activity `protobuf:"bytes,2,opt,name=activity,proto3,oneof"`
}

type Operation_Signal struct {
	Signal *Signal `protobuf:"bytes,3,opt,name=signal,proto3,oneof"`
}

type Operation_Query struct {
	Query *Query `protobuf:"bytes,4,opt,name=query,proto3,oneof"`
}

type Operation_Update struct {
	Update *Update `protobuf:"bytes,5,opt,name=update,proto3,oneof"`
}

func (*Operation_Workflow) isOperation_Kind() {}

func (*Operation_Activity) isOperation_Kind() {}

func (*Operation_Signal) isOperation_Kind() {}

func (*Operation_Query) isOperation_Kind() {}

func (*Operation_Update) isOperation_Kind() {}

// A Workflow type. Its result is the rpc's response.
type Workflow struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Workflow type name registered with the Worker. Defaults to the rpc name.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Overrides the service's task queue.
	TaskQueue string `protobuf:"bytes,2,opt,name=task_queue,json=taskQueue,proto3" json:"task_queue,omitempty"`
	// Whether the Workflow may continue-as-new into itself with this input.
	ContinueAsNew bool `protobuf:"varint,3,opt,name=continue_as_new,json=continueAsNew,proto3" json:"continue_as_new,omitempty"`
	// Timeouts are Go-style durations such as "30s" or "1h30m".
	// Total time for the Workflow Execution, including retries and continue-as-new.
	ExecutionTimeout string `protobuf:"bytes,4,opt,name=execution_timeout,json=executionTimeout,proto3" json:"execution_timeout,omitempty"`
	// Time for a single Workflow Run.
	RunTimeout string `protobuf:"bytes,5,opt,name=run_timeout,json=runTimeout,proto3" json:"run_timeout,omitempty"`
	// Time for a single Workflow Task.
	TaskTimeout   string       `protobuf:"bytes,6,opt,name=task_timeout,json=taskTimeout,proto3" json:"task_timeout,omitempty"`
	RetryPolicy   *RetryPolicy `protobuf:"bytes,7,opt,name=retry_policy,json=retryPolicy,proto3" json:"retry_policy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Workflow) Reset() {
	*x = Workflow{}
	mi := &file_temporal_asyncapi_v1_options_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Workflow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Workflow) ProtoMessage() {}

func (x *Workflow) ProtoReflect() protoreflect.Message {
	mi := &file_temporal_asyncapi_v1_options_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Workflow.ProtoReflect.Descriptor instead.
func (*Workflow) Descriptor() ([]byte, []int) {
	return file_temporal_asyncapi_v1_options_proto_rawDescGZIP(), []int{2}
}

func (x *Workflow) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Workflow) GetTaskQueue() string {
	if x != nil {
		return x.TaskQueue
	}
	return ""
}

func (x *Workflow) GetContinueAsNew() bool {
	if x != nil {
		return x.ContinueAsNew
	}
	return false
}

func (x *Workflow) GetExecutionTimeout() string {
	if x != nil {
		return x.ExecutionTimeout
	}
	return ""
}

func (x *Workflow) GetRunTimeout() string {
	if x != nil {
		return x.RunTimeout
	}
	return ""
}

func (x *Workflow) GetTaskTimeout() string {
	if x != nil {
		return x.TaskTimeout
	}
	return ""
}

func (x *Workflow) GetRetryPolicy() *RetryPolicy {
	if x != nil {
		return x.RetryPolicy
	}
	return nil
}

// An Activity type. Its result is the rpc's response.
type Activity struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Activity type name registered with the Worker. Defaults to the rpc name.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Overrides the service's task queue.
	TaskQueue string `protobuf:"bytes,2,opt,name=task_queue,json=taskQueue,proto3" json:"task_queue,omitempty"`
	// Timeouts are Go-style durations such as "30s" or "1h30m".
	// Total time for the Activity Execution, including retries.
	ScheduleToCloseTimeout string `protobuf:"bytes,3,opt,name=schedule_to_close_timeout,json=scheduleToCloseTimeout,proto3" json:"schedule_to_close_timeout,omitempty"`
	// Time for a single Activity Task Execution.
	StartToCloseTimeout string `protobuf:"bytes,4,opt,name=start_to_close_timeout,json=startToCloseTimeout,proto3" json:"start_to_close_timeout,omitempty"`
	// Time an Activity Task may wait in the task queue.
	ScheduleToStartTimeout string `protobuf:"bytes,5,opt,name=schedule_to_start_timeout,json=scheduleToStartTimeout,proto3" json:"schedule_to_start_timeout,omitempty"`
	// Maximum time between heartbeats.
	HeartbeatTimeout string       `protobuf:"bytes,6,opt,name=heartbeat_timeout,json=heartbeatTimeout,proto3" json:"heartbeat_timeout,omitempty"`
	RetryPolicy      *RetryPolicy `protobuf:"bytes,7,opt,name=retry_policy,json=retryPolicy,proto3" json:"retry_policy,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Activity) Reset() {
	*x = Activity{}
	mi := &file_temporal_asyncapi_v1_options_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Activity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Activity) ProtoMessage() {}

func (x *Activity) ProtoReflect() protoreflect.Message {
	mi := &file_temporal_asyncapi_v1_options_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Activity.ProtoReflect.Descriptor instead.
func (*Activity) Descriptor() ([]byte, []int) {
	return file_temporal_asyncapi_v1_options_proto_rawDescGZIP(), []int{3}
}

func (x *Activity) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Activity) GetTaskQueue() string {
	if x != nil {
		return x.TaskQueue
	}
	return ""
}

func (x *Activity) GetScheduleToCloseTimeout() string {
	if x != nil {
		return x.ScheduleToCloseTimeout
	}
	return ""
}

func (x *Activity) GetStartToCloseTimeout() string {
	if x != nil {
		return x.StartToCloseTimeout
	}
	return ""
}

func (x *Activity) GetScheduleToStartTimeout() string {
	if x != nil {
		return x.ScheduleToStartTimeout
	}
	return ""
}

func (x *Activity) GetHeartbeatTimeout() string {
	if x != nil {
		return x.HeartbeatTimeout
	}
	return ""
}

func (x *Activity) GetRetryPolicy() *RetryPolicy {
	if x != nil {
		return x.RetryPolicy
	}
	return nil
}

// A Signal handler. The rpc must return google.protobuf.Empty.
type Signal struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Signal name. Defaults to the rpc name.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// rpc names of the Workflows in this service that handle it. Defaults to the
	// service's only Workflow, if it has exactly one.
	Workflows     []string `protobuf:"bytes,2,rep,name=workflows,proto3" json:"workflows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Signal) Reset() {
	*x = Signal{}
	mi := &file_temporal_asyncapi_v1_options_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Signal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Signal) ProtoMessage() {}

func (x *Signal) ProtoReflect() protoreflect.Message {
	mi := &file_temporal_asyncapi_v1_options_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Signal.ProtoReflect.Descriptor instead.
func (*Signal) Descriptor() ([]byte, []int) {
	return file_temporal_asyncapi_v1_options_proto_rawDescGZIP(), []int{4}
}

func (x *Signal) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Signal) GetWorkflows() []string {
	if x != nil {
		return x.Workflows
	}
	return nil
}

// A Query handler. Its result is the rpc's response, which must not be
// google.protobuf.Empty.
type Query struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Query name. Defaults to the rpc name.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// rpc names of the Workflows in this service that handle it. Defaults to the
	// service's only Workflow, if it has exactly one.
	Workflows     []string `protobuf:"bytes,2,rep,name=workflows,proto3" json:"workflows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Query) Reset() {
	*x = Query{}
	mi := &file_temporal_asyncapi_v1_options_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Query) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Query) ProtoMessage() {}

func (x *Query) ProtoReflect() protoreflect.Message {
	mi := &file_temporal_asyncapi_v1_options_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Query.ProtoReflect.Descriptor instead.
func (*Query) Descriptor() ([]byte, []int) {
	return file_temporal_asyncapi_v1_options_proto_rawDescGZIP(), []int{5}
}

func (x *Query) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Query) GetWorkflows() []string {
	if x != nil {
		return x.Workflows
	}
	return nil
}

// An Update handler. Its result is the rpc's response.
type Update struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Update name. Defaults to the rpc name.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// rpc names of the Workflows in this service that handle it. Defaults to the
	// service's only Workflow, if it has exactly one.
	Workflows     []string `protobuf:"bytes,2,rep,name=workflows,proto3" json:"workflows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Update) Reset() {
	*x = Update{}
	mi := &file_temporal_asyncapi_v1_options_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Update) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Update) ProtoMessage() {}

func (x *Update) ProtoReflect() protoreflect.Message {
	mi := &file_temporal_asyncapi_v1_options_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Update.ProtoReflect.Descriptor instead.
func (*Update) Descriptor() ([]byte, []int) {
	return file_temporal_asyncapi_v1_options_proto_rawDescGZIP(), []int{6}
}

func (x *Update) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Update) GetWorkflows() []string {
	if x != nil {
		return x.Workflows
	}
	return nil
}

// Mirrors temporal.api.common.v1.RetryPolicy; intervals are Go-style durations.
type RetryPolicy struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	InitialInterval    string                 `protobuf:"bytes,1,opt,name=initial_interval,json=initialInterval,proto3" json:"initial_interval,omitempty"`
	BackoffCoefficient float64                `protobuf:"fixed64,2,opt,name=backoff_coefficient,json=backoffCoefficient,proto3" json:"backoff_coefficient,omitempty"`
	MaximumInterval    string                 `protobuf:"bytes,3,opt,name=maximum_interval,json=maximumInterval,proto3" json:"maximum_interval,omitempty"`
	// 0 means unlimited.
	MaximumAttempts        int32    `protobuf:"varint,4,opt,name=maximum_attempts,json=maximumAttempts,proto3" json:"maximum_attempts,omitempty"`
	NonRetryableErrorTypes []string `protobuf:"bytes,5,rep,name=non_retryable_error_types,json=nonRetryableErrorTypes,proto3" json:"non_retryable_error_types,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *RetryPolicy) Reset() {
	*x = RetryPolicy{}
	mi := &file_temporal_asyncapi_v1_options_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetryPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetryPolicy) ProtoMessage() {}

func (x *RetryPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_temporal_asyncapi_v1_options_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetryPolicy.ProtoReflect.Descriptor instead.
func (*RetryPolicy) Descriptor() ([]byte, []int) {
	return file_temporal_asyncapi_v1_options_proto_rawDescGZIP(), []int{7}
}

func (x *RetryPolicy) GetInitialInterval() string {
	if x != nil {
		return x.InitialInterval
	}
	return ""
}

func (x *RetryPolicy) GetBackoffCoefficient() float64 {
	if x != nil {
		return x.BackoffCoefficient
	}
	return 0
}

func (x *RetryPolicy) GetMaximumInterval() string {
	if x != nil {
		return x.MaximumInterval
	}
	return ""
}

func (x *RetryPolicy) GetMaximumAttempts() int32 {
	if x != nil {
		return x.MaximumAttempts
	}
	return 0
}

func (x *RetryPolicy) GetNonRetryableErrorTypes() []string {
	if x != nil {
		return x.NonRetryableErrorTypes
	}
	return nil
}

var file_temporal_asyncapi_v1_options_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.ServiceOptions)(nil),
		ExtensionType: (*Service)(nil),
		Field:         58320,
		Name:          "temporal.asyncapi.v1.service",
		Tag:           "bytes,58320,opt,name=service",
		Filename:      "temporal/asyncapi/v1/options.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*Operation)(nil),
		Field:         58320,
		Name:          "temporal.asyncapi.v1.operation",
		Tag:           "bytes,58320,opt,name=operation",
		Filename:      "temporal/asyncapi/v1/options.proto",
	},
}

// Extension fields to descriptorpb.ServiceOptions.
var (
	// optional temporal.asyncapi.v1.Service service = 58320;
	E_Service = &file_temporal_asyncapi_v1_options_proto_extTypes[0]
)

// Extension fields to descriptorpb.MethodOptions.
var (
	// optional temporal.asyncapi.v1.Operation operation = 58320;
	E_Operation = &file_temporal_asyncapi_v1_options_proto_extTypes[1]
)

var File_temporal_asyncapi_v1_options_proto protoreflect.FileDescriptor

const file_temporal_asyncapi_v1_options_proto_rawDesc = "" +
	"\n" +
	"\"temporal/asyncapi/v1/options.proto\x12\x14temporal.asyncapi.v1\x1a google/protobuf/descriptor.proto\"(\n" +
	"\aService\x12\x1d\n" +
	"\n" +
	"task_queue\x18\x01 \x01(\tR\ttaskQueue\"\xb4\x02\n" +
	"\tOperation\x12<\n" +
	"\bworkflow\x18\x01 \x01(\v2\x1e.temporal.asyncapi.v1.WorkflowH\x00R\bworkflow\x12<\n" +
	"\bactivity\x18\x02 \x01(\v2\x1e.temporal.asyncapi.v1.ActivityH\x00R\bactivity\x126\n" +
	"\x06signal\x18\x03 \x01(\v2\x1c.temporal.asyncapi.v1.SignalH\x00R\x06signal\x123\n" +
	"\x05query\x18\x04 \x01(\v2\x1b.temporal.asyncapi.v1.QueryH\x00R\x05query\x126\n" +
	"\x06update\x18\x05 \x01(\v2\x1c.temporal.asyncapi.v1.UpdateH\x00R\x06updateB\x06\n" +
	"\x04kind\"\x9c\x02\n" +
	"\bWorkflow\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"task_queue\x18\x02 \x01(\tR\ttaskQueue\x12&\n" +
	"\x0fcontinue_as_new\x18\x03 \x01(\bR\rcontinueAsNew\x12+\n" +
	"\x11execution_timeout\x18\x04 \x01(\tR\x10executionTimeout\x12\x1f\n" +
	"\vrun_timeout\x18\x05 \x01(\tR\n" +
	"runTimeout\x12!\n" +
	"\ftask_timeout\x18\x06 \x01(\tR\vtaskTimeout\x12D\n" +
	"\fretry_policy\x18\a \x01(\v2!.temporal.asyncapi.v1.RetryPolicyR\vretryPolicy\"\xdb\x02\n" +
	"\bActivity\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"task_queue\x18\x02 \x01(\tR\ttaskQueue\x129\n" +
	"\x19schedule_to_close_timeout\x18\x03 \x01(\tR\x16scheduleToCloseTimeout\x123\n" +
	"\x16start_to_close_timeout\x18\x04 \x01(\tR\x13startToCloseTimeout\x129\n" +
	"\x19schedule_to_start_timeout\x18\x05 \x01(\tR\x16scheduleToStartTimeout\x12+\n" +
	"\x11heartbeat_timeout\x18\x06 \x01(\tR\x10heartbeatTimeout\x12D\n" +
	"\fretry_policy\x18\a \x01(\v2!.temporal.asyncapi.v1.RetryPolicyR\vretryPolicy\":\n" +
	"\x06Signal\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1c\n" +
	"\tworkflows\x18\x02 \x03(\tR\tworkflows\"9\n" +
	"\x05Query\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1c\n" +
	"\tworkflows\x18\x02 \x03(\tR\tworkflows\":\n" +
	"\x06Update\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1c\n" +
	"\tworkflows\x18\x02 \x03(\tR\tworkflows\"\xfa\x01\n" +
	"\vRetryPolicy\x12)\n" +
	"\x10initial_interval\x18\x01 \x01(\tR\x0finitialInterval\x12/\n" +
	"\x13backoff_coefficient\x18\x02 \x01(\x01R\x12backoffCoefficient\x12)\n" +
	"\x10maximum_interval\x18\x03 \x01(\tR\x0fmaximumInterval\x12)\n" +
	"\x10maximum_attempts\x18\x04 \x01(\x05R\x0fmaximumAttempts\x129\n" +
	"\x19non_retryable_error_types\x18\x05 \x03(\tR\x16nonRetryableErrorTypes:Z\n" +
	"\aservice\x12\x1f.google.protobuf.ServiceOptions\x18\xd0\xc7\x03 \x01(\v2\x1d.temporal.asyncapi.v1.ServiceR\aservice:_\n" +
	"\toperation\x12\x1e.google.protobuf.MethodOptions\x18\xd0\xc7\x03 \x01(\v2\x1f.temporal.asyncapi.v1.OperationR\toperationBYZWgithub.com/AustinZhu/protoc-gen-temporal-asyncapi/proto/temporal/asyncapi/v1;asyncapiv1b\x06proto3"

var (
	file_temporal_asyncapi_v1_options_proto_rawDescOnce sync.Once
	file_temporal_asyncapi_v1_options_proto_rawDescData []byte
)

func file_temporal_asyncapi_v1_options_proto_rawDescGZIP() []byte {
	file_temporal_asyncapi_v1_options_proto_rawDescOnce.Do(func() {
		file_temporal_asyncapi_v1_options_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_temporal_asyncapi_v1_options_proto_rawDesc), len(file_temporal_asyncapi_v1_options_proto_rawDesc)))
	})
	return file_temporal_asyncapi_v1_options_proto_rawDescData
}

var file_temporal_asyncapi_v1_options_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_temporal_asyncapi_v1_options_proto_goTypes = []any{
	(*Service)(nil),                     // 0: temporal.asyncapi.v1.Service
	(*Operation)(nil),                   // 1: temporal.asyncapi.v1.Operation
	(*Workflow)(nil),                    // 2: temporal.asyncapi.v1.Workflow
	(*Activity)(nil),                    // 3: temporal.asyncapi.v1.Activity
	(*Signal)(nil),                      // 4: temporal.asyncapi.v1.Signal
	(*Query)(nil),                       // 5: temporal.asyncapi.v1.Query
	(*Update)(nil),                      // 6: temporal.asyncapi.v1.Update
	(*RetryPolicy)(nil),                 // 7: temporal.asyncapi.v1.RetryPolicy
	(*descriptorpb.ServiceOptions)(nil), // 8: google.protobuf.ServiceOptions
	(*descriptorpb.MethodOptions)(nil),  // 9: google.protobuf.MethodOptions
}
var file_temporal_asyncapi_v1_options_proto_depIdxs = []int32{
	2,  // 0: temporal.asyncapi.v1.Operation.workflow:type_name -> temporal.asyncapi.v1.Workflow
	3,  // 1: temporal.asyncapi.v1.Operation.activity:type_name -> temporal.asyncapi.v1.Activity
	4,  // 2: temporal.asyncapi.v1.Operation.signal:type_name -> temporal.asyncapi.v1.Signal
	5,  // 3: temporal.asyncapi.v1.Operation.query:type_name -> temporal.asyncapi.v1.Query
	6,  // 4: temporal.asyncapi.v1.Operation.update:type_name -> temporal.asyncapi.v1.Update
	7,  // 5: temporal.asyncapi.v1.Workflow.retry_policy:type_name -> temporal.asyncapi.v1.RetryPolicy
	7,  // 6: temporal.asyncapi.v1.Activity.retry_policy:type_name -> temporal.asyncapi.v1.RetryPolicy
	8,  // 7: temporal.asyncapi.v1.service:extendee -> google.protobuf.ServiceOptions
	9,  // 8: temporal.asyncapi.v1.operation:extendee -> google.protobuf.MethodOptions
	0,  // 9: temporal.asyncapi.v1.service:type_name -> temporal.asyncapi.v1.Service
	1,  // 10: temporal.asyncapi.v1.operation:type_name -> temporal.asyncapi.v1.Operation
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	9,  // [9:11] is the sub-list for extension type_name
	7,  // [7:9] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_temporal_asyncapi_v1_options_proto_init() }
func file_temporal_asyncapi_v1_options_proto_init() {
	if File_temporal_asyncapi_v1_options_proto != nil {
		return
	}
	file_temporal_asyncapi_v1_options_proto_msgTypes[1].OneofWrappers = []any{
		(*Operation_Workflow)(nil),
		(*Operation_Activity)(nil),
		(*Operation_Signal)(nil),
		(*Operation_Query)(nil),
		(*Operation_Update)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_temporal_asyncapi_v1_options_proto_rawDesc), len(file_temporal_asyncapi_v1_options_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 2,
			NumServices:   0,
		},
		GoTypes:           file_temporal_asyncapi_v1_options_proto_goTypes,
		DependencyIndexes: file_temporal_asyncapi_v1_options_proto_depIdxs,
		MessageInfos:      file_temporal_asyncapi_v1_options_proto_msgTypes,
		ExtensionInfos:    file_temporal_asyncapi_v1_options_proto_extTypes,
	}.Build()
	File_temporal_asyncapi_v1_options_proto = out.File
	file_temporal_asyncapi_v1_options_proto_goTypes = nil
	file_temporal_asyncapi_v1_options_proto_depIdxs = nil
}
