// NATS annotations for protoc-gen-asyncapi (protoc-gen-nats-asyncapi).
//
// These annotations carry only NATS concepts: subjects, queue groups, NATS
// micro, JetStream streams, consumers, key-value buckets and object stores,
// and NATS specifics of servers and authentication. Everything generic
// (info, servers, security schemes, tags, summaries, examples, headers, ...)
// uses the asyncapi.v3 annotations (asyncapi/v3/annotations.proto).
//
// Every annotation is optional. A service only needs enough annotations to
// say "this is a NATS API"; everything else is inferred from the Protobuf
// schema and its comments:
//
//   - request/reply vs. publish vs. subscribe is inferred from the RPC shape,
//   - subject parameters are bound to payload fields with the same name,
//   - JetStream streams are matched to subjects automatically.
//
// Durations are strings in Go syntax with an additional "d" (day) unit, e.g.
// "30s", "5m", "1h30m", "7d". Sizes are strings with an optional unit,
// e.g. "512", "64KiB", "10MB", "1GiB".

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: nats/asyncapi/v1/annotations.proto

package natsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AuthType lists the authentication mechanisms supported by NATS.
type AuthType int32

const (
	AuthType_AUTH_TYPE_UNSPECIFIED AuthType = 0
	// Username and password (AsyncAPI "userPassword").
	AuthType_AUTH_TYPE_USER_PASSWORD AuthType = 1
	// Plain token (AsyncAPI "apiKey" in the user position).
	AuthType_AUTH_TYPE_TOKEN AuthType = 2
	// NKey challenge/response (AsyncAPI "asymmetricEncryption").
	AuthType_AUTH_TYPE_NKEY AuthType = 3
	// Decentralised JWT with NKey signature, i.e. a ".creds" file
	// (AsyncAPI "asymmetricEncryption").
	AuthType_AUTH_TYPE_JWT AuthType = 4
	// Mutual TLS with client certificates (AsyncAPI "X509").
	AuthType_AUTH_TYPE_TLS AuthType = 5
	// Authorization callout: credentials are forwarded to an external
	// service (AsyncAPI "userPassword").
	AuthType_AUTH_TYPE_AUTH_CALLOUT AuthType = 6
)

// Enum value maps for AuthType.
var (
	AuthType_name = map[int32]string{
		0: "AUTH_TYPE_UNSPECIFIED",
		1: "AUTH_TYPE_USER_PASSWORD",
		2: "AUTH_TYPE_TOKEN",
		3: "AUTH_TYPE_NKEY",
		4: "AUTH_TYPE_JWT",
		5: "AUTH_TYPE_TLS",
		6: "AUTH_TYPE_AUTH_CALLOUT",
	}
	AuthType_value = map[string]int32{
		"AUTH_TYPE_UNSPECIFIED":   0,
		"AUTH_TYPE_USER_PASSWORD": 1,
		"AUTH_TYPE_TOKEN":         2,
		"AUTH_TYPE_NKEY":          3,
		"AUTH_TYPE_JWT":           4,
		"AUTH_TYPE_TLS":           5,
		"AUTH_TYPE_AUTH_CALLOUT":  6,
	}
)

func (x AuthType) Enum() *AuthType {
	p := new(AuthType)
	*p = x
	return p
}

func (x AuthType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AuthType) Descriptor() protoreflect.EnumDescriptor {
	return file_nats_asyncapi_v1_annotations_proto_enumTypes[0].Descriptor()
}

func (AuthType) Type() protoreflect.EnumType {
	return &file_nats_asyncapi_v1_annotations_proto_enumTypes[0]
}

func (x AuthType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AuthType.Descriptor instead.
func (AuthType) EnumDescriptor() ([]byte, []int) {
	return file_nats_asyncapi_v1_annotations_proto_rawDescGZIP(), []int{0}
}

// Pattern tells how a method maps onto NATS messaging.
//
// When unspecified it is inferred from the method signature:
//
//	rpc A(Req) returns (Res)                    -> REQUEST_REPLY
//	rpc B(Event) returns (google.protobuf.Empty) -> SUBSCRIBE
//	rpc C(Event) returns (stream ...)           -> PUBLISH (payload is the output)
//	rpc D(stream Event) returns (...)           -> SUBSCRIBE
type Pattern int32

const (
	Pattern_PATTERN_UNSPECIFIED Pattern = 0
	// The service receives the request and replies with the response.
	Pattern_PATTERN_REQUEST_REPLY Pattern = 1
	// The service publishes the message (the output for server streaming
	// methods, otherwise the non-Empty of input/output, preferring the input).
	Pattern_PATTERN_PUBLISH Pattern = 2
	// The service subscribes to (or consumes) the input message.
	Pattern_PATTERN_SUBSCRIBE Pattern = 3
)

// Enum value maps for Pattern.
var (
	Pattern_name = map[int32]string{
		0: "PATTERN_UNSPECIFIED",
		1: "PATTERN_REQUEST_REPLY",
		2: "PATTERN_PUBLISH",
		3: "PATTERN_SUBSCRIBE",
	}
	Pattern_value = map[string]int32{
		"PATTERN_UNSPECIFIED":   0,
		"PATTERN_REQUEST_REPLY": 1,
		"PATTERN_PUBLISH":       2,
		"PATTERN_SUBSCRIBE":     3,
	}
)

func (x Pattern) Enum() *Pattern {
	p := new(Pattern)
	*p = x
	return p
}

func (x Pattern) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Pattern) Descriptor() protoreflect.EnumDescriptor {
	return file_nats_asyncapi_v1_annotations_proto_enumTypes[1].Descriptor()
}

func (Pattern) Type() protoreflect.EnumType {
	return &file_nats_asyncapi_v1_annotations_proto_enumTypes[1]
}

func (x Pattern) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Pattern.Descriptor instead.
func (Pattern) EnumDescriptor() ([]byte, []int) {
	return file_nats_asyncapi_v1_annotations_proto_rawDescGZIP(), []int{1}
}

// Expect lists JetStream optimistic concurrency checks.
type Expect int32

const (
	Expect_EXPECT_UNSPECIFIED Expect = 0
	// Nats-Expected-Stream
	Expect_EXPECT_STREAM Expect = 1
	// Nats-Expected-Last-Sequence
	Expect_EXPECT_LAST_SEQUENCE Expect = 2
	// Nats-Expected-Last-Subject-Sequence
	Expect_EXPECT_LAST_SUBJECT_SEQUENCE Expect = 3
	// Nats-Expected-Last-Msg-Id
	Expect_EXPECT_LAST_MSG_ID Expect = 4
)

// Enum value maps for Expect.
var (
	Expect_name = map[int32]string{
		0: "EXPECT_UNSPECIFIED",
		1: "EXPECT_STREAM",
		2: "EXPECT_LAST_SEQUENCE",
		3: "EXPECT_LAST_SUBJECT_SEQUENCE",
		4: "EXPECT_LAST_MSG_ID",
	}
	Expect_value = map[string]int32{
		"EXPECT_UNSPECIFIED":           0,
		"EXPECT_STREAM":                1,
		"EXPECT_LAST_SEQUENCE":         2,
		"EXPECT_LAST_SUBJECT_SEQUENCE": 3,
		"EXPECT_LAST_MSG_ID":           4,
	}
)

func (x Expect) Enum() *Expect {
	p := new(Expect)
	*p = x
	return p
}

func (x Expect) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Expect) Descriptor() protoreflect.EnumDescriptor {
	return file_nats_asyncapi_v1_annotations_proto_enumTypes[2].Descriptor()
}

func (Expect) Type() protoreflect.EnumType {
	return &file_nats_asyncapi_v1_annotations_proto_enumTypes[2]
}

func (x Expect) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Expect.Descriptor instead.
func (Expect) EnumDescriptor() ([]byte, []int) {
	return file_nats_asyncapi_v1_annotations_proto_rawDescGZIP(), []int{2}
}

type Retention int32

const (
	Retention_RETENTION_UNSPECIFIED Retention = 0
	Retention_RETENTION_LIMITS      Retention = 1
	Retention_RETENTION_INTEREST    Retention = 2
	Retention_RETENTION_WORK_QUEUE  Retention = 3
)

// Enum value maps for Retention.
var (
	Retention_name = map[int32]string{
		0: "RETENTION_UNSPECIFIED",
		1: "RETENTION_LIMITS",
		2: "RETENTION_INTEREST",
		3: "RETENTION_WORK_QUEUE",
	}
	Retention_value = map[string]int32{
		"RETENTION_UNSPECIFIED": 0,
		"RETENTION_LIMITS":      1,
		"RETENTION_INTEREST":    2,
		"RETENTION_WORK_QUEUE":  3,
	}
)

func (x Retention) Enum() *Retention {
	p := new(Retention)
	*p = x
	return p
}

func (x Retention) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Retention) Descriptor() protoreflect.EnumDescriptor {
	return file_nats_asyncapi_v1_annotations_proto_enumTypes[3].Descriptor()
}

func (Retention) Type() protoreflect.EnumType {
	return &file_nats_asyncapi_v1_annotations_proto_enumTypes[3]
}

func (x Retention) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Retention.Descriptor instead.
func (Retention) EnumDescriptor() ([]byte, []int) {
	return file_nats_asyncapi_v1_annotations_proto_rawDescGZIP(), []int{3}
}

type Storage int32

const (
	Storage_STORAGE_UNSPECIFIED Storage = 0
	Storage_STORAGE_FILE        Storage = 1
	Storage_STORAGE_MEMORY      Storage = 2
)

// Enum value maps for Storage.
var (
	Storage_name = map[int32]string{
		0: "STORAGE_UNSPECIFIED",
		1: "STORAGE_FILE",
		2: "STORAGE_MEMORY",
	}
	Storage_value = map[string]int32{
		"STORAGE_UNSPECIFIED": 0,
		"STORAGE_FILE":        1,
		"STORAGE_MEMORY":      2,
	}
)

func (x Storage) Enum() *Storage {
	p := new(Storage)
	*p = x
	return p
}

func (x Storage) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Storage) Descriptor() protoreflect.EnumDescriptor {
	return file_nats_asyncapi_v1_annotations_proto_enumTypes[4].Descriptor()
}

func (Storage) Type() protoreflect.EnumType {
	return &file_nats_asyncapi_v1_annotations_proto_enumTypes[4]
}

func (x Storage) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Storage.Descriptor instead.
func (Storage) EnumDescriptor() ([]byte, []int) {
	return file_nats_asyncapi_v1_annotations_proto_rawDescGZIP(), []int{4}
}

type Discard int32

const (
	Discard_DISCARD_UNSPECIFIED Discard = 0
	Discard_DISCARD_OLD         Discard = 1
	Discard_DISCARD_NEW         Discard = 2
)

// Enum value maps for Discard.
var (
	Discard_name = map[int32]string{
		0: "DISCARD_UNSPECIFIED",
		1: "DISCARD_OLD",
		2: "DISCARD_NEW",
	}
	Discard_value = map[string]int32{
		"DISCARD_UNSPECIFIED": 0,
		"DISCARD_OLD":         1,
		"DISCARD_NEW":         2,
	}
)

func (x Discard) Enum() *Discard {
	p := new(Discard)
	*p = x
	return p
}

func (x Discard) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Discard) Descriptor() protoreflect.EnumDescriptor {
	return file_nats_asyncapi_v1_annotations_proto_enumTypes[5].Descriptor()
}

func (Discard) Type() protoreflect.EnumType {
	return &file_nats_asyncapi_v1_annotations_proto_enumTypes[5]
}

func (x Discard) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Discard.Descriptor instead.
func (Discard) EnumDescriptor() ([]byte, []int) {
	return file_nats_asyncapi_v1_annotations_proto_rawDescGZIP(), []int{5}
}

type Compression int32

const (
	Compression_COMPRESSION_UNSPECIFIED Compression = 0
	Compression_COMPRESSION_NONE        Compression = 1
	Compression_COMPRESSION_S2          Compression = 2
)

// Enum value maps for Compression.
var (
	Compression_name = map[int32]string{
		0: "COMPRESSION_UNSPECIFIED",
		1: "COMPRESSION_NONE",
		2: "COMPRESSION_S2",
	}
	Compression_value = map[string]int32{
		"COMPRESSION_UNSPECIFIED": 0,
		"COMPRESSION_NONE":        1,
		"COMPRESSION_S2":          2,
	}
)

func (x Compression) Enum() *Compression {
	p := new(Compression)
	*p = x
	return p
}

func (x Compression) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Compression) Descriptor() protoreflect.EnumDescriptor {
	return file_nats_asyncapi_v1_annotations_proto_enumTypes[6].Descriptor()
}

func (Compression) Type() protoreflect.EnumType {
	return &file_nats_asyncapi_v1_annotations_proto_enumTypes[6]
}

func (x Compression) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Compression.Descriptor instead.
func (Compression) EnumDescriptor() ([]byte, []int) {
	return file_nats_asyncapi_v1_annotations_proto_rawDescGZIP(), []int{6}
}

type ConsumerKind int32

const (
	// Pull consumer (default, recommended).
	ConsumerKind_CONSUMER_KIND_UNSPECIFIED ConsumerKind = 0
	ConsumerKind_CONSUMER_KIND_PULL        ConsumerKind = 1
	ConsumerKind_CONSUMER_KIND_PUSH        ConsumerKind = 2
	// Ordered, ephemeral, flow-controlled consumer.
	ConsumerKind_CONSUMER_KIND_ORDERED ConsumerKind = 3
)

// Enum value maps for ConsumerKind.
var (
	ConsumerKind_name = map[int32]string{
		0: "CONSUMER_KIND_UNSPECIFIED",
		1: "CONSUMER_KIND_PULL",
		2: "CONSUMER_KIND_PUSH",
		3: "CONSUMER_KIND_ORDERED",
	}
	ConsumerKind_value = map[string]int32{
		"CONSUMER_KIND_UNSPECIFIED": 0,
		"CONSUMER_KIND_PULL":        1,
		"CONSUMER_KIND_PUSH":        2,
		"CONSUMER_KIND_ORDERED":     3,
	}
)

func (x ConsumerKind) Enum() *ConsumerKind {
	p := new(ConsumerKind)
	*p = x
	return p
}

func (x ConsumerKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConsumerKind) Descriptor() protoreflect.EnumDescriptor {
	return file_nats_asyncapi_v1_annotations_proto_enumTypes[7].Descriptor()
}

func (ConsumerKind) Type() protoreflect.EnumType {
	return &file_nats_asyncapi_v1_annotations_proto_enumTypes[7]
}

func (x ConsumerKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ConsumerKind.Descriptor instead.
func (ConsumerKind) EnumDescriptor() ([]byte, []int) {
	return file_nats_asyncapi_v1_annotations_proto_rawDescGZIP(), []int{7}
}

type DeliverPolicy int32

const (
	DeliverPolicy_DELIVER_POLICY_UNSPECIFIED       DeliverPolicy = 0
	DeliverPolicy_DELIVER_POLICY_ALL               DeliverPolicy = 1
	DeliverPolicy_DELIVER_POLICY_LAST              DeliverPolicy = 2
	DeliverPolicy_DELIVER_POLICY_NEW               DeliverPolicy = 3
	DeliverPolicy_DELIVER_POLICY_BY_START_SEQUENCE DeliverPolicy = 4
	DeliverPolicy_DELIVER_POLICY_BY_START_TIME     DeliverPolicy = 5
	DeliverPolicy_DELIVER_POLICY_LAST_PER_SUBJECT  DeliverPolicy = 6
)

// Enum value maps for DeliverPolicy.
var (
	DeliverPolicy_name = map[int32]string{
		0: "DELIVER_POLICY_UNSPECIFIED",
		1: "DELIVER_POLICY_ALL",
		2: "DELIVER_POLICY_LAST",
		3: "DELIVER_POLICY_NEW",
		4: "DELIVER_POLICY_BY_START_SEQUENCE",
		5: "DELIVER_POLICY_BY_START_TIME",
		6: "DELIVER_POLICY_LAST_PER_SUBJECT",
	}
	DeliverPolicy_value = map[string]int32{
		"DELIVER_POLICY_UNSPECIFIED":       0,
		"DELIVER_POLICY_ALL":               1,
		"DELIVER_POLICY_LAST":              2,
		"DELIVER_POLICY_NEW":               3,
		"DELIVER_POLICY_BY_START_SEQUENCE": 4,
		"DELIVER_POLICY_BY_START_TIME":     5,
		"DELIVER_POLICY_LAST_PER_SUBJECT":  6,
	}
)

func (x DeliverPolicy) Enum() *DeliverPolicy {
	p := new(DeliverPolicy)
	*p = x
	return p
}

func (x DeliverPolicy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeliverPolicy) Descriptor() protoreflect.EnumDescriptor {
	return file_nats_asyncapi_v1_annotations_proto_enumTypes[8].Descriptor()
}

func (DeliverPolicy) Type() protoreflect.EnumType {
	return &file_nats_asyncapi_v1_annotations_proto_enumTypes[8]
}

func (x DeliverPolicy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DeliverPolicy.Descriptor instead.
func (DeliverPolicy) EnumDescriptor() ([]byte, []int) {
	return file_nats_asyncapi_v1_annotations_proto_rawDescGZIP(), []int{8}
}

type AckPolicy int32

const (
	AckPolicy_ACK_POLICY_UNSPECIFIED AckPolicy = 0
	AckPolicy_ACK_POLICY_NONE        AckPolicy = 1
	AckPolicy_ACK_POLICY_ALL         AckPolicy = 2
	AckPolicy_ACK_POLICY_EXPLICIT    AckPolicy = 3
)

// Enum value maps for AckPolicy.
var (
	AckPolicy_name = map[int32]string{
		0: "ACK_POLICY_UNSPECIFIED",
		1: "ACK_POLICY_NONE",
		2: "ACK_POLICY_ALL",
		3: "ACK_POLICY_EXPLICIT",
	}
	AckPolicy_value = map[string]int32{
		"ACK_POLICY_UNSPECIFIED": 0,
		"ACK_POLICY_NONE":        1,
		"ACK_POLICY_ALL":         2,
		"ACK_POLICY_EXPLICIT":    3,
	}
)

func (x AckPolicy) Enum() *AckPolicy {
	p := new(AckPolicy)
	*p = x
	return p
}

func (x AckPolicy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AckPolicy) Descriptor() protoreflect.EnumDescriptor {
	return file_nats_asyncapi_v1_annotations_proto_enumTypes[9].Descriptor()
}

func (AckPolicy) Type() protoreflect.EnumType {
	return &file_nats_asyncapi_v1_annotations_proto_enumTypes[9]
}

func (x AckPolicy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AckPolicy.Descriptor instead.
func (AckPolicy) EnumDescriptor() ([]byte, []int) {
	return file_nats_asyncapi_v1_annotations_proto_rawDescGZIP(), []int{9}
}

type ReplayPolicy int32

const (
	ReplayPolicy_REPLAY_POLICY_UNSPECIFIED ReplayPolicy = 0
	ReplayPolicy_REPLAY_POLICY_INSTANT     ReplayPolicy = 1
	ReplayPolicy_REPLAY_POLICY_ORIGINAL    ReplayPolicy = 2
)

// Enum value maps for ReplayPolicy.
var (
	ReplayPolicy_name = map[int32]string{
		0: "REPLAY_POLICY_UNSPECIFIED",
		1: "REPLAY_POLICY_INSTANT",
		2: "REPLAY_POLICY_ORIGINAL",
	}
	ReplayPolicy_value = map[string]int32{
		"REPLAY_POLICY_UNSPECIFIED": 0,
		"REPLAY_POLICY_INSTANT":     1,
		"REPLAY_POLICY_ORIGINAL":    2,
	}
)

func (x ReplayPolicy) Enum() *ReplayPolicy {
	p := new(ReplayPolicy)
	*p = x
	return p
}

func (x ReplayPolicy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ReplayPolicy) Descriptor() protoreflect.EnumDescriptor {
	return file_nats_asyncapi_v1_annotations_proto_enumTypes[10].Descriptor()
}

func (ReplayPolicy) Type() protoreflect.EnumType {
	return &file_nats_asyncapi_v1_annotations_proto_enumTypes[10]
}

func (x ReplayPolicy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ReplayPolicy.Descriptor instead.
func (ReplayPolicy) EnumDescriptor() ([]byte, []int) {
	return file_nats_asyncapi_v1_annotations_proto_rawDescGZIP(), []int{10}
}

type PriorityPolicy int32

const (
	PriorityPolicy_PRIORITY_POLICY_UNSPECIFIED   PriorityPolicy = 0
	PriorityPolicy_PRIORITY_POLICY_NONE          PriorityPolicy = 1
	PriorityPolicy_PRIORITY_POLICY_OVERFLOW      PriorityPolicy = 2
	PriorityPolicy_PRIORITY_POLICY_PINNED_CLIENT PriorityPolicy = 3
	// NATS 2.12.
	PriorityPolicy_PRIORITY_POLICY_PRIORITIZED PriorityPolicy = 4
)

// Enum value maps for PriorityPolicy.
var (
	PriorityPolicy_name = map[int32]string{
		0: "PRIORITY_POLICY_UNSPECIFIED",
		1: "PRIORITY_POLICY_NONE",
		2: "PRIORITY_POLICY_OVERFLOW",
		3: "PRIORITY_POLICY_PINNED_CLIENT",
		4: "PRIORITY_POLICY_PRIORITIZED",
	}
	PriorityPolicy_value = map[string]int32{
		"PRIORITY_POLICY_UNSPECIFIED":   0,
		"PRIORITY_POLICY_NONE":          1,
		"PRIORITY_POLICY_OVERFLOW":      2,
		"PRIORITY_POLICY_PINNED_CLIENT": 3,
		"PRIORITY_POLICY_PRIORITIZED":   4,
	}
)

func (x PriorityPolicy) Enum() *PriorityPolicy {
	p := new(PriorityPolicy)
	*p = x
	return p
}

func (x PriorityPolicy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PriorityPolicy) Descriptor() protoreflect.EnumDescriptor {
	return file_nats_asyncapi_v1_annotations_proto_enumTypes[11].Descriptor()
}

func (PriorityPolicy) Type() protoreflect.EnumType {
	return &file_nats_asyncapi_v1_annotations_proto_enumTypes[11]
}

func (x PriorityPolicy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PriorityPolicy.Descriptor instead.
func (PriorityPolicy) EnumDescriptor() ([]byte, []int) {
	return file_nats_asyncapi_v1_annotations_proto_rawDescGZIP(), []int{11}
}

// Document holds the NATS specifics of a document. When several files are
// merged into a single AsyncAPI document, the settings of all files (and of
// the files they import) are combined.
type Document struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// NATS details of servers declared in (asyncapi.v3.document).servers.
	Servers []*Server `protobuf:"bytes,1,rep,name=servers,proto3" json:"servers,omitempty"`
	// NATS authentication mechanism of security schemes declared in
	// (asyncapi.v3.document).security_schemes.
	Auth []*Auth `protobuf:"bytes,2,rep,name=auth,proto3" json:"auth,omitempty"`
	// JetStream streams used by the application.
	Streams []*Stream `protobuf:"bytes,3,rep,name=streams,proto3" json:"streams,omitempty"`
	// JetStream key-value buckets used by the application.
	KvBuckets []*KeyValueBucket `protobuf:"bytes,4,rep,name=kv_buckets,json=kvBuckets,proto3" json:"kv_buckets,omitempty"`
	// JetStream object stores used by the application.
	ObjectStores  []*ObjectStore `protobuf:"bytes,5,rep,name=object_stores,json=objectStores,proto3" json:"object_stores,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Document) Reset() {
	*x = Document{}
	mi := &file_nats_asyncapi_v1_annotations_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Document) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Document) ProtoMessage() {}

func (x *Document) ProtoReflect() protoreflect.Message {
	mi := &file_nats_asyncapi_v1_annotations_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Document.ProtoReflect.Descriptor instead.
func (*Document) Descriptor() ([]byte, []int) {
	return file_nats_asyncapi_v1_annotations_proto_rawDescGZIP(), []int{0}
}

func (x *Document) GetServers() []*Server {
	if x != nil {
		return x.Servers
	}
	return nil
}

func (x *Document) GetAuth() []*Auth {
	if x != nil {
		return x.Auth
	}
	return nil
}

func (x *Document) GetStreams() []*Stream {
	if x != nil {
		return x.Streams
	}
	return nil
}

func (x *Document) GetKvBuckets() []*KeyValueBucket {
	if x != nil {
		return x.KvBuckets
	}
	return nil
}

func (x *Document) GetObjectStores() []*ObjectStore {
	if x != nil {
		return x.ObjectStores
	}
	return nil
}

// Server adds NATS details to an asyncapi.v3 server, emitted as the `x-nats`
// server extension.
type Server struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name of the asyncapi.v3 server.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// NATS account the application binds to.
	Account string `protobuf:"bytes,2,opt,name=account,proto3" json:"account,omitempty"`
	// JetStream domain to use (for leaf node / hub topologies).
	JetstreamDomain string `protobuf:"bytes,3,opt,name=jetstream_domain,json=jetstreamDomain,proto3" json:"jetstream_domain,omitempty"`
	// JetStream API prefix when using account imports, e.g. "$JS.hub.API".
	JetstreamApiPrefix string `protobuf:"bytes,4,opt,name=jetstream_api_prefix,json=jetstreamApiPrefix,proto3" json:"jetstream_api_prefix,omitempty"`
	// Whether the server requires TLS.
	Tls           bool `protobuf:"varint,5,opt,name=tls,proto3" json:"tls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Server) Reset() {
	*x = Server{}
	mi := &file_nats_asyncapi_v1_annotations_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server) ProtoMessage() {}

func (x *Server) ProtoReflect() protoreflect.Message {
	mi := &file_nats_asyncapi_v1_annotations_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server.ProtoReflect.Descriptor instead.
func (*Server) Descriptor() ([]byte, []int) {
	return file_nats_asyncapi_v1_annotations_proto_rawDescGZIP(), []int{1}
}

func (x *Server) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Server) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *Server) GetJetstreamDomain() string {
	if x != nil {
		return x.JetstreamDomain
	}
	return ""
}

func (x *Server) GetJetstreamApiPrefix() string {
	if x != nil {
		return x.JetstreamApiPrefix
	}
	return ""
}

func (x *Server) GetTls() bool {
	if x != nil {
		return x.Tls
	}
	return false
}

// Auth tells which NATS mechanism an asyncapi.v3 security scheme uses. It is
// emitted as the `x-nats-auth` extension and, when the scheme has no type,
// determines it.
type Auth struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name of the asyncapi.v3 security scheme.
	Scheme        string   `protobuf:"bytes,1,opt,name=scheme,proto3" json:"scheme,omitempty"`
	Type          AuthType `protobuf:"varint,2,opt,name=type,proto3,enum=nats.asyncapi.v1.AuthType" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Auth) Reset() {
	*x = Auth{}
	mi := &file_nats_asyncapi_v1_annotations_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Auth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Auth) ProtoMessage() {}

func (x *Auth) ProtoReflect() protoreflect.Message {
	mi := &file_nats_asyncapi_v1_annotations_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Auth.ProtoReflect.Descriptor instead.
func (*Auth) Descriptor() ([]byte, []int) {
	return file_nats_asyncapi_v1_annotations_proto_rawDescGZIP(), []int{2}
}

func (x *Auth) GetScheme() string {
	if x != nil {
		return x.Scheme
	}
	return ""
}

func (x *Auth) GetType() AuthType {
	if x != nil {
		return x.Type
	}
	return AuthType_AUTH_TYPE_UNSPECIFIED
}

type Service struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Prefix joined (with ".") in front of every method subject, e.g.
	// "orders.v1". When a method has no subject the default is
	// "<subject_prefix>.<method_name_in_snake_case>".
	SubjectPrefix string `protobuf:"bytes,1,opt,name=subject_prefix,json=subjectPrefix,proto3" json:"subject_prefix,omitempty"`
	// Queue group used by methods that receive messages.
	QueueGroup string `protobuf:"bytes,2,opt,name=queue_group,json=queueGroup,proto3" json:"queue_group,omitempty"`
	// JetStream stream used by the methods. See Operation.stream.
	Stream string `protobuf:"bytes,3,opt,name=stream,proto3" json:"stream,omitempty"`
	// Expose the service as a NATS micro service (github.com/nats-io/nats.go/micro).
	Micro         *Micro `protobuf:"bytes,4,opt,name=micro,proto3" json:"micro,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Service) Reset() {
	*x = Service{}
	mi := &file_nats_asyncapi_v1_annotations_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Service) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Service) ProtoMessage() {}

func (x *Service) ProtoReflect() protoreflect.Message {
	mi := &file_nats_asyncapi_v1_annotations_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Service.ProtoReflect.Descriptor instead.
func (*Service) Descriptor() ([]byte, []int) {
	return file_nats_asyncapi_v1_annotations_proto_rawDescGZIP(), []int{3}
}

func (x *Service) GetSubjectPrefix() string {
	if x != nil {
		return x.SubjectPrefix
	}
	return ""
}

func (x *Service) GetQueueGroup() string {
	if x != nil {
		return x.QueueGroup
	}
	return ""
}

func (x *Service) GetStream() string {
	if x != nil {
		return x.Stream
	}
	return ""
}

func (x *Service) GetMicro() *Micro {
	if x != nil {
		return x.Micro
	}
	return nil
}

// Micro describes a NATS micro service. Request/reply methods become micro
// endpoints, the default queue group becomes "q", error headers are
// documented and the $SRV.PING/INFO/STATS discovery endpoints are added.
type Micro struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Service name as registered with micro, e.g. "orders". Must match
	// [A-Za-z0-9\-_]+.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Semantic version of the service, e.g. "1.2.0".
	Version     string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	// Endpoint group, used as default subject prefix.
	Group string `protobuf:"bytes,4,opt,name=group,proto3" json:"group,omitempty"`
	// Service metadata.
	Metadata map[string]string `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Disables the $SRV discovery endpoints.
	NoDiscovery   bool `protobuf:"varint,6,opt,name=no_discovery,json=noDiscovery,proto3" json:"no_discovery,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Micro) Reset() {
	*x = Micro{}
	mi := &file_nats_asyncapi_v1_annotations_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Micro) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Micro) ProtoMessage() {}

func (x *Micro) ProtoReflect() protoreflect.Message {
	mi := &file_nats_asyncapi_v1_annotations_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Micro.ProtoReflect.Descriptor instead.
func (*Micro) Descriptor() ([]byte, []int) {
	return file_nats_asyncapi_v1_annotations_proto_rawDescGZIP(), []int{4}
}

func (x *Micro) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Micro) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Micro) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Micro) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *Micro) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Micro) GetNoDiscovery() bool {
	if x != nil {
		return x.NoDiscovery
	}
	return false
}

// Operation describes a NATS operation.
type Operation struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// How the method maps onto NATS. Inferred when unspecified.
	Pattern Pattern `protobuf:"varint,1,opt,name=pattern,proto3,enum=nats.asyncapi.v1.Pattern" json:"pattern,omitempty"`
	// NATS subject. Parameters are written as {name} and must span a whole
	// token, e.g. "orders.{region}.{order_id}.created". NATS wildcards "*" and
	// ">" are allowed. Joined to Service.subject_prefix.
	Subject string `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`
	// Key-value bucket: the channel becomes "$KV.<bucket>.<key>". `subject` is
	// then the key (e.g. "users.{user_id}") and may be empty (">" = every key).
	KvBucket string `protobuf:"bytes,3,opt,name=kv_bucket,json=kvBucket,proto3" json:"kv_bucket,omitempty"`
	// Queue group for receiving operations. Overrides Service.queue_group.
	QueueGroup string `protobuf:"bytes,4,opt,name=queue_group,json=queueGroup,proto3" json:"queue_group,omitempty"`
	// Static reply subject for REQUEST_REPLY operations. By default replies
	// go to the dynamic inbox chosen by the requester.
	ReplySubject string `protobuf:"bytes,5,opt,name=reply_subject,json=replySubject,proto3" json:"reply_subject,omitempty"`
	// Additional reply messages, e.g. an error type (full Protobuf name).
	ReplyMessages []string `protobuf:"bytes,6,rep,name=reply_messages,json=replyMessages,proto3" json:"reply_messages,omitempty"`
	// JetStream stream the subject belongs to. Overrides Service.stream. When
	// empty, the stream whose subjects match the operation subject is used.
	Stream string `protobuf:"bytes,7,opt,name=stream,proto3" json:"stream,omitempty"`
	// JetStream consumer used to receive the messages.
	Consumer *Consumer `protobuf:"bytes,8,opt,name=consumer,proto3" json:"consumer,omitempty"`
	// JetStream publish behaviour.
	Publish       *Publish `protobuf:"bytes,9,opt,name=publish,proto3" json:"publish,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Operation) Reset() {
	*x = Operation{}
	mi := &file_nats_asyncapi_v1_annotations_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Operation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Operation) ProtoMessage() {}

func (x *Operation) ProtoReflect() protoreflect.Message {
	mi := &file_nats_asyncapi_v1_annotations_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Operation.ProtoReflect.Descriptor instead.
func (*Operation) Descriptor() ([]byte, []int) {
	return file_nats_asyncapi_v1_annotations_proto_rawDescGZIP(), []int{5}
}

func (x *Operation) GetPattern() Pattern {
	if x != nil {
		return x.Pattern
	}
	return Pattern_PATTERN_UNSPECIFIED
}

func (x *Operation) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *Operation) GetKvBucket() string {
	if x != nil {
		return x.KvBucket
	}
	return ""
}

func (x *Operation) GetQueueGroup() string {
	if x != nil {
		return x.QueueGroup
	}
	return ""
}

func (x *Operation) GetReplySubject() string {
	if x != nil {
		return x.ReplySubject
	}
	return ""
}

func (x *Operation) GetReplyMessages() []string {
	if x != nil {
		return x.ReplyMessages
	}
	return nil
}

func (x *Operation) GetStream() string {
	if x != nil {
		return x.Stream
	}
	return ""
}

func (x *Operation) GetConsumer() *Consumer {
	if x != nil {
		return x.Consumer
	}
	return nil
}

func (x *Operation) GetPublish() *Publish {
	if x != nil {
		return x.Publish
	}
	return nil
}

// Publish describes how messages are published to JetStream.
type Publish struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Document the JetStream publish acknowledgement as reply of the
	// operation. Enabled by default for JetStream subjects.
	Ack *bool `protobuf:"varint,1,opt,name=ack,proto3,oneof" json:"ack,omitempty"`
	// Messages carry a Nats-Msg-Id header used for de-duplication.
	MsgId bool `protobuf:"varint,2,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
	// Optimistic concurrency headers set by the publisher.
	Expect []Expect `protobuf:"varint,3,rep,packed,name=expect,proto3,enum=nats.asyncapi.v1.Expect" json:"expect,omitempty"`
	// Messages carry a Nats-TTL header (NATS 2.11+, requires allow_msg_ttl).
	Ttl bool `protobuf:"varint,4,opt,name=ttl,proto3" json:"ttl,omitempty"`
	// Messages are published as part of an atomic batch (NATS 2.12+,
	// requires allow_atomic).
	AtomicBatch bool `protobuf:"varint,5,opt,name=atomic_batch,json=atomicBatch,proto3" json:"atomic_batch,omitempty"`
	// Messages may be scheduled (NATS 2.12+, requires allow_msg_schedules).
	Schedule      bool `protobuf:"varint,6,opt,name=schedule,proto3" json:"schedule,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Publish) Reset() {
	*x = Publish{}
	mi := &file_nats_asyncapi_v1_annotations_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Publish) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Publish) ProtoMessage() {}

func (x *Publish) ProtoReflect() protoreflect.Message {
	mi := &file_nats_asyncapi_v1_annotations_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Publish.ProtoReflect.Descriptor instead.
func (*Publish) Descriptor() ([]byte, []int) {
	return file_nats_asyncapi_v1_annotations_proto_rawDescGZIP(), []int{6}
}

func (x *Publish) GetAck() bool {
	if x != nil && x.Ack != nil {
		return *x.Ack
	}
	return false
}

func (x *Publish) GetMsgId() bool {
	if x != nil {
		return x.MsgId
	}
	return false
}

func (x *Publish) GetExpect() []Expect {
	if x != nil {
		return x.Expect
	}
	return nil
}

func (x *Publish) GetTtl() bool {
	if x != nil {
		return x.Ttl
	}
	return false
}

func (x *Publish) GetAtomicBatch() bool {
	if x != nil {
		return x.AtomicBatch
	}
	return false
}

func (x *Publish) GetSchedule() bool {
	if x != nil {
		return x.Schedule
	}
	return false
}

// Message gives a Protobuf message its own subject. Operations without a
// subject use it; messages with a subject that no operation uses still get a
// channel.
type Message struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// NATS subject, see Operation.subject (not joined to a prefix).
	Subject string `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	// Key-value bucket, see Operation.kv_bucket.
	KvBucket      string `protobuf:"bytes,2,opt,name=kv_bucket,json=kvBucket,proto3" json:"kv_bucket,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_nats_asyncapi_v1_annotations_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_nats_asyncapi_v1_annotations_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_nats_asyncapi_v1_annotations_proto_rawDescGZIP(), []int{7}
}

func (x *Message) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *Message) GetKvBucket() string {
	if x != nil {
		return x.KvBucket
	}
	return ""
}

// Stream mirrors the JetStream stream configuration.
type Stream struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Stream name, e.g. "ORDERS".
	Name        string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	// Subjects captured by the stream. When empty, derived from the channels
	// bound to the stream (parameters become "*").
	Subjects             []string          `protobuf:"bytes,3,rep,name=subjects,proto3" json:"subjects,omitempty"`
	Retention            Retention         `protobuf:"varint,4,opt,name=retention,proto3,enum=nats.asyncapi.v1.Retention" json:"retention,omitempty"`
	Storage              Storage           `protobuf:"varint,5,opt,name=storage,proto3,enum=nats.asyncapi.v1.Storage" json:"storage,omitempty"`
	Replicas             int32             `protobuf:"varint,6,opt,name=replicas,proto3" json:"replicas,omitempty"`
	MaxConsumers         int32             `protobuf:"varint,7,opt,name=max_consumers,json=maxConsumers,proto3" json:"max_consumers,omitempty"`
	MaxMsgs              int64             `protobuf:"varint,8,opt,name=max_msgs,json=maxMsgs,proto3" json:"max_msgs,omitempty"`
	MaxBytes             string            `protobuf:"bytes,9,opt,name=max_bytes,json=maxBytes,proto3" json:"max_bytes,omitempty"`
	MaxAge               string            `protobuf:"bytes,10,opt,name=max_age,json=maxAge,proto3" json:"max_age,omitempty"`
	MaxMsgsPerSubject    int64             `protobuf:"varint,11,opt,name=max_msgs_per_subject,json=maxMsgsPerSubject,proto3" json:"max_msgs_per_subject,omitempty"`
	MaxMsgSize           string            `protobuf:"bytes,12,opt,name=max_msg_size,json=maxMsgSize,proto3" json:"max_msg_size,omitempty"`
	Discard              Discard           `protobuf:"varint,13,opt,name=discard,proto3,enum=nats.asyncapi.v1.Discard" json:"discard,omitempty"`
	DiscardNewPerSubject bool              `protobuf:"varint,14,opt,name=discard_new_per_subject,json=discardNewPerSubject,proto3" json:"discard_new_per_subject,omitempty"`
	DuplicateWindow      string            `protobuf:"bytes,15,opt,name=duplicate_window,json=duplicateWindow,proto3" json:"duplicate_window,omitempty"`
	NoAck                bool              `protobuf:"varint,16,opt,name=no_ack,json=noAck,proto3" json:"no_ack,omitempty"`
	AllowDirect          bool              `protobuf:"varint,17,opt,name=allow_direct,json=allowDirect,proto3" json:"allow_direct,omitempty"`
	MirrorDirect         bool              `protobuf:"varint,18,opt,name=mirror_direct,json=mirrorDirect,proto3" json:"mirror_direct,omitempty"`
	AllowRollupHdrs      bool              `protobuf:"varint,19,opt,name=allow_rollup_hdrs,json=allowRollupHdrs,proto3" json:"allow_rollup_hdrs,omitempty"`
	DenyDelete           bool              `protobuf:"varint,20,opt,name=deny_delete,json=denyDelete,proto3" json:"deny_delete,omitempty"`
	DenyPurge            bool              `protobuf:"varint,21,opt,name=deny_purge,json=denyPurge,proto3" json:"deny_purge,omitempty"`
	Compression          Compression       `protobuf:"varint,22,opt,name=compression,proto3,enum=nats.asyncapi.v1.Compression" json:"compression,omitempty"`
	FirstSeq             uint64            `protobuf:"varint,23,opt,name=first_seq,json=firstSeq,proto3" json:"first_seq,omitempty"`
	Placement            *Placement        `protobuf:"bytes,24,opt,name=placement,proto3" json:"placement,omitempty"`
	Mirror               *StreamSource     `protobuf:"bytes,25,opt,name=mirror,proto3" json:"mirror,omitempty"`
	Sources              []*StreamSource   `protobuf:"bytes,26,rep,name=sources,proto3" json:"sources,omitempty"`
	Republish            *Republish        `protobuf:"bytes,27,opt,name=republish,proto3" json:"republish,omitempty"`
	SubjectTransform     *SubjectTransform `protobuf:"bytes,28,opt,name=subject_transform,json=subjectTransform,proto3" json:"subject_transform,omitempty"`
	Metadata             map[string]string `protobuf:"bytes,29,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// NATS 2.11: per message TTL via the Nats-TTL header.
	AllowMsgTtl bool `protobuf:"varint,30,opt,name=allow_msg_ttl,json=allowMsgTtl,proto3" json:"allow_msg_ttl,omitempty"`
	// NATS 2.11: TTL of delete markers left by max_age.
	SubjectDeleteMarkerTtl string `protobuf:"bytes,31,opt,name=subject_delete_marker_ttl,json=subjectDeleteMarkerTtl,proto3" json:"subject_delete_marker_ttl,omitempty"`
	// NATS 2.12: atomic batch publishing.
	AllowAtomic bool `protobuf:"varint,32,opt,name=allow_atomic,json=allowAtomic,proto3" json:"allow_atomic,omitempty"`
	// NATS 2.12: distributed counters.
	AllowMsgCounter bool `protobuf:"varint,33,opt,name=allow_msg_counter,json=allowMsgCounter,proto3" json:"allow_msg_counter,omitempty"`
	// NATS 2.12: message scheduling.
	AllowMsgSchedules bool `protobuf:"varint,34,opt,name=allow_msg_schedules,json=allowMsgSchedules,proto3" json:"allow_msg_schedules,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Stream) Reset() {
	*x = Stream{}
	mi := &file_nats_asyncapi_v1_annotations_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Stream) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Stream) ProtoMessage() {}

func (x *Stream) ProtoReflect() protoreflect.Message {
	mi := &file_nats_asyncapi_v1_annotations_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Stream.ProtoReflect.Descriptor instead.
func (*Stream) Descriptor() ([]byte, []int) {
	return file_nats_asyncapi_v1_annotations_proto_rawDescGZIP(), []int{8}
}

func (x *Stream) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Stream) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Stream) GetSubjects() []string {
	if x != nil {
		return x.Subjects
	}
	return nil
}

func (x *Stream) GetRetention() Retention {
	if x != nil {
		return x.Retention
	}
	return Retention_RETENTION_UNSPECIFIED
}

func (x *Stream) GetStorage() Storage {
	if x != nil {
		return x.Storage
	}
	return Storage_STORAGE_UNSPECIFIED
}

func (x *Stream) GetReplicas() int32 {
	if x != nil {
		return x.Replicas
	}
	return 0
}

func (x *Stream) GetMaxConsumers() int32 {
	if x != nil {
		return x.MaxConsumers
	}
	return 0
}

func (x *Stream) GetMaxMsgs() int64 {
	if x != nil {
		return x.MaxMsgs
	}
	return 0
}

func (x *Stream) GetMaxBytes() string {
	if x != nil {
		return x.MaxBytes
	}
	return ""
}

func (x *Stream) GetMaxAge() string {
	if x != nil {
		return x.MaxAge
	}
	return ""
}

func (x *Stream) GetMaxMsgsPerSubject() int64 {
	if x != nil {
		return x.MaxMsgsPerSubject
	}
	return 0
}

func (x *Stream) GetMaxMsgSize() string {
	if x != nil {
		return x.MaxMsgSize
	}
	return ""
}

func (x *Stream) GetDiscard() Discard {
	if x != nil {
		return x.Discard
	}
	return Discard_DISCARD_UNSPECIFIED
}

func (x *Stream) GetDiscardNewPerSubject() bool {
	if x != nil {
		return x.DiscardNewPerSubject
	}
	return false
}

func (x *Stream) GetDuplicateWindow() string {
	if x != nil {
		return x.DuplicateWindow
	}
	return ""
}

func (x *Stream) GetNoAck() bool {
	if x != nil {
		return x.NoAck
	}
	return false
}

func (x *Stream) GetAllowDirect() bool {
	if x != nil {
		return x.AllowDirect
	}
	return false
}

func (x *Stream) GetMirrorDirect() bool {
	if x != nil {
		return x.MirrorDirect
	}
	return false
}

func (x *Stream) GetAllowRollupHdrs() bool {
	if x != nil {
		return x.AllowRollupHdrs
	}
	return false
}

func (x *Stream) GetDenyDelete() bool {
	if x != nil {
		return x.DenyDelete
	}
	return false
}

func (x *Stream) GetDenyPurge() bool {
	if x != nil {
		return x.DenyPurge
	}
	return false
}

func (x *Stream) GetCompression() Compression {
	if x != nil {
		return x.Compression
	}
	return Compression_COMPRESSION_UNSPECIFIED
}

func (x *Stream) GetFirstSeq() uint64 {
	if x != nil {
		return x.FirstSeq
	}
	return 0
}

func (x *Stream) GetPlacement() *Placement {
	if x != nil {
		return x.Placement
	}
	return nil
}

func (x *Stream) GetMirror() *StreamSource {
	if x != nil {
		return x.Mirror
	}
	return nil
}

func (x *Stream) GetSources() []*StreamSource {
	if x != nil {
		return x.Sources
	}
	return nil
}

func (x *Stream) GetRepublish() *Republish {
	if x != nil {
		return x.Republish
	}
	return nil
}

func (x *Stream) GetSubjectTransform() *SubjectTransform {
	if x != nil {
		return x.SubjectTransform
	}
	return nil
}

func (x *Stream) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Stream) GetAllowMsgTtl() bool {
	if x != nil {
		return x.AllowMsgTtl
	}
	return false
}

func (x *Stream) GetSubjectDeleteMarkerTtl() string {
	if x != nil {
		return x.SubjectDeleteMarkerTtl
	}
	return ""
}

func (x *Stream) GetAllowAtomic() bool {
	if x != nil {
		return x.AllowAtomic
	}
	return false
}

func (x *Stream) GetAllowMsgCounter() bool {
	if x != nil {
		return x.AllowMsgCounter
	}
	return false
}

func (x *Stream) GetAllowMsgSchedules() bool {
	if x != nil {
		return x.AllowMsgSchedules
	}
	return false
}

type Placement struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Cluster string                 `protobuf:"bytes,1,opt,name=cluster,proto3" json:"cluster,omitempty"`
	Tags    []string               `protobuf:"bytes,2,rep,name=tags,proto3" json:"tags,omitempty"`
	// NATS 2.12: preferred leader.
	Preferred     string `protobuf:"bytes,3,opt,name=preferred,proto3" json:"preferred,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Placement) Reset() {
	*x = Placement{}
	mi := &file_nats_asyncapi_v1_annotations_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Placement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Placement) ProtoMessage() {}

func (x *Placement) ProtoReflect() protoreflect.Message {
	mi := &file_nats_asyncapi_v1_annotations_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Placement.ProtoReflect.Descriptor instead.
func (*Placement) Descriptor() ([]byte, []int) {
	return file_nats_asyncapi_v1_annotations_proto_rawDescGZIP(), []int{9}
}

func (x *Placement) GetCluster() string {
	if x != nil {
		return x.Cluster
	}
	return ""
}

func (x *Placement) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Placement) GetPreferred() string {
	if x != nil {
		return x.Preferred
	}
	return ""
}

type StreamSource struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Name        string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	OptStartSeq uint64                 `protobuf:"varint,2,opt,name=opt_start_seq,json=optStartSeq,proto3" json:"opt_start_seq,omitempty"`
	// RFC 3339 timestamp.
	OptStartTime      string              `protobuf:"bytes,3,opt,name=opt_start_time,json=optStartTime,proto3" json:"opt_start_time,omitempty"`
	FilterSubject     string              `protobuf:"bytes,4,opt,name=filter_subject,json=filterSubject,proto3" json:"filter_subject,omitempty"`
	SubjectTransforms []*SubjectTransform `protobuf:"bytes,5,rep,name=subject_transforms,json=subjectTransforms,proto3" json:"subject_transforms,omitempty"`
	// Cross-domain / cross-account access.
	ExternalApiPrefix     string `protobuf:"bytes,6,opt,name=external_api_prefix,json=externalApiPrefix,proto3" json:"external_api_prefix,omitempty"`
	ExternalDeliverPrefix string `protobuf:"bytes,7,opt,name=external_deliver_prefix,json=externalDeliverPrefix,proto3" json:"external_deliver_prefix,omitempty"`
	Domain                string `protobuf:"bytes,8,opt,name=domain,proto3" json:"domain,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *StreamSource) Reset() {
	*x = StreamSource{}
	mi := &file_nats_asyncapi_v1_annotations_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamSource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamSource) ProtoMessage() {}

func (x *StreamSource) ProtoReflect() protoreflect.Message {
	mi := &file_nats_asyncapi_v1_annotations_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamSource.ProtoReflect.Descriptor instead.
func (*StreamSource) Descriptor() ([]byte, []int) {
	return file_nats_asyncapi_v1_annotations_proto_rawDescGZIP(), []int{10}
}

func (x *StreamSource) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StreamSource) GetOptStartSeq() uint64 {
	if x != nil {
		return x.OptStartSeq
	}
	return 0
}

func (x *StreamSource) GetOptStartTime() string {
	if x != nil {
		return x.OptStartTime
	}
	return ""
}

func (x *StreamSource) GetFilterSubject() string {
	if x != nil {
		return x.FilterSubject
	}
	return ""
}

func (x *StreamSource) GetSubjectTransforms() []*SubjectTransform {
	if x != nil {
		return x.SubjectTransforms
	}
	return nil
}

func (x *StreamSource) GetExternalApiPrefix() string {
	if x != nil {
		return x.ExternalApiPrefix
	}
	return ""
}

func (x *StreamSource) GetExternalDeliverPrefix() string {
	if x != nil {
		return x.ExternalDeliverPrefix
	}
	return ""
}

func (x *StreamSource) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

type SubjectTransform struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Src           string                 `protobuf:"bytes,1,opt,name=src,proto3" json:"src,omitempty"`
	Dest          string                 `protobuf:"bytes,2,opt,name=dest,proto3" json:"dest,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubjectTransform) Reset() {
	*x = SubjectTransform{}
	mi := &file_nats_asyncapi_v1_annotations_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubjectTransform) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubjectTransform) ProtoMessage() {}

func (x *SubjectTransform) ProtoReflect() protoreflect.Message {
	mi := &file_nats_asyncapi_v1_annotations_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubjectTransform.ProtoReflect.Descriptor instead.
func (*SubjectTransform) Descriptor() ([]byte, []int) {
	return file_nats_asyncapi_v1_annotations_proto_rawDescGZIP(), []int{11}
}

func (x *SubjectTransform) GetSrc() string {
	if x != nil {
		return x.Src
	}
	return ""
}

func (x *SubjectTransform) GetDest() string {
	if x != nil {
		return x.Dest
	}
	return ""
}

type Republish struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Src           string                 `protobuf:"bytes,1,opt,name=src,proto3" json:"src,omitempty"`
	Dest          string                 `protobuf:"bytes,2,opt,name=dest,proto3" json:"dest,omitempty"`
	HeadersOnly   bool                   `protobuf:"varint,3,opt,name=headers_only,json=headersOnly,proto3" json:"headers_only,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Republish) Reset() {
	*x = Republish{}
	mi := &file_nats_asyncapi_v1_annotations_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Republish) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Republish) ProtoMessage() {}

func (x *Republish) ProtoReflect() protoreflect.Message {
	mi := &file_nats_asyncapi_v1_annotations_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Republish.ProtoReflect.Descriptor instead.
func (*Republish) Descriptor() ([]byte, []int) {
	return file_nats_asyncapi_v1_annotations_proto_rawDescGZIP(), []int{12}
}

func (x *Republish) GetSrc() string {
	if x != nil {
		return x.Src
	}
	return ""
}

func (x *Republish) GetDest() string {
	if x != nil {
		return x.Dest
	}
	return ""
}

func (x *Republish) GetHeadersOnly() bool {
	if x != nil {
		return x.HeadersOnly
	}
	return false
}

// Consumer mirrors the JetStream consumer configuration.
type Consumer struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Durable name. When empty the consumer is ephemeral.
	Durable string `protobuf:"bytes,1,opt,name=durable,proto3" json:"durable,omitempty"`
	// Consumer name (when different from the durable name).
	Name          string        `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string        `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Kind          ConsumerKind  `protobuf:"varint,4,opt,name=kind,proto3,enum=nats.asyncapi.v1.ConsumerKind" json:"kind,omitempty"`
	DeliverPolicy DeliverPolicy `protobuf:"varint,5,opt,name=deliver_policy,json=deliverPolicy,proto3,enum=nats.asyncapi.v1.DeliverPolicy" json:"deliver_policy,omitempty"`
	OptStartSeq   uint64        `protobuf:"varint,6,opt,name=opt_start_seq,json=optStartSeq,proto3" json:"opt_start_seq,omitempty"`
	// RFC 3339 timestamp.
	OptStartTime string    `protobuf:"bytes,7,opt,name=opt_start_time,json=optStartTime,proto3" json:"opt_start_time,omitempty"`
	AckPolicy    AckPolicy `protobuf:"varint,8,opt,name=ack_policy,json=ackPolicy,proto3,enum=nats.asyncapi.v1.AckPolicy" json:"ack_policy,omitempty"`
	AckWait      string    `protobuf:"bytes,9,opt,name=ack_wait,json=ackWait,proto3" json:"ack_wait,omitempty"`
	MaxDeliver   int32     `protobuf:"varint,10,opt,name=max_deliver,json=maxDeliver,proto3" json:"max_deliver,omitempty"`
	Backoff      []string  `protobuf:"bytes,11,rep,name=backoff,proto3" json:"backoff,omitempty"`
	// Subjects to filter on. Defaults to the operation subject (parameters
	// become "*").
	FilterSubjects []string     `protobuf:"bytes,12,rep,name=filter_subjects,json=filterSubjects,proto3" json:"filter_subjects,omitempty"`
	ReplayPolicy   ReplayPolicy `protobuf:"varint,13,opt,name=replay_policy,json=replayPolicy,proto3,enum=nats.asyncapi.v1.ReplayPolicy" json:"replay_policy,omitempty"`
	RateLimitBps   uint64       `protobuf:"varint,14,opt,name=rate_limit_bps,json=rateLimitBps,proto3" json:"rate_limit_bps,omitempty"`
	// Percentage of acknowledgements to sample, e.g. "100%".
	SampleFreq        string            `protobuf:"bytes,15,opt,name=sample_freq,json=sampleFreq,proto3" json:"sample_freq,omitempty"`
	MaxWaiting        int32             `protobuf:"varint,16,opt,name=max_waiting,json=maxWaiting,proto3" json:"max_waiting,omitempty"`
	MaxAckPending     int32             `protobuf:"varint,17,opt,name=max_ack_pending,json=maxAckPending,proto3" json:"max_ack_pending,omitempty"`
	HeadersOnly       bool              `protobuf:"varint,18,opt,name=headers_only,json=headersOnly,proto3" json:"headers_only,omitempty"`
	MaxBatch          int32             `protobuf:"varint,19,opt,name=max_batch,json=maxBatch,proto3" json:"max_batch,omitempty"`
	MaxExpires        string            `protobuf:"bytes,20,opt,name=max_expires,json=maxExpires,proto3" json:"max_expires,omitempty"`
	MaxBytes          string            `protobuf:"bytes,21,opt,name=max_bytes,json=maxBytes,proto3" json:"max_bytes,omitempty"`
	InactiveThreshold string            `protobuf:"bytes,22,opt,name=inactive_threshold,json=inactiveThreshold,proto3" json:"inactive_threshold,omitempty"`
	Replicas          int32             `protobuf:"varint,23,opt,name=replicas,proto3" json:"replicas,omitempty"`
	MemStorage        bool              `protobuf:"varint,24,opt,name=mem_storage,json=memStorage,proto3" json:"mem_storage,omitempty"`
	Metadata          map[string]string `protobuf:"bytes,25,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Push consumers only.
	DeliverSubject string `protobuf:"bytes,26,opt,name=deliver_subject,json=deliverSubject,proto3" json:"deliver_subject,omitempty"`
	DeliverGroup   string `protobuf:"bytes,27,opt,name=deliver_group,json=deliverGroup,proto3" json:"deliver_group,omitempty"`
	FlowControl    bool   `protobuf:"varint,28,opt,name=flow_control,json=flowControl,proto3" json:"flow_control,omitempty"`
	IdleHeartbeat  string `protobuf:"bytes,29,opt,name=idle_heartbeat,json=idleHeartbeat,proto3" json:"idle_heartbeat,omitempty"`
	// NATS 2.11: priority groups for pull consumers.
	PriorityGroups  []string       `protobuf:"bytes,30,rep,name=priority_groups,json=priorityGroups,proto3" json:"priority_groups,omitempty"`
	PriorityPolicy  PriorityPolicy `protobuf:"varint,31,opt,name=priority_policy,json=priorityPolicy,proto3,enum=nats.asyncapi.v1.PriorityPolicy" json:"priority_policy,omitempty"`
	PriorityTimeout string         `protobuf:"bytes,32,opt,name=priority_timeout,json=priorityTimeout,proto3" json:"priority_timeout,omitempty"`
	// NATS 2.11: pause the consumer until the given RFC 3339 timestamp.
	PauseUntil    string `protobuf:"bytes,33,opt,name=pause_until,json=pauseUntil,proto3" json:"pause_until,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Consumer) Reset() {
	*x = Consumer{}
	mi := &file_nats_asyncapi_v1_annotations_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Consumer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Consumer) ProtoMessage() {}

func (x *Consumer) ProtoReflect() protoreflect.Message {
	mi := &file_nats_asyncapi_v1_annotations_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Consumer.ProtoReflect.Descriptor instead.
func (*Consumer) Descriptor() ([]byte, []int) {
	return file_nats_asyncapi_v1_annotations_proto_rawDescGZIP(), []int{13}
}

func (x *Consumer) GetDurable() string {
	if x != nil {
		return x.Durable
	}
	return ""
}

func (x *Consumer) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Consumer) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Consumer) GetKind() ConsumerKind {
	if x != nil {
		return x.Kind
	}
	return ConsumerKind_CONSUMER_KIND_UNSPECIFIED
}

func (x *Consumer) GetDeliverPolicy() DeliverPolicy {
	if x != nil {
		return x.DeliverPolicy
	}
	return DeliverPolicy_DELIVER_POLICY_UNSPECIFIED
}

func (x *Consumer) GetOptStartSeq() uint64 {
	if x != nil {
		return x.OptStartSeq
	}
	return 0
}

func (x *Consumer) GetOptStartTime() string {
	if x != nil {
		return x.OptStartTime
	}
	return ""
}

func (x *Consumer) GetAckPolicy() AckPolicy {
	if x != nil {
		return x.AckPolicy
	}
	return AckPolicy_ACK_POLICY_UNSPECIFIED
}

func (x *Consumer) GetAckWait() string {
	if x != nil {
		return x.AckWait
	}
	return ""
}

func (x *Consumer) GetMaxDeliver() int32 {
	if x != nil {
		return x.MaxDeliver
	}
	return 0
}

func (x *Consumer) GetBackoff() []string {
	if x != nil {
		return x.Backoff
	}
	return nil
}

func (x *Consumer) GetFilterSubjects() []string {
	if x != nil {
		return x.FilterSubjects
	}
	return nil
}

func (x *Consumer) GetReplayPolicy() ReplayPolicy {
	if x != nil {
		return x.ReplayPolicy
	}
	return ReplayPolicy_REPLAY_POLICY_UNSPECIFIED
}

func (x *Consumer) GetRateLimitBps() uint64 {
	if x != nil {
		return x.RateLimitBps
	}
	return 0
}

func (x *Consumer) GetSampleFreq() string {
	if x != nil {
		return x.SampleFreq
	}
	return ""
}

func (x *Consumer) GetMaxWaiting() int32 {
	if x != nil {
		return x.MaxWaiting
	}
	return 0
}

func (x *Consumer) GetMaxAckPending() int32 {
	if x != nil {
		return x.MaxAckPending
	}
	return 0
}

func (x *Consumer) GetHeadersOnly() bool {
	if x != nil {
		return x.HeadersOnly
	}
	return false
}

func (x *Consumer) GetMaxBatch() int32 {
	if x != nil {
		return x.MaxBatch
	}
	return 0
}

func (x *Consumer) GetMaxExpires() string {
	if x != nil {
		return x.MaxExpires
	}
	return ""
}

func (x *Consumer) GetMaxBytes() string {
	if x != nil {
		return x.MaxBytes
	}
	return ""
}

func (x *Consumer) GetInactiveThreshold() string {
	if x != nil {
		return x.InactiveThreshold
	}
	return ""
}

func (x *Consumer) GetReplicas() int32 {
	if x != nil {
		return x.Replicas
	}
	return 0
}

func (x *Consumer) GetMemStorage() bool {
	if x != nil {
		return x.MemStorage
	}
	return false
}

func (x *Consumer) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Consumer) GetDeliverSubject() string {
	if x != nil {
		return x.DeliverSubject
	}
	return ""
}

func (x *Consumer) GetDeliverGroup() string {
	if x != nil {
		return x.DeliverGroup
	}
	return ""
}

func (x *Consumer) GetFlowControl() bool {
	if x != nil {
		return x.FlowControl
	}
	return false
}

func (x *Consumer) GetIdleHeartbeat() string {
	if x != nil {
		return x.IdleHeartbeat
	}
	return ""
}

func (x *Consumer) GetPriorityGroups() []string {
	if x != nil {
		return x.PriorityGroups
	}
	return nil
}

func (x *Consumer) GetPriorityPolicy() PriorityPolicy {
	if x != nil {
		return x.PriorityPolicy
	}
	return PriorityPolicy_PRIORITY_POLICY_UNSPECIFIED
}

func (x *Consumer) GetPriorityTimeout() string {
	if x != nil {
		return x.PriorityTimeout
	}
	return ""
}

func (x *Consumer) GetPauseUntil() string {
	if x != nil {
		return x.PauseUntil
	}
	return ""
}

// KeyValueBucket mirrors the JetStream key-value configuration.
type KeyValueBucket struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Bucket name, e.g. "profiles".
	Bucket       string `protobuf:"bytes,1,opt,name=bucket,proto3" json:"bucket,omitempty"`
	Description  string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	MaxValueSize string `protobuf:"bytes,3,opt,name=max_value_size,json=maxValueSize,proto3" json:"max_value_size,omitempty"`
	// Number of historical values per key (1-64).
	History     int32           `protobuf:"varint,4,opt,name=history,proto3" json:"history,omitempty"`
	Ttl         string          `protobuf:"bytes,5,opt,name=ttl,proto3" json:"ttl,omitempty"`
	MaxBytes    string          `protobuf:"bytes,6,opt,name=max_bytes,json=maxBytes,proto3" json:"max_bytes,omitempty"`
	Storage     Storage         `protobuf:"varint,7,opt,name=storage,proto3,enum=nats.asyncapi.v1.Storage" json:"storage,omitempty"`
	Replicas    int32           `protobuf:"varint,8,opt,name=replicas,proto3" json:"replicas,omitempty"`
	Placement   *Placement      `protobuf:"bytes,9,opt,name=placement,proto3" json:"placement,omitempty"`
	Republish   *Republish      `protobuf:"bytes,10,opt,name=republish,proto3" json:"republish,omitempty"`
	Mirror      *StreamSource   `protobuf:"bytes,11,opt,name=mirror,proto3" json:"mirror,omitempty"`
	Sources     []*StreamSource `protobuf:"bytes,12,rep,name=sources,proto3" json:"sources,omitempty"`
	Compression bool            `protobuf:"varint,13,opt,name=compression,proto3" json:"compression,omitempty"`
	// NATS 2.11: TTL of markers left by per-key TTL / limits.
	LimitMarkerTtl string            `protobuf:"bytes,14,opt,name=limit_marker_ttl,json=limitMarkerTtl,proto3" json:"limit_marker_ttl,omitempty"`
	Metadata       map[string]string `protobuf:"bytes,15,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *KeyValueBucket) Reset() {
	*x = KeyValueBucket{}
	mi := &file_nats_asyncapi_v1_annotations_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyValueBucket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyValueBucket) ProtoMessage() {}

func (x *KeyValueBucket) ProtoReflect() protoreflect.Message {
	mi := &file_nats_asyncapi_v1_annotations_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyValueBucket.ProtoReflect.Descriptor instead.
func (*KeyValueBucket) Descriptor() ([]byte, []int) {
	return file_nats_asyncapi_v1_annotations_proto_rawDescGZIP(), []int{14}
}

func (x *KeyValueBucket) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

func (x *KeyValueBucket) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *KeyValueBucket) GetMaxValueSize() string {
	if x != nil {
		return x.MaxValueSize
	}
	return ""
}

func (x *KeyValueBucket) GetHistory() int32 {
	if x != nil {
		return x.History
	}
	return 0
}

func (x *KeyValueBucket) GetTtl() string {
	if x != nil {
		return x.Ttl
	}
	return ""
}

func (x *KeyValueBucket) GetMaxBytes() string {
	if x != nil {
		return x.MaxBytes
	}
	return ""
}

func (x *KeyValueBucket) GetStorage() Storage {
	if x != nil {
		return x.Storage
	}
	return Storage_STORAGE_UNSPECIFIED
}

func (x *KeyValueBucket) GetReplicas() int32 {
	if x != nil {
		return x.Replicas
	}
	return 0
}

func (x *KeyValueBucket) GetPlacement() *Placement {
	if x != nil {
		return x.Placement
	}
	return nil
}

func (x *KeyValueBucket) GetRepublish() *Republish {
	if x != nil {
		return x.Republish
	}
	return nil
}

func (x *KeyValueBucket) GetMirror() *StreamSource {
	if x != nil {
		return x.Mirror
	}
	return nil
}

func (x *KeyValueBucket) GetSources() []*StreamSource {
	if x != nil {
		return x.Sources
	}
	return nil
}

func (x *KeyValueBucket) GetCompression() bool {
	if x != nil {
		return x.Compression
	}
	return false
}

func (x *KeyValueBucket) GetLimitMarkerTtl() string {
	if x != nil {
		return x.LimitMarkerTtl
	}
	return ""
}

func (x *KeyValueBucket) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// ObjectStore mirrors the JetStream object store configuration.
type ObjectStore struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Bucket name, e.g. "images".
	Bucket        string            `protobuf:"bytes,1,opt,name=bucket,proto3" json:"bucket,omitempty"`
	Description   string            `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Ttl           string            `protobuf:"bytes,3,opt,name=ttl,proto3" json:"ttl,omitempty"`
	MaxBytes      string            `protobuf:"bytes,4,opt,name=max_bytes,json=maxBytes,proto3" json:"max_bytes,omitempty"`
	Storage       Storage           `protobuf:"varint,5,opt,name=storage,proto3,enum=nats.asyncapi.v1.Storage" json:"storage,omitempty"`
	Replicas      int32             `protobuf:"varint,6,opt,name=replicas,proto3" json:"replicas,omitempty"`
	Placement     *Placement        `protobuf:"bytes,7,opt,name=placement,proto3" json:"placement,omitempty"`
	Compression   bool              `protobuf:"varint,8,opt,name=compression,proto3" json:"compression,omitempty"`
	Metadata      map[string]string `protobuf:"bytes,9,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ObjectStore) Reset() {
	*x = ObjectStore{}
	mi := &file_nats_asyncapi_v1_annotations_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObjectStore) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectStore) ProtoMessage() {}

func (x *ObjectStore) ProtoReflect() protoreflect.Message {
	mi := &file_nats_asyncapi_v1_annotations_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectStore.ProtoReflect.Descriptor instead.
func (*ObjectStore) Descriptor() ([]byte, []int) {
	return file_nats_asyncapi_v1_annotations_proto_rawDescGZIP(), []int{15}
}

func (x *ObjectStore) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

func (x *ObjectStore) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ObjectStore) GetTtl() string {
	if x != nil {
		return x.Ttl
	}
	return ""
}

func (x *ObjectStore) GetMaxBytes() string {
	if x != nil {
		return x.MaxBytes
	}
	return ""
}

func (x *ObjectStore) GetStorage() Storage {
	if x != nil {
		return x.Storage
	}
	return Storage_STORAGE_UNSPECIFIED
}

func (x *ObjectStore) GetReplicas() int32 {
	if x != nil {
		return x.Replicas
	}
	return 0
}

func (x *ObjectStore) GetPlacement() *Placement {
	if x != nil {
		return x.Placement
	}
	return nil
}

func (x *ObjectStore) GetCompression() bool {
	if x != nil {
		return x.Compression
	}
	return false
}

func (x *ObjectStore) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

var file_nats_asyncapi_v1_annotations_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.FileOptions)(nil),
		ExtensionType: (*Document)(nil),
		Field:         58310,
		Name:          "nats.asyncapi.v1.document",
		Tag:           "bytes,58310,opt,name=document",
		Filename:      "nats/asyncapi/v1/annotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.ServiceOptions)(nil),
		ExtensionType: (*Service)(nil),
		Field:         58310,
		Name:          "nats.asyncapi.v1.service",
		Tag:           "bytes,58310,opt,name=service",
		Filename:      "nats/asyncapi/v1/annotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*Operation)(nil),
		Field:         58310,
		Name:          "nats.asyncapi.v1.operation",
		Tag:           "bytes,58310,opt,name=operation",
		Filename:      "nats/asyncapi/v1/annotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*Message)(nil),
		Field:         58310,
		Name:          "nats.asyncapi.v1.message",
		Tag:           "bytes,58310,opt,name=message",
		Filename:      "nats/asyncapi/v1/annotations.proto",
	},
}

// Extension fields to descriptorpb.FileOptions.
var (
	// NATS specifics of the document: server and authentication details and
	// JetStream assets (streams, key-value buckets, object stores).
	//
	// optional nats.asyncapi.v1.Document document = 58310;
	E_Document = &file_nats_asyncapi_v1_annotations_proto_extTypes[0]
)

// Extension fields to descriptorpb.ServiceOptions.
var (
	// NATS defaults applied to every method of the service.
	//
	// optional nats.asyncapi.v1.Service service = 58310;
	E_Service = &file_nats_asyncapi_v1_annotations_proto_extTypes[1]
)

// Extension fields to descriptorpb.MethodOptions.
var (
	// Describes the NATS operation implemented by a method.
	//
	// optional nats.asyncapi.v1.Operation operation = 58310;
	E_Operation = &file_nats_asyncapi_v1_annotations_proto_extTypes[2]
)

// Extension fields to descriptorpb.MessageOptions.
var (
	// Gives a message its own subject.
	//
	// optional nats.asyncapi.v1.Message message = 58310;
	E_Message = &file_nats_asyncapi_v1_annotations_proto_extTypes[3]
)

var File_nats_asyncapi_v1_annotations_proto protoreflect.FileDescriptor

const file_nats_asyncapi_v1_annotations_proto_rawDesc = "" +
	"\n" +
	"\"nats/asyncapi/v1/annotations.proto\x12\x10nats.asyncapi.v1\x1a google/protobuf/descriptor.proto\"\xa3\x02\n" +
	"\bDocument\x122\n" +
	"\aservers\x18\x01 \x03(\v2\x18.nats.asyncapi.v1.ServerR\aservers\x12*\n" +
	"\x04auth\x18\x02 \x03(\v2\x16.nats.asyncapi.v1.AuthR\x04auth\x122\n" +
	"\astreams\x18\x03 \x03(\v2\x18.nats.asyncapi.v1.StreamR\astreams\x12?\n" +
	"\n" +
	"kv_buckets\x18\x04 \x03(\v2 .nats.asyncapi.v1.KeyValueBucketR\tkvBuckets\x12B\n" +
	"\robject_stores\x18\x05 \x03(\v2\x1d.nats.asyncapi.v1.ObjectStoreR\fobjectStores\"\xa5\x01\n" +
	"\x06Server\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aaccount\x18\x02 \x01(\tR\aaccount\x12)\n" +
	"\x10jetstream_domain\x18\x03 \x01(\tR\x0fjetstreamDomain\x120\n" +
	"\x14jetstream_api_prefix\x18\x04 \x01(\tR\x12jetstreamApiPrefix\x12\x10\n" +
	"\x03tls\x18\x05 \x01(\bR\x03tls\"N\n" +
	"\x04Auth\x12\x16\n" +
	"\x06scheme\x18\x01 \x01(\tR\x06scheme\x12.\n" +
	"\x04type\x18\x02 \x01(\x0e2\x1a.nats.asyncapi.v1.AuthTypeR\x04type\"\x98\x01\n" +
	"\aService\x12%\n" +
	"\x0esubject_prefix\x18\x01 \x01(\tR\rsubjectPrefix\x12\x1f\n" +
	"\vqueue_group\x18\x02 \x01(\tR\n" +
	"queueGroup\x12\x16\n" +
	"\x06stream\x18\x03 \x01(\tR\x06stream\x12-\n" +
	"\x05micro\x18\x04 \x01(\v2\x17.nats.asyncapi.v1.MicroR\x05micro\"\x90\x02\n" +
	"\x05Micro\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x14\n" +
	"\x05group\x18\x04 \x01(\tR\x05group\x12A\n" +
	"\bmetadata\x18\x05 \x03(\v2%.nats.asyncapi.v1.Micro.MetadataEntryR\bmetadata\x12!\n" +
	"\fno_discovery\x18\x06 \x01(\bR\vnoDiscovery\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xe9\x02\n" +
	"\tOperation\x123\n" +
	"\apattern\x18\x01 \x01(\x0e2\x19.nats.asyncapi.v1.PatternR\apattern\x12\x18\n" +
	"\asubject\x18\x02 \x01(\tR\asubject\x12\x1b\n" +
	"\tkv_bucket\x18\x03 \x01(\tR\bkvBucket\x12\x1f\n" +
	"\vqueue_group\x18\x04 \x01(\tR\n" +
	"queueGroup\x12#\n" +
	"\rreply_subject\x18\x05 \x01(\tR\freplySubject\x12%\n" +
	"\x0ereply_messages\x18\x06 \x03(\tR\rreplyMessages\x12\x16\n" +
	"\x06stream\x18\a \x01(\tR\x06stream\x126\n" +
	"\bconsumer\x18\b \x01(\v2\x1a.nats.asyncapi.v1.ConsumerR\bconsumer\x123\n" +
	"\apublish\x18\t \x01(\v2\x19.nats.asyncapi.v1.PublishR\apublish\"\xc2\x01\n" +
	"\aPublish\x12\x15\n" +
	"\x03ack\x18\x01 \x01(\bH\x00R\x03ack\x88\x01\x01\x12\x15\n" +
	"\x06msg_id\x18\x02 \x01(\bR\x05msgId\x120\n" +
	"\x06expect\x18\x03 \x03(\x0e2\x18.nats.asyncapi.v1.ExpectR\x06expect\x12\x10\n" +
	"\x03ttl\x18\x04 \x01(\bR\x03ttl\x12!\n" +
	"\fatomic_batch\x18\x05 \x01(\bR\vatomicBatch\x12\x1a\n" +
	"\bschedule\x18\x06 \x01(\bR\bscheduleB\x06\n" +
	"\x04_ack\"@\n" +
	"\aMessage\x12\x18\n" +
	"\asubject\x18\x01 \x01(\tR\asubject\x12\x1b\n" +
	"\tkv_bucket\x18\x02 \x01(\tR\bkvBucket\"\x87\f\n" +
	"\x06Stream\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1a\n" +
	"\bsubjects\x18\x03 \x03(\tR\bsubjects\x129\n" +
	"\tretention\x18\x04 \x01(\x0e2\x1b.nats.asyncapi.v1.RetentionR\tretention\x123\n" +
	"\astorage\x18\x05 \x01(\x0e2\x19.nats.asyncapi.v1.StorageR\astorage\x12\x1a\n" +
	"\breplicas\x18\x06 \x01(\x05R\breplicas\x12#\n" +
	"\rmax_consumers\x18\a \x01(\x05R\fmaxConsumers\x12\x19\n" +
	"\bmax_msgs\x18\b \x01(\x03R\amaxMsgs\x12\x1b\n" +
	"\tmax_bytes\x18\t \x01(\tR\bmaxBytes\x12\x17\n" +
	"\amax_age\x18\n" +
	" \x01(\tR\x06maxAge\x12/\n" +
	"\x14max_msgs_per_subject\x18\v \x01(\x03R\x11maxMsgsPerSubject\x12 \n" +
	"\fmax_msg_size\x18\f \x01(\tR\n" +
	"maxMsgSize\x123\n" +
	"\adiscard\x18\r \x01(\x0e2\x19.nats.asyncapi.v1.DiscardR\adiscard\x125\n" +
	"\x17discard_new_per_subject\x18\x0e \x01(\bR\x14discardNewPerSubject\x12)\n" +
	"\x10duplicate_window\x18\x0f \x01(\tR\x0fduplicateWindow\x12\x15\n" +
	"\x06no_ack\x18\x10 \x01(\bR\x05noAck\x12!\n" +
	"\fallow_direct\x18\x11 \x01(\bR\vallowDirect\x12#\n" +
	"\rmirror_direct\x18\x12 \x01(\bR\fmirrorDirect\x12*\n" +
	"\x11allow_rollup_hdrs\x18\x13 \x01(\bR\x0fallowRollupHdrs\x12\x1f\n" +
	"\vdeny_delete\x18\x14 \x01(\bR\n" +
	"denyDelete\x12\x1d\n" +
	"\n" +
	"deny_purge\x18\x15 \x01(\bR\tdenyPurge\x12?\n" +
	"\vcompression\x18\x16 \x01(\x0e2\x1d.nats.asyncapi.v1.CompressionR\vcompression\x12\x1b\n" +
	"\tfirst_seq\x18\x17 \x01(\x04R\bfirstSeq\x129\n" +
	"\tplacement\x18\x18 \x01(\v2\x1b.nats.asyncapi.v1.PlacementR\tplacement\x126\n" +
	"\x06mirror\x18\x19 \x01(\v2\x1e.nats.asyncapi.v1.StreamSourceR\x06mirror\x128\n" +
	"\asources\x18\x1a \x03(\v2\x1e.nats.asyncapi.v1.StreamSourceR\asources\x129\n" +
	"\trepublish\x18\x1b \x01(\v2\x1b.nats.asyncapi.v1.RepublishR\trepublish\x12O\n" +
	"\x11subject_transform\x18\x1c \x01(\v2\".nats.asyncapi.v1.SubjectTransformR\x10subjectTransform\x12B\n" +
	"\bmetadata\x18\x1d \x03(\v2&.nats.asyncapi.v1.Stream.MetadataEntryR\bmetadata\x12\"\n" +
	"\rallow_msg_ttl\x18\x1e \x01(\bR\vallowMsgTtl\x129\n" +
	"\x19subject_delete_marker_ttl\x18\x1f \x01(\tR\x16subjectDeleteMarkerTtl\x12!\n" +
	"\fallow_atomic\x18  \x01(\bR\vallowAtomic\x12*\n" +
	"\x11allow_msg_counter\x18! \x01(\bR\x0fallowMsgCounter\x12.\n" +
	"\x13allow_msg_schedules\x18\" \x01(\bR\x11allowMsgSchedules\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"W\n" +
	"\tPlacement\x12\x18\n" +
	"\acluster\x18\x01 \x01(\tR\acluster\x12\x12\n" +
	"\x04tags\x18\x02 \x03(\tR\x04tags\x12\x1c\n" +
	"\tpreferred\x18\x03 \x01(\tR\tpreferred\"\xe6\x02\n" +
	"\fStreamSource\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\"\n" +
	"\ropt_start_seq\x18\x02 \x01(\x04R\voptStartSeq\x12$\n" +
	"\x0eopt_start_time\x18\x03 \x01(\tR\foptStartTime\x12%\n" +
	"\x0efilter_subject\x18\x04 \x01(\tR\rfilterSubject\x12Q\n" +
	"\x12subject_transforms\x18\x05 \x03(\v2\".nats.asyncapi.v1.SubjectTransformR\x11subjectTransforms\x12.\n" +
	"\x13external_api_prefix\x18\x06 \x01(\tR\x11externalApiPrefix\x126\n" +
	"\x17external_deliver_prefix\x18\a \x01(\tR\x15externalDeliverPrefix\x12\x16\n" +
	"\x06domain\x18\b \x01(\tR\x06domain\"8\n" +
	"\x10SubjectTransform\x12\x10\n" +
	"\x03src\x18\x01 \x01(\tR\x03src\x12\x12\n" +
	"\x04dest\x18\x02 \x01(\tR\x04dest\"T\n" +
	"\tRepublish\x12\x10\n" +
	"\x03src\x18\x01 \x01(\tR\x03src\x12\x12\n" +
	"\x04dest\x18\x02 \x01(\tR\x04dest\x12!\n" +
	"\fheaders_only\x18\x03 \x01(\bR\vheadersOnly\"\xf5\n" +
	"\n" +
	"\bConsumer\x12\x18\n" +
	"\adurable\x18\x01 \x01(\tR\adurable\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x122\n" +
	"\x04kind\x18\x04 \x01(\x0e2\x1e.nats.asyncapi.v1.ConsumerKindR\x04kind\x12F\n" +
	"\x0edeliver_policy\x18\x05 \x01(\x0e2\x1f.nats.asyncapi.v1.DeliverPolicyR\rdeliverPolicy\x12\"\n" +
	"\ropt_start_seq\x18\x06 \x01(\x04R\voptStartSeq\x12$\n" +
	"\x0eopt_start_time\x18\a \x01(\tR\foptStartTime\x12:\n" +
	"\n" +
	"ack_policy\x18\b \x01(\x0e2\x1b.nats.asyncapi.v1.AckPolicyR\tackPolicy\x12\x19\n" +
	"\back_wait\x18\t \x01(\tR\aackWait\x12\x1f\n" +
	"\vmax_deliver\x18\n" +
	" \x01(\x05R\n" +
	"maxDeliver\x12\x18\n" +
	"\abackoff\x18\v \x03(\tR\abackoff\x12'\n" +
	"\x0ffilter_subjects\x18\f \x03(\tR\x0efilterSubjects\x12C\n" +
	"\rreplay_policy\x18\r \x01(\x0e2\x1e.nats.asyncapi.v1.ReplayPolicyR\freplayPolicy\x12$\n" +
	"\x0erate_limit_bps\x18\x0e \x01(\x04R\frateLimitBps\x12\x1f\n" +
	"\vsample_freq\x18\x0f \x01(\tR\n" +
	"sampleFreq\x12\x1f\n" +
	"\vmax_waiting\x18\x10 \x01(\x05R\n" +
	"maxWaiting\x12&\n" +
	"\x0fmax_ack_pending\x18\x11 \x01(\x05R\rmaxAckPending\x12!\n" +
	"\fheaders_only\x18\x12 \x01(\bR\vheadersOnly\x12\x1b\n" +
	"\tmax_batch\x18\x13 \x01(\x05R\bmaxBatch\x12\x1f\n" +
	"\vmax_expires\x18\x14 \x01(\tR\n" +
	"maxExpires\x12\x1b\n" +
	"\tmax_bytes\x18\x15 \x01(\tR\bmaxBytes\x12-\n" +
	"\x12inactive_threshold\x18\x16 \x01(\tR\x11inactiveThreshold\x12\x1a\n" +
	"\breplicas\x18\x17 \x01(\x05R\breplicas\x12\x1f\n" +
	"\vmem_storage\x18\x18 \x01(\bR\n" +
	"memStorage\x12D\n" +
	"\bmetadata\x18\x19 \x03(\v2(.nats.asyncapi.v1.Consumer.MetadataEntryR\bmetadata\x12'\n" +
	"\x0fdeliver_subject\x18\x1a \x01(\tR\x0edeliverSubject\x12#\n" +
	"\rdeliver_group\x18\x1b \x01(\tR\fdeliverGroup\x12!\n" +
	"\fflow_control\x18\x1c \x01(\bR\vflowControl\x12%\n" +
	"\x0eidle_heartbeat\x18\x1d \x01(\tR\ridleHeartbeat\x12'\n" +
	"\x0fpriority_groups\x18\x1e \x03(\tR\x0epriorityGroups\x12I\n" +
	"\x0fpriority_policy\x18\x1f \x01(\x0e2 .nats.asyncapi.v1.PriorityPolicyR\x0epriorityPolicy\x12)\n" +
	"\x10priority_timeout\x18  \x01(\tR\x0fpriorityTimeout\x12\x1f\n" +
	"\vpause_until\x18! \x01(\tR\n" +
	"pauseUntil\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xc7\x05\n" +
	"\x0eKeyValueBucket\x12\x16\n" +
	"\x06bucket\x18\x01 \x01(\tR\x06bucket\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12$\n" +
	"\x0emax_value_size\x18\x03 \x01(\tR\fmaxValueSize\x12\x18\n" +
	"\ahistory\x18\x04 \x01(\x05R\ahistory\x12\x10\n" +
	"\x03ttl\x18\x05 \x01(\tR\x03ttl\x12\x1b\n" +
	"\tmax_bytes\x18\x06 \x01(\tR\bmaxBytes\x123\n" +
	"\astorage\x18\a \x01(\x0e2\x19.nats.asyncapi.v1.StorageR\astorage\x12\x1a\n" +
	"\breplicas\x18\b \x01(\x05R\breplicas\x129\n" +
	"\tplacement\x18\t \x01(\v2\x1b.nats.asyncapi.v1.PlacementR\tplacement\x129\n" +
	"\trepublish\x18\n" +
	" \x01(\v2\x1b.nats.asyncapi.v1.RepublishR\trepublish\x126\n" +
	"\x06mirror\x18\v \x01(\v2\x1e.nats.asyncapi.v1.StreamSourceR\x06mirror\x128\n" +
	"\asources\x18\f \x03(\v2\x1e.nats.asyncapi.v1.StreamSourceR\asources\x12 \n" +
	"\vcompression\x18\r \x01(\bR\vcompression\x12(\n" +
	"\x10limit_marker_ttl\x18\x0e \x01(\tR\x0elimitMarkerTtl\x12J\n" +
	"\bmetadata\x18\x0f \x03(\v2..nats.asyncapi.v1.KeyValueBucket.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xaa\x03\n" +
	"\vObjectStore\x12\x16\n" +
	"\x06bucket\x18\x01 \x01(\tR\x06bucket\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x10\n" +
	"\x03ttl\x18\x03 \x01(\tR\x03ttl\x12\x1b\n" +
	"\tmax_bytes\x18\x04 \x01(\tR\bmaxBytes\x123\n" +
	"\astorage\x18\x05 \x01(\x0e2\x19.nats.asyncapi.v1.StorageR\astorage\x12\x1a\n" +
	"\breplicas\x18\x06 \x01(\x05R\breplicas\x129\n" +
	"\tplacement\x18\a \x01(\v2\x1b.nats.asyncapi.v1.PlacementR\tplacement\x12 \n" +
	"\vcompression\x18\b \x01(\bR\vcompression\x12G\n" +
	"\bmetadata\x18\t \x03(\v2+.nats.asyncapi.v1.ObjectStore.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01*\xad\x01\n" +
	"\bAuthType\x12\x19\n" +
	"\x15AUTH_TYPE_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17AUTH_TYPE_USER_PASSWORD\x10\x01\x12\x13\n" +
	"\x0fAUTH_TYPE_TOKEN\x10\x02\x12\x12\n" +
	"\x0eAUTH_TYPE_NKEY\x10\x03\x12\x11\n" +
	"\rAUTH_TYPE_JWT\x10\x04\x12\x11\n" +
	"\rAUTH_TYPE_TLS\x10\x05\x12\x1a\n" +
	"\x16AUTH_TYPE_AUTH_CALLOUT\x10\x06*i\n" +
	"\aPattern\x12\x17\n" +
	"\x13PATTERN_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15PATTERN_REQUEST_REPLY\x10\x01\x12\x13\n" +
	"\x0fPATTERN_PUBLISH\x10\x02\x12\x15\n" +
	"\x11PATTERN_SUBSCRIBE\x10\x03*\x87\x01\n" +
	"\x06Expect\x12\x16\n" +
	"\x12EXPECT_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rEXPECT_STREAM\x10\x01\x12\x18\n" +
	"\x14EXPECT_LAST_SEQUENCE\x10\x02\x12 \n" +
	"\x1cEXPECT_LAST_SUBJECT_SEQUENCE\x10\x03\x12\x16\n" +
	"\x12EXPECT_LAST_MSG_ID\x10\x04*n\n" +
	"\tRetention\x12\x19\n" +
	"\x15RETENTION_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10RETENTION_LIMITS\x10\x01\x12\x16\n" +
	"\x12RETENTION_INTEREST\x10\x02\x12\x18\n" +
	"\x14RETENTION_WORK_QUEUE\x10\x03*H\n" +
	"\aStorage\x12\x17\n" +
	"\x13STORAGE_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fSTORAGE_FILE\x10\x01\x12\x12\n" +
	"\x0eSTORAGE_MEMORY\x10\x02*D\n" +
	"\aDiscard\x12\x17\n" +
	"\x13DISCARD_UNSPECIFIED\x10\x00\x12\x0f\n" +
	"\vDISCARD_OLD\x10\x01\x12\x0f\n" +
	"\vDISCARD_NEW\x10\x02*T\n" +
	"\vCompression\x12\x1b\n" +
	"\x17COMPRESSION_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10COMPRESSION_NONE\x10\x01\x12\x12\n" +
	"\x0eCOMPRESSION_S2\x10\x02*x\n" +
	"\fConsumerKind\x12\x1d\n" +
	"\x19CONSUMER_KIND_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12CONSUMER_KIND_PULL\x10\x01\x12\x16\n" +
	"\x12CONSUMER_KIND_PUSH\x10\x02\x12\x19\n" +
	"\x15CONSUMER_KIND_ORDERED\x10\x03*\xe5\x01\n" +
	"\rDeliverPolicy\x12\x1e\n" +
	"\x1aDELIVER_POLICY_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12DELIVER_POLICY_ALL\x10\x01\x12\x17\n" +
	"\x13DELIVER_POLICY_LAST\x10\x02\x12\x16\n" +
	"\x12DELIVER_POLICY_NEW\x10\x03\x12$\n" +
	" DELIVER_POLICY_BY_START_SEQUENCE\x10\x04\x12 \n" +
	"\x1cDELIVER_POLICY_BY_START_TIME\x10\x05\x12#\n" +
	"\x1fDELIVER_POLICY_LAST_PER_SUBJECT\x10\x06*i\n" +
	"\tAckPolicy\x12\x1a\n" +
	"\x16ACK_POLICY_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fACK_POLICY_NONE\x10\x01\x12\x12\n" +
	"\x0eACK_POLICY_ALL\x10\x02\x12\x17\n" +
	"\x13ACK_POLICY_EXPLICIT\x10\x03*d\n" +
	"\fReplayPolicy\x12\x1d\n" +
	"\x19REPLAY_POLICY_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15REPLAY_POLICY_INSTANT\x10\x01\x12\x1a\n" +
	"\x16REPLAY_POLICY_ORIGINAL\x10\x02*\xad\x01\n" +
	"\x0ePriorityPolicy\x12\x1f\n" +
	"\x1bPRIORITY_POLICY_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14PRIORITY_POLICY_NONE\x10\x01\x12\x1c\n" +
	"\x18PRIORITY_POLICY_OVERFLOW\x10\x02\x12!\n" +
	"\x1dPRIORITY_POLICY_PINNED_CLIENT\x10\x03\x12\x1f\n" +
	"\x1bPRIORITY_POLICY_PRIORITIZED\x10\x04:V\n" +
	"\bdocument\x12\x1c.google.protobuf.FileOptions\x18\xc6\xc7\x03 \x01(\v2\x1a.nats.asyncapi.v1.DocumentR\bdocument:V\n" +
	"\aservice\x12\x1f.google.protobuf.ServiceOptions\x18\xc6\xc7\x03 \x01(\v2\x19.nats.asyncapi.v1.ServiceR\aservice:[\n" +
	"\toperation\x12\x1e.google.protobuf.MethodOptions\x18\xc6\xc7\x03 \x01(\v2\x1b.nats.asyncapi.v1.OperationR\toperation:V\n" +
	"\amessage\x12\x1f.google.protobuf.MessageOptions\x18\xc6\xc7\x03 \x01(\v2\x19.nats.asyncapi.v1.MessageR\amessageBEZCgithub.com/AustinZhu/protoc-gen-asyncapi/pb/nats/asyncapi/v1;natsv1b\x06proto3"

var (
	file_nats_asyncapi_v1_annotations_proto_rawDescOnce sync.Once
	file_nats_asyncapi_v1_annotations_proto_rawDescData []byte
)

func file_nats_asyncapi_v1_annotations_proto_rawDescGZIP() []byte {
	file_nats_asyncapi_v1_annotations_proto_rawDescOnce.Do(func() {
		file_nats_asyncapi_v1_annotations_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_nats_asyncapi_v1_annotations_proto_rawDesc), len(file_nats_asyncapi_v1_annotations_proto_rawDesc)))
	})
	return file_nats_asyncapi_v1_annotations_proto_rawDescData
}

var file_nats_asyncapi_v1_annotations_proto_enumTypes = make([]protoimpl.EnumInfo, 12)
var file_nats_asyncapi_v1_annotations_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_nats_asyncapi_v1_annotations_proto_goTypes = []any{
	(AuthType)(0),                       // 0: nats.asyncapi.v1.AuthType
	(Pattern)(0),                        // 1: nats.asyncapi.v1.Pattern
	(Expect)(0),                         // 2: nats.asyncapi.v1.Expect
	(Retention)(0),                      // 3: nats.asyncapi.v1.Retention
	(Storage)(0),                        // 4: nats.asyncapi.v1.Storage
	(Discard)(0),                        // 5: nats.asyncapi.v1.Discard
	(Compression)(0),                    // 6: nats.asyncapi.v1.Compression
	(ConsumerKind)(0),                   // 7: nats.asyncapi.v1.ConsumerKind
	(DeliverPolicy)(0),                  // 8: nats.asyncapi.v1.DeliverPolicy
	(AckPolicy)(0),                      // 9: nats.asyncapi.v1.AckPolicy
	(ReplayPolicy)(0),                   // 10: nats.asyncapi.v1.ReplayPolicy
	(PriorityPolicy)(0),                 // 11: nats.asyncapi.v1.PriorityPolicy
	(*Document)(nil),                    // 12: nats.asyncapi.v1.Document
	(*Server)(nil),                      // 13: nats.asyncapi.v1.Server
	(*Auth)(nil),                        // 14: nats.asyncapi.v1.Auth
	(*Service)(nil),                     // 15: nats.asyncapi.v1.Service
	(*Micro)(nil),                       // 16: nats.asyncapi.v1.Micro
	(*Operation)(nil),                   // 17: nats.asyncapi.v1.Operation
	(*Publish)(nil),                     // 18: nats.asyncapi.v1.Publish
	(*Message)(nil),                     // 19: nats.asyncapi.v1.Message
	(*Stream)(nil),                      // 20: nats.asyncapi.v1.Stream
	(*Placement)(nil),                   // 21: nats.asyncapi.v1.Placement
	(*StreamSource)(nil),                // 22: nats.asyncapi.v1.StreamSource
	(*SubjectTransform)(nil),            // 23: nats.asyncapi.v1.SubjectTransform
	(*Republish)(nil),                   // 24: nats.asyncapi.v1.Republish
	(*Consumer)(nil),                    // 25: nats.asyncapi.v1.Consumer
	(*KeyValueBucket)(nil),              // 26: nats.asyncapi.v1.KeyValueBucket
	(*ObjectStore)(nil),                 // 27: nats.asyncapi.v1.ObjectStore
	nil,                                 // 28: nats.asyncapi.v1.Micro.MetadataEntry
	nil,                                 // 29: nats.asyncapi.v1.Stream.MetadataEntry
	nil,                                 // 30: nats.asyncapi.v1.Consumer.MetadataEntry
	nil,                                 // 31: nats.asyncapi.v1.KeyValueBucket.MetadataEntry
	nil,                                 // 32: nats.asyncapi.v1.ObjectStore.MetadataEntry
	(*descriptorpb.FileOptions)(nil),    // 33: google.protobuf.FileOptions
	(*descriptorpb.ServiceOptions)(nil), // 34: google.protobuf.ServiceOptions
	(*descriptorpb.MethodOptions)(nil),  // 35: google.protobuf.MethodOptions
	(*descriptorpb.MessageOptions)(nil), // 36: google.protobuf.MessageOptions
}
var file_nats_asyncapi_v1_annotations_proto_depIdxs = []int32{
	13, // 0: nats.asyncapi.v1.Document.servers:type_name -> nats.asyncapi.v1.Server
	14, // 1: nats.asyncapi.v1.Document.auth:type_name -> nats.asyncapi.v1.Auth
	20, // 2: nats.asyncapi.v1.Document.streams:type_name -> nats.asyncapi.v1.Stream
	26, // 3: nats.asyncapi.v1.Document.kv_buckets:type_name -> nats.asyncapi.v1.KeyValueBucket
	27, // 4: nats.asyncapi.v1.Document.object_stores:type_name -> nats.asyncapi.v1.ObjectStore
	0,  // 5: nats.asyncapi.v1.Auth.type:type_name -> nats.asyncapi.v1.AuthType
	16, // 6: nats.asyncapi.v1.Service.micro:type_name -> nats.asyncapi.v1.Micro
	28, // 7: nats.asyncapi.v1.Micro.metadata:type_name -> nats.asyncapi.v1.Micro.MetadataEntry
	1,  // 8: nats.asyncapi.v1.Operation.pattern:type_name -> nats.asyncapi.v1.Pattern
	25, // 9: nats.asyncapi.v1.Operation.consumer:type_name -> nats.asyncapi.v1.Consumer
	18, // 10: nats.asyncapi.v1.Operation.publish:type_name -> nats.asyncapi.v1.Publish
	2,  // 11: nats.asyncapi.v1.Publish.expect:type_name -> nats.asyncapi.v1.Expect
	3,  // 12: nats.asyncapi.v1.Stream.retention:type_name -> nats.asyncapi.v1.Retention
	4,  // 13: nats.asyncapi.v1.Stream.storage:type_name -> nats.asyncapi.v1.Storage
	5,  // 14: nats.asyncapi.v1.Stream.discard:type_name -> nats.asyncapi.v1.Discard
	6,  // 15: nats.asyncapi.v1.Stream.compression:type_name -> nats.asyncapi.v1.Compression
	21, // 16: nats.asyncapi.v1.Stream.placement:type_name -> nats.asyncapi.v1.Placement
	22, // 17: nats.asyncapi.v1.Stream.mirror:type_name -> nats.asyncapi.v1.StreamSource
	22, // 18: nats.asyncapi.v1.Stream.sources:type_name -> nats.asyncapi.v1.StreamSource
	24, // 19: nats.asyncapi.v1.Stream.republish:type_name -> nats.asyncapi.v1.Republish
	23, // 20: nats.asyncapi.v1.Stream.subject_transform:type_name -> nats.asyncapi.v1.SubjectTransform
	29, // 21: nats.asyncapi.v1.Stream.metadata:type_name -> nats.asyncapi.v1.Stream.MetadataEntry
	23, // 22: nats.asyncapi.v1.StreamSource.subject_transforms:type_name -> nats.asyncapi.v1.SubjectTransform
	7,  // 23: nats.asyncapi.v1.Consumer.kind:type_name -> nats.asyncapi.v1.ConsumerKind
	8,  // 24: nats.asyncapi.v1.Consumer.deliver_policy:type_name -> nats.asyncapi.v1.DeliverPolicy
	9,  // 25: nats.asyncapi.v1.Consumer.ack_policy:type_name -> nats.asyncapi.v1.AckPolicy
	10, // 26: nats.asyncapi.v1.Consumer.replay_policy:type_name -> nats.asyncapi.v1.ReplayPolicy
	30, // 27: nats.asyncapi.v1.Consumer.metadata:type_name -> nats.asyncapi.v1.Consumer.MetadataEntry
	11, // 28: nats.asyncapi.v1.Consumer.priority_policy:type_name -> nats.asyncapi.v1.PriorityPolicy
	4,  // 29: nats.asyncapi.v1.KeyValueBucket.storage:type_name -> nats.asyncapi.v1.Storage
	21, // 30: nats.asyncapi.v1.KeyValueBucket.placement:type_name -> nats.asyncapi.v1.Placement
	24, // 31: nats.asyncapi.v1.KeyValueBucket.republish:type_name -> nats.asyncapi.v1.Republish
	22, // 32: nats.asyncapi.v1.KeyValueBucket.mirror:type_name -> nats.asyncapi.v1.StreamSource
	22, // 33: nats.asyncapi.v1.KeyValueBucket.sources:type_name -> nats.asyncapi.v1.StreamSource
	31, // 34: nats.asyncapi.v1.KeyValueBucket.metadata:type_name -> nats.asyncapi.v1.KeyValueBucket.MetadataEntry
	4,  // 35: nats.asyncapi.v1.ObjectStore.storage:type_name -> nats.asyncapi.v1.Storage
	21, // 36: nats.asyncapi.v1.ObjectStore.placement:type_name -> nats.asyncapi.v1.Placement
	32, // 37: nats.asyncapi.v1.ObjectStore.metadata:type_name -> nats.asyncapi.v1.ObjectStore.MetadataEntry
	33, // 38: nats.asyncapi.v1.document:extendee -> google.protobuf.FileOptions
	34, // 39: nats.asyncapi.v1.service:extendee -> google.protobuf.ServiceOptions
	35, // 40: nats.asyncapi.v1.operation:extendee -> google.protobuf.MethodOptions
	36, // 41: nats.asyncapi.v1.message:extendee -> google.protobuf.MessageOptions
	12, // 42: nats.asyncapi.v1.document:type_name -> nats.asyncapi.v1.Document
	15, // 43: nats.asyncapi.v1.service:type_name -> nats.asyncapi.v1.Service
	17, // 44: nats.asyncapi.v1.operation:type_name -> nats.asyncapi.v1.Operation
	19, // 45: nats.asyncapi.v1.message:type_name -> nats.asyncapi.v1.Message
	46, // [46:46] is the sub-list for method output_type
	46, // [46:46] is the sub-list for method input_type
	42, // [42:46] is the sub-list for extension type_name
	38, // [38:42] is the sub-list for extension extendee
	0,  // [0:38] is the sub-list for field type_name
}

func init() { file_nats_asyncapi_v1_annotations_proto_init() }
func file_nats_asyncapi_v1_annotations_proto_init() {
	if File_nats_asyncapi_v1_annotations_proto != nil {
		return
	}
	file_nats_asyncapi_v1_annotations_proto_msgTypes[6].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_nats_asyncapi_v1_annotations_proto_rawDesc), len(file_nats_asyncapi_v1_annotations_proto_rawDesc)),
			NumEnums:      12,
			NumMessages:   21,
			NumExtensions: 4,
			NumServices:   0,
		},
		GoTypes:           file_nats_asyncapi_v1_annotations_proto_goTypes,
		DependencyIndexes: file_nats_asyncapi_v1_annotations_proto_depIdxs,
		EnumInfos:         file_nats_asyncapi_v1_annotations_proto_enumTypes,
		MessageInfos:      file_nats_asyncapi_v1_annotations_proto_msgTypes,
		ExtensionInfos:    file_nats_asyncapi_v1_annotations_proto_extTypes,
	}.Build()
	File_nats_asyncapi_v1_annotations_proto = out.File
	file_nats_asyncapi_v1_annotations_proto_goTypes = nil
	file_nats_asyncapi_v1_annotations_proto_depIdxs = nil
}
