// Protocol-neutral AsyncAPI 3 annotations, shared by every protoc-gen-asyncapi
// protocol (NATS, Temporal, ...).
//
// Every annotation is optional. The generators infer channels, operations
// and payload schemas from services and messages; these annotations add the
// parts of an AsyncAPI document that cannot be inferred (info, servers,
// security) and override or extend what is inferred (summaries, tags,
// examples, ...). Protocol specifics (NATS subjects, Temporal workflow kinds,
// ...) live in each protocol's own annotation package.
//
// Descriptions default to the leading comments of the annotated element.
//
// Escape hatches: every object that AsyncAPI lets carry bindings or
// specification extensions has
//   - `bindings`: protocol bindings as JSON, keyed by protocol, e.g.
//     bindings: [{protocol: "kafka", json: '{"bindingVersion": "0.5.0"}'}]
//   - `extensions`: specification extensions as JSON, keyed by "x-..." name,
//     e.g. extensions: [{key: "x-team", value: '"orders"'}]
// so any official or custom binding can be expressed without new
// annotations.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: asyncapi/v3/annotations.proto

package asyncapiv3

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SecuritySchemeType int32

const (
	SecuritySchemeType_SECURITY_SCHEME_TYPE_UNSPECIFIED           SecuritySchemeType = 0
	SecuritySchemeType_SECURITY_SCHEME_TYPE_USER_PASSWORD         SecuritySchemeType = 1
	SecuritySchemeType_SECURITY_SCHEME_TYPE_API_KEY               SecuritySchemeType = 2
	SecuritySchemeType_SECURITY_SCHEME_TYPE_X509                  SecuritySchemeType = 3
	SecuritySchemeType_SECURITY_SCHEME_TYPE_SYMMETRIC_ENCRYPTION  SecuritySchemeType = 4
	SecuritySchemeType_SECURITY_SCHEME_TYPE_ASYMMETRIC_ENCRYPTION SecuritySchemeType = 5
	SecuritySchemeType_SECURITY_SCHEME_TYPE_HTTP_API_KEY          SecuritySchemeType = 6
	SecuritySchemeType_SECURITY_SCHEME_TYPE_HTTP                  SecuritySchemeType = 7
	SecuritySchemeType_SECURITY_SCHEME_TYPE_OAUTH2                SecuritySchemeType = 8
	SecuritySchemeType_SECURITY_SCHEME_TYPE_OPEN_ID_CONNECT       SecuritySchemeType = 9
	SecuritySchemeType_SECURITY_SCHEME_TYPE_PLAIN                 SecuritySchemeType = 10
	SecuritySchemeType_SECURITY_SCHEME_TYPE_SCRAM_SHA256          SecuritySchemeType = 11
	SecuritySchemeType_SECURITY_SCHEME_TYPE_SCRAM_SHA512          SecuritySchemeType = 12
	SecuritySchemeType_SECURITY_SCHEME_TYPE_GSSAPI                SecuritySchemeType = 13
)

// Enum value maps for SecuritySchemeType.
var (
	SecuritySchemeType_name = map[int32]string{
		0:  "SECURITY_SCHEME_TYPE_UNSPECIFIED",
		1:  "SECURITY_SCHEME_TYPE_USER_PASSWORD",
		2:  "SECURITY_SCHEME_TYPE_API_KEY",
		3:  "SECURITY_SCHEME_TYPE_X509",
		4:  "SECURITY_SCHEME_TYPE_SYMMETRIC_ENCRYPTION",
		5:  "SECURITY_SCHEME_TYPE_ASYMMETRIC_ENCRYPTION",
		6:  "SECURITY_SCHEME_TYPE_HTTP_API_KEY",
		7:  "SECURITY_SCHEME_TYPE_HTTP",
		8:  "SECURITY_SCHEME_TYPE_OAUTH2",
		9:  "SECURITY_SCHEME_TYPE_OPEN_ID_CONNECT",
		10: "SECURITY_SCHEME_TYPE_PLAIN",
		11: "SECURITY_SCHEME_TYPE_SCRAM_SHA256",
		12: "SECURITY_SCHEME_TYPE_SCRAM_SHA512",
		13: "SECURITY_SCHEME_TYPE_GSSAPI",
	}
	SecuritySchemeType_value = map[string]int32{
		"SECURITY_SCHEME_TYPE_UNSPECIFIED":           0,
		"SECURITY_SCHEME_TYPE_USER_PASSWORD":         1,
		"SECURITY_SCHEME_TYPE_API_KEY":               2,
		"SECURITY_SCHEME_TYPE_X509":                  3,
		"SECURITY_SCHEME_TYPE_SYMMETRIC_ENCRYPTION":  4,
		"SECURITY_SCHEME_TYPE_ASYMMETRIC_ENCRYPTION": 5,
		"SECURITY_SCHEME_TYPE_HTTP_API_KEY":          6,
		"SECURITY_SCHEME_TYPE_HTTP":                  7,
		"SECURITY_SCHEME_TYPE_OAUTH2":                8,
		"SECURITY_SCHEME_TYPE_OPEN_ID_CONNECT":       9,
		"SECURITY_SCHEME_TYPE_PLAIN":                 10,
		"SECURITY_SCHEME_TYPE_SCRAM_SHA256":          11,
		"SECURITY_SCHEME_TYPE_SCRAM_SHA512":          12,
		"SECURITY_SCHEME_TYPE_GSSAPI":                13,
	}
)

func (x SecuritySchemeType) Enum() *SecuritySchemeType {
	p := new(SecuritySchemeType)
	*p = x
	return p
}

func (x SecuritySchemeType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SecuritySchemeType) Descriptor() protoreflect.EnumDescriptor {
	return file_asyncapi_v3_annotations_proto_enumTypes[0].Descriptor()
}

func (SecuritySchemeType) Type() protoreflect.EnumType {
	return &file_asyncapi_v3_annotations_proto_enumTypes[0]
}

func (x SecuritySchemeType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SecuritySchemeType.Descriptor instead.
func (SecuritySchemeType) EnumDescriptor() ([]byte, []int) {
	return file_asyncapi_v3_annotations_proto_rawDescGZIP(), []int{0}
}

type Document struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Info  *Info                  `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	// Document id, e.g. "urn:acme:orders".
	Id string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	// Default content type of messages. Defaults to application/json
	// (application/protobuf with payload=protobuf).
	DefaultContentType string            `protobuf:"bytes,3,opt,name=default_content_type,json=defaultContentType,proto3" json:"default_content_type,omitempty"`
	Servers            []*Server         `protobuf:"bytes,4,rep,name=servers,proto3" json:"servers,omitempty"`
	SecuritySchemes    []*SecurityScheme `protobuf:"bytes,5,rep,name=security_schemes,json=securitySchemes,proto3" json:"security_schemes,omitempty"`
	// Tags declared at document level (info.tags).
	Tags         []*Tag        `protobuf:"bytes,6,rep,name=tags,proto3" json:"tags,omitempty"`
	ExternalDocs *ExternalDocs `protobuf:"bytes,7,opt,name=external_docs,json=externalDocs,proto3" json:"external_docs,omitempty"`
	// Specification extensions of the document root.
	Extensions    map[string]string `protobuf:"bytes,8,rep,name=extensions,proto3" json:"extensions,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Document) Reset() {
	*x = Document{}
	mi := &file_asyncapi_v3_annotations_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Document) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Document) ProtoMessage() {}

func (x *Document) ProtoReflect() protoreflect.Message {
	mi := &file_asyncapi_v3_annotations_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Document.ProtoReflect.Descriptor instead.
func (*Document) Descriptor() ([]byte, []int) {
	return file_asyncapi_v3_annotations_proto_rawDescGZIP(), []int{0}
}

func (x *Document) GetInfo() *Info {
	if x != nil {
		return x.Info
	}
	return nil
}

func (x *Document) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Document) GetDefaultContentType() string {
	if x != nil {
		return x.DefaultContentType
	}
	return ""
}

func (x *Document) GetServers() []*Server {
	if x != nil {
		return x.Servers
	}
	return nil
}

func (x *Document) GetSecuritySchemes() []*SecurityScheme {
	if x != nil {
		return x.SecuritySchemes
	}
	return nil
}

func (x *Document) GetTags() []*Tag {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Document) GetExternalDocs() *ExternalDocs {
	if x != nil {
		return x.ExternalDocs
	}
	return nil
}

func (x *Document) GetExtensions() map[string]string {
	if x != nil {
		return x.Extensions
	}
	return nil
}

// Binding is a protocol binding object written as JSON.
type Binding struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Protocol key, e.g. "kafka", "amqp", "mqtt", "ws", "ros2", or "x-..." for
	// an unofficial binding.
	Protocol string `protobuf:"bytes,1,opt,name=protocol,proto3" json:"protocol,omitempty"`
	// The binding object as JSON, e.g. '{"bindingVersion": "0.5.0"}'.
	Json          string `protobuf:"bytes,2,opt,name=json,proto3" json:"json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Binding) Reset() {
	*x = Binding{}
	mi := &file_asyncapi_v3_annotations_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Binding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Binding) ProtoMessage() {}

func (x *Binding) ProtoReflect() protoreflect.Message {
	mi := &file_asyncapi_v3_annotations_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Binding.ProtoReflect.Descriptor instead.
func (*Binding) Descriptor() ([]byte, []int) {
	return file_asyncapi_v3_annotations_proto_rawDescGZIP(), []int{1}
}

func (x *Binding) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *Binding) GetJson() string {
	if x != nil {
		return x.Json
	}
	return ""
}

type Info struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Defaults to the service name when the document has a single service,
	// else to the package name.
	Title string `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	// Defaults to 0.0.0; the `version` plugin option overrides it.
	Version string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	// Defaults to the comments of the `package` (or `syntax`) statement.
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	// Short summary, prepended to the description (AsyncAPI has no
	// info.summary).
	Summary        string            `protobuf:"bytes,4,opt,name=summary,proto3" json:"summary,omitempty"`
	TermsOfService string            `protobuf:"bytes,5,opt,name=terms_of_service,json=termsOfService,proto3" json:"terms_of_service,omitempty"`
	Contact        *Contact          `protobuf:"bytes,6,opt,name=contact,proto3" json:"contact,omitempty"`
	License        *License          `protobuf:"bytes,7,opt,name=license,proto3" json:"license,omitempty"`
	Extensions     map[string]string `protobuf:"bytes,8,rep,name=extensions,proto3" json:"extensions,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Info) Reset() {
	*x = Info{}
	mi := &file_asyncapi_v3_annotations_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Info) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Info) ProtoMessage() {}

func (x *Info) ProtoReflect() protoreflect.Message {
	mi := &file_asyncapi_v3_annotations_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Info.ProtoReflect.Descriptor instead.
func (*Info) Descriptor() ([]byte, []int) {
	return file_asyncapi_v3_annotations_proto_rawDescGZIP(), []int{2}
}

func (x *Info) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Info) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Info) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Info) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *Info) GetTermsOfService() string {
	if x != nil {
		return x.TermsOfService
	}
	return ""
}

func (x *Info) GetContact() *Contact {
	if x != nil {
		return x.Contact
	}
	return nil
}

func (x *Info) GetLicense() *License {
	if x != nil {
		return x.License
	}
	return nil
}

func (x *Info) GetExtensions() map[string]string {
	if x != nil {
		return x.Extensions
	}
	return nil
}

type Contact struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Contact) Reset() {
	*x = Contact{}
	mi := &file_asyncapi_v3_annotations_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Contact) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Contact) ProtoMessage() {}

func (x *Contact) ProtoReflect() protoreflect.Message {
	mi := &file_asyncapi_v3_annotations_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Contact.ProtoReflect.Descriptor instead.
func (*Contact) Descriptor() ([]byte, []int) {
	return file_asyncapi_v3_annotations_proto_rawDescGZIP(), []int{3}
}

func (x *Contact) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Contact) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Contact) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type License struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required.
	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Url           string `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *License) Reset() {
	*x = License{}
	mi := &file_asyncapi_v3_annotations_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *License) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*License) ProtoMessage() {}

func (x *License) ProtoReflect() protoreflect.Message {
	mi := &file_asyncapi_v3_annotations_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use License.ProtoReflect.Descriptor instead.
func (*License) Descriptor() ([]byte, []int) {
	return file_asyncapi_v3_annotations_proto_rawDescGZIP(), []int{4}
}

func (x *License) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *License) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type Tag struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	ExternalDocs  *ExternalDocs          `protobuf:"bytes,3,opt,name=external_docs,json=externalDocs,proto3" json:"external_docs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tag) Reset() {
	*x = Tag{}
	mi := &file_asyncapi_v3_annotations_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tag) ProtoMessage() {}

func (x *Tag) ProtoReflect() protoreflect.Message {
	mi := &file_asyncapi_v3_annotations_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tag.ProtoReflect.Descriptor instead.
func (*Tag) Descriptor() ([]byte, []int) {
	return file_asyncapi_v3_annotations_proto_rawDescGZIP(), []int{5}
}

func (x *Tag) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Tag) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Tag) GetExternalDocs() *ExternalDocs {
	if x != nil {
		return x.ExternalDocs
	}
	return nil
}

type ExternalDocs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExternalDocs) Reset() {
	*x = ExternalDocs{}
	mi := &file_asyncapi_v3_annotations_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExternalDocs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExternalDocs) ProtoMessage() {}

func (x *ExternalDocs) ProtoReflect() protoreflect.Message {
	mi := &file_asyncapi_v3_annotations_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExternalDocs.ProtoReflect.Descriptor instead.
func (*ExternalDocs) Descriptor() ([]byte, []int) {
	return file_asyncapi_v3_annotations_proto_rawDescGZIP(), []int{6}
}

func (x *ExternalDocs) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *ExternalDocs) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type Server struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Key of the server in the document, e.g. "production". Required.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Host, optionally with port, e.g. "nats.example.com:4222". Required.
	Host string `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`
	// Protocol, e.g. "nats" or "temporal". Defaults to the protocol of the
	// generator when the document describes a single protocol.
	Protocol        string            `protobuf:"bytes,3,opt,name=protocol,proto3" json:"protocol,omitempty"`
	ProtocolVersion string            `protobuf:"bytes,4,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	Pathname        string            `protobuf:"bytes,5,opt,name=pathname,proto3" json:"pathname,omitempty"`
	Title           string            `protobuf:"bytes,6,opt,name=title,proto3" json:"title,omitempty"`
	Summary         string            `protobuf:"bytes,7,opt,name=summary,proto3" json:"summary,omitempty"`
	Description     string            `protobuf:"bytes,8,opt,name=description,proto3" json:"description,omitempty"`
	Variables       []*ServerVariable `protobuf:"bytes,9,rep,name=variables,proto3" json:"variables,omitempty"`
	// Names of security schemes required to connect.
	Security      []string          `protobuf:"bytes,10,rep,name=security,proto3" json:"security,omitempty"`
	Tags          []*Tag            `protobuf:"bytes,11,rep,name=tags,proto3" json:"tags,omitempty"`
	ExternalDocs  *ExternalDocs     `protobuf:"bytes,12,opt,name=external_docs,json=externalDocs,proto3" json:"external_docs,omitempty"`
	Bindings      []*Binding        `protobuf:"bytes,13,rep,name=bindings,proto3" json:"bindings,omitempty"`
	Extensions    map[string]string `protobuf:"bytes,14,rep,name=extensions,proto3" json:"extensions,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Server) Reset() {
	*x = Server{}
	mi := &file_asyncapi_v3_annotations_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server) ProtoMessage() {}

func (x *Server) ProtoReflect() protoreflect.Message {
	mi := &file_asyncapi_v3_annotations_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server.ProtoReflect.Descriptor instead.
func (*Server) Descriptor() ([]byte, []int) {
	return file_asyncapi_v3_annotations_proto_rawDescGZIP(), []int{7}
}

func (x *Server) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Server) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *Server) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *Server) GetProtocolVersion() string {
	if x != nil {
		return x.ProtocolVersion
	}
	return ""
}

func (x *Server) GetPathname() string {
	if x != nil {
		return x.Pathname
	}
	return ""
}

func (x *Server) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Server) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *Server) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Server) GetVariables() []*ServerVariable {
	if x != nil {
		return x.Variables
	}
	return nil
}

func (x *Server) GetSecurity() []string {
	if x != nil {
		return x.Security
	}
	return nil
}

func (x *Server) GetTags() []*Tag {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Server) GetExternalDocs() *ExternalDocs {
	if x != nil {
		return x.ExternalDocs
	}
	return nil
}

func (x *Server) GetBindings() []*Binding {
	if x != nil {
		return x.Bindings
	}
	return nil
}

func (x *Server) GetExtensions() map[string]string {
	if x != nil {
		return x.Extensions
	}
	return nil
}

type ServerVariable struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Enum          []string               `protobuf:"bytes,2,rep,name=enum,proto3" json:"enum,omitempty"`
	Default       string                 `protobuf:"bytes,3,opt,name=default,proto3" json:"default,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Examples      []string               `protobuf:"bytes,5,rep,name=examples,proto3" json:"examples,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerVariable) Reset() {
	*x = ServerVariable{}
	mi := &file_asyncapi_v3_annotations_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerVariable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerVariable) ProtoMessage() {}

func (x *ServerVariable) ProtoReflect() protoreflect.Message {
	mi := &file_asyncapi_v3_annotations_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerVariable.ProtoReflect.Descriptor instead.
func (*ServerVariable) Descriptor() ([]byte, []int) {
	return file_asyncapi_v3_annotations_proto_rawDescGZIP(), []int{8}
}

func (x *ServerVariable) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ServerVariable) GetEnum() []string {
	if x != nil {
		return x.Enum
	}
	return nil
}

func (x *ServerVariable) GetDefault() string {
	if x != nil {
		return x.Default
	}
	return ""
}

func (x *ServerVariable) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ServerVariable) GetExamples() []string {
	if x != nil {
		return x.Examples
	}
	return nil
}

// SecurityScheme mirrors the AsyncAPI Security Scheme Object.
type SecurityScheme struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Key of the scheme in components.securitySchemes. Required.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Required, unless a protocol annotation derives it (e.g. the NATS auth
	// type).
	Type        SecuritySchemeType `protobuf:"varint,2,opt,name=type,proto3,enum=asyncapi.v3.SecuritySchemeType" json:"type,omitempty"`
	Description string             `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	// apiKey: "user" or "password"; httpApiKey: "query", "header" or "cookie".
	In string `protobuf:"bytes,4,opt,name=in,proto3" json:"in,omitempty"`
	// httpApiKey: name of the header, query parameter or cookie.
	ParameterName string `protobuf:"bytes,5,opt,name=parameter_name,json=parameterName,proto3" json:"parameter_name,omitempty"`
	// http: e.g. "bearer" or "basic".
	Scheme string `protobuf:"bytes,6,opt,name=scheme,proto3" json:"scheme,omitempty"`
	// http bearer: e.g. "JWT".
	BearerFormat string `protobuf:"bytes,7,opt,name=bearer_format,json=bearerFormat,proto3" json:"bearer_format,omitempty"`
	// openIdConnect: OpenID Connect discovery URL.
	OpenIdConnectUrl string `protobuf:"bytes,8,opt,name=open_id_connect_url,json=openIdConnectUrl,proto3" json:"open_id_connect_url,omitempty"`
	// oauth2 / openIdConnect: scopes required.
	Scopes []string `protobuf:"bytes,9,rep,name=scopes,proto3" json:"scopes,omitempty"`
	// oauth2: supported flows.
	Flows         *OAuthFlows       `protobuf:"bytes,10,opt,name=flows,proto3" json:"flows,omitempty"`
	Extensions    map[string]string `protobuf:"bytes,11,rep,name=extensions,proto3" json:"extensions,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SecurityScheme) Reset() {
	*x = SecurityScheme{}
	mi := &file_asyncapi_v3_annotations_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecurityScheme) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecurityScheme) ProtoMessage() {}

func (x *SecurityScheme) ProtoReflect() protoreflect.Message {
	mi := &file_asyncapi_v3_annotations_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecurityScheme.ProtoReflect.Descriptor instead.
func (*SecurityScheme) Descriptor() ([]byte, []int) {
	return file_asyncapi_v3_annotations_proto_rawDescGZIP(), []int{9}
}

func (x *SecurityScheme) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SecurityScheme) GetType() SecuritySchemeType {
	if x != nil {
		return x.Type
	}
	return SecuritySchemeType_SECURITY_SCHEME_TYPE_UNSPECIFIED
}

func (x *SecurityScheme) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *SecurityScheme) GetIn() string {
	if x != nil {
		return x.In
	}
	return ""
}

func (x *SecurityScheme) GetParameterName() string {
	if x != nil {
		return x.ParameterName
	}
	return ""
}

func (x *SecurityScheme) GetScheme() string {
	if x != nil {
		return x.Scheme
	}
	return ""
}

func (x *SecurityScheme) GetBearerFormat() string {
	if x != nil {
		return x.BearerFormat
	}
	return ""
}

func (x *SecurityScheme) GetOpenIdConnectUrl() string {
	if x != nil {
		return x.OpenIdConnectUrl
	}
	return ""
}

func (x *SecurityScheme) GetScopes() []string {
	if x != nil {
		return x.Scopes
	}
	return nil
}

func (x *SecurityScheme) GetFlows() *OAuthFlows {
	if x != nil {
		return x.Flows
	}
	return nil
}

func (x *SecurityScheme) GetExtensions() map[string]string {
	if x != nil {
		return x.Extensions
	}
	return nil
}

type OAuthFlows struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Implicit          *OAuthFlow             `protobuf:"bytes,1,opt,name=implicit,proto3" json:"implicit,omitempty"`
	Password          *OAuthFlow             `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	ClientCredentials *OAuthFlow             `protobuf:"bytes,3,opt,name=client_credentials,json=clientCredentials,proto3" json:"client_credentials,omitempty"`
	AuthorizationCode *OAuthFlow             `protobuf:"bytes,4,opt,name=authorization_code,json=authorizationCode,proto3" json:"authorization_code,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *OAuthFlows) Reset() {
	*x = OAuthFlows{}
	mi := &file_asyncapi_v3_annotations_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OAuthFlows) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OAuthFlows) ProtoMessage() {}

func (x *OAuthFlows) ProtoReflect() protoreflect.Message {
	mi := &file_asyncapi_v3_annotations_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OAuthFlows.ProtoReflect.Descriptor instead.
func (*OAuthFlows) Descriptor() ([]byte, []int) {
	return file_asyncapi_v3_annotations_proto_rawDescGZIP(), []int{10}
}

func (x *OAuthFlows) GetImplicit() *OAuthFlow {
	if x != nil {
		return x.Implicit
	}
	return nil
}

func (x *OAuthFlows) GetPassword() *OAuthFlow {
	if x != nil {
		return x.Password
	}
	return nil
}

func (x *OAuthFlows) GetClientCredentials() *OAuthFlow {
	if x != nil {
		return x.ClientCredentials
	}
	return nil
}

func (x *OAuthFlows) GetAuthorizationCode() *OAuthFlow {
	if x != nil {
		return x.AuthorizationCode
	}
	return nil
}

type OAuthFlow struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	AuthorizationUrl string                 `protobuf:"bytes,1,opt,name=authorization_url,json=authorizationUrl,proto3" json:"authorization_url,omitempty"`
	TokenUrl         string                 `protobuf:"bytes,2,opt,name=token_url,json=tokenUrl,proto3" json:"token_url,omitempty"`
	RefreshUrl       string                 `protobuf:"bytes,3,opt,name=refresh_url,json=refreshUrl,proto3" json:"refresh_url,omitempty"`
	// Scope name to description.
	AvailableScopes map[string]string `protobuf:"bytes,4,rep,name=available_scopes,json=availableScopes,proto3" json:"available_scopes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *OAuthFlow) Reset() {
	*x = OAuthFlow{}
	mi := &file_asyncapi_v3_annotations_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OAuthFlow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OAuthFlow) ProtoMessage() {}

func (x *OAuthFlow) ProtoReflect() protoreflect.Message {
	mi := &file_asyncapi_v3_annotations_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OAuthFlow.ProtoReflect.Descriptor instead.
func (*OAuthFlow) Descriptor() ([]byte, []int) {
	return file_asyncapi_v3_annotations_proto_rawDescGZIP(), []int{11}
}

func (x *OAuthFlow) GetAuthorizationUrl() string {
	if x != nil {
		return x.AuthorizationUrl
	}
	return ""
}

func (x *OAuthFlow) GetTokenUrl() string {
	if x != nil {
		return x.TokenUrl
	}
	return ""
}

func (x *OAuthFlow) GetRefreshUrl() string {
	if x != nil {
		return x.RefreshUrl
	}
	return ""
}

func (x *OAuthFlow) GetAvailableScopes() map[string]string {
	if x != nil {
		return x.AvailableScopes
	}
	return nil
}

type Service struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Tags added to every operation of the service (after the service tag).
	Tags         []*Tag        `protobuf:"bytes,1,rep,name=tags,proto3" json:"tags,omitempty"`
	ExternalDocs *ExternalDocs `protobuf:"bytes,2,opt,name=external_docs,json=externalDocs,proto3" json:"external_docs,omitempty"`
	// Security schemes required by every operation, unless overridden.
	Security []string `protobuf:"bytes,3,rep,name=security,proto3" json:"security,omitempty"`
	// Servers the service's channels are available on. Defaults to all.
	Servers []string `protobuf:"bytes,4,rep,name=servers,proto3" json:"servers,omitempty"`
	// Leaves the service out of the document.
	Skip          bool `protobuf:"varint,5,opt,name=skip,proto3" json:"skip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Service) Reset() {
	*x = Service{}
	mi := &file_asyncapi_v3_annotations_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Service) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Service) ProtoMessage() {}

func (x *Service) ProtoReflect() protoreflect.Message {
	mi := &file_asyncapi_v3_annotations_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Service.ProtoReflect.Descriptor instead.
func (*Service) Descriptor() ([]byte, []int) {
	return file_asyncapi_v3_annotations_proto_rawDescGZIP(), []int{12}
}

func (x *Service) GetTags() []*Tag {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Service) GetExternalDocs() *ExternalDocs {
	if x != nil {
		return x.ExternalDocs
	}
	return nil
}

func (x *Service) GetSecurity() []string {
	if x != nil {
		return x.Security
	}
	return nil
}

func (x *Service) GetServers() []string {
	if x != nil {
		return x.Servers
	}
	return nil
}

func (x *Service) GetSkip() bool {
	if x != nil {
		return x.Skip
	}
	return false
}

type Operation struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Operation id. Defaults to a protocol specific id.
	OperationId string `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	Title       string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	// Defaults to the first sentence of the rpc comment.
	Summary string `protobuf:"bytes,3,opt,name=summary,proto3" json:"summary,omitempty"`
	// Defaults to the rpc comment.
	Description  string        `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Tags         []*Tag        `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty"`
	ExternalDocs *ExternalDocs `protobuf:"bytes,6,opt,name=external_docs,json=externalDocs,proto3" json:"external_docs,omitempty"`
	// Overrides Service.security.
	Security []string `protobuf:"bytes,7,rep,name=security,proto3" json:"security,omitempty"`
	// Metadata of the operation's channel.
	Channel *Channel `protobuf:"bytes,8,opt,name=channel,proto3" json:"channel,omitempty"`
	// Leaves the rpc out of the document.
	Skip bool `protobuf:"varint,9,opt,name=skip,proto3" json:"skip,omitempty"`
	// Where replies are sent, for request/reply operations.
	ReplyAddress  *ReplyAddress     `protobuf:"bytes,10,opt,name=reply_address,json=replyAddress,proto3" json:"reply_address,omitempty"`
	Bindings      []*Binding        `protobuf:"bytes,11,rep,name=bindings,proto3" json:"bindings,omitempty"`
	Extensions    map[string]string `protobuf:"bytes,12,rep,name=extensions,proto3" json:"extensions,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Operation) Reset() {
	*x = Operation{}
	mi := &file_asyncapi_v3_annotations_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Operation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Operation) ProtoMessage() {}

func (x *Operation) ProtoReflect() protoreflect.Message {
	mi := &file_asyncapi_v3_annotations_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Operation.ProtoReflect.Descriptor instead.
func (*Operation) Descriptor() ([]byte, []int) {
	return file_asyncapi_v3_annotations_proto_rawDescGZIP(), []int{13}
}

func (x *Operation) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

func (x *Operation) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Operation) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *Operation) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Operation) GetTags() []*Tag {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Operation) GetExternalDocs() *ExternalDocs {
	if x != nil {
		return x.ExternalDocs
	}
	return nil
}

func (x *Operation) GetSecurity() []string {
	if x != nil {
		return x.Security
	}
	return nil
}

func (x *Operation) GetChannel() *Channel {
	if x != nil {
		return x.Channel
	}
	return nil
}

func (x *Operation) GetSkip() bool {
	if x != nil {
		return x.Skip
	}
	return false
}

func (x *Operation) GetReplyAddress() *ReplyAddress {
	if x != nil {
		return x.ReplyAddress
	}
	return nil
}

func (x *Operation) GetBindings() []*Binding {
	if x != nil {
		return x.Bindings
	}
	return nil
}

func (x *Operation) GetExtensions() map[string]string {
	if x != nil {
		return x.Extensions
	}
	return nil
}

type ReplyAddress struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Description string                 `protobuf:"bytes,1,opt,name=description,proto3" json:"description,omitempty"`
	// Runtime expression, e.g. "$message.header#/replyTo".
	Location      string `protobuf:"bytes,2,opt,name=location,proto3" json:"location,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplyAddress) Reset() {
	*x = ReplyAddress{}
	mi := &file_asyncapi_v3_annotations_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplyAddress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplyAddress) ProtoMessage() {}

func (x *ReplyAddress) ProtoReflect() protoreflect.Message {
	mi := &file_asyncapi_v3_annotations_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplyAddress.ProtoReflect.Descriptor instead.
func (*ReplyAddress) Descriptor() ([]byte, []int) {
	return file_asyncapi_v3_annotations_proto_rawDescGZIP(), []int{14}
}

func (x *ReplyAddress) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ReplyAddress) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

// Channel metadata. Addresses are protocol specific and set by protocol
// annotations or inferred.
type Channel struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Channel id. Defaults to one derived from the address.
	Id          string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title       string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Summary     string `protobuf:"bytes,3,opt,name=summary,proto3" json:"summary,omitempty"`
	Description string `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	// Descriptions of address parameters. Parameters are otherwise bound to
	// payload fields with the same name.
	Parameters []*Parameter `protobuf:"bytes,5,rep,name=parameters,proto3" json:"parameters,omitempty"`
	// Overrides Service.servers.
	Servers       []string          `protobuf:"bytes,6,rep,name=servers,proto3" json:"servers,omitempty"`
	Tags          []*Tag            `protobuf:"bytes,7,rep,name=tags,proto3" json:"tags,omitempty"`
	ExternalDocs  *ExternalDocs     `protobuf:"bytes,8,opt,name=external_docs,json=externalDocs,proto3" json:"external_docs,omitempty"`
	Bindings      []*Binding        `protobuf:"bytes,9,rep,name=bindings,proto3" json:"bindings,omitempty"`
	Extensions    map[string]string `protobuf:"bytes,10,rep,name=extensions,proto3" json:"extensions,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Channel) Reset() {
	*x = Channel{}
	mi := &file_asyncapi_v3_annotations_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Channel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Channel) ProtoMessage() {}

func (x *Channel) ProtoReflect() protoreflect.Message {
	mi := &file_asyncapi_v3_annotations_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Channel.ProtoReflect.Descriptor instead.
func (*Channel) Descriptor() ([]byte, []int) {
	return file_asyncapi_v3_annotations_proto_rawDescGZIP(), []int{15}
}

func (x *Channel) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Channel) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Channel) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *Channel) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Channel) GetParameters() []*Parameter {
	if x != nil {
		return x.Parameters
	}
	return nil
}

func (x *Channel) GetServers() []string {
	if x != nil {
		return x.Servers
	}
	return nil
}

func (x *Channel) GetTags() []*Tag {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Channel) GetExternalDocs() *ExternalDocs {
	if x != nil {
		return x.ExternalDocs
	}
	return nil
}

func (x *Channel) GetBindings() []*Binding {
	if x != nil {
		return x.Bindings
	}
	return nil
}

func (x *Channel) GetExtensions() map[string]string {
	if x != nil {
		return x.Extensions
	}
	return nil
}

type Parameter struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Parameter name as it appears in the address, e.g. "order_id".
	Name        string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description string   `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Enum        []string `protobuf:"bytes,3,rep,name=enum,proto3" json:"enum,omitempty"`
	Default     string   `protobuf:"bytes,4,opt,name=default,proto3" json:"default,omitempty"`
	Examples    []string `protobuf:"bytes,5,rep,name=examples,proto3" json:"examples,omitempty"`
	// Runtime expression, e.g. "$message.payload#/orderId".
	Location      string `protobuf:"bytes,6,opt,name=location,proto3" json:"location,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Parameter) Reset() {
	*x = Parameter{}
	mi := &file_asyncapi_v3_annotations_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Parameter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Parameter) ProtoMessage() {}

func (x *Parameter) ProtoReflect() protoreflect.Message {
	mi := &file_asyncapi_v3_annotations_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Parameter.ProtoReflect.Descriptor instead.
func (*Parameter) Descriptor() ([]byte, []int) {
	return file_asyncapi_v3_annotations_proto_rawDescGZIP(), []int{16}
}

func (x *Parameter) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Parameter) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Parameter) GetEnum() []string {
	if x != nil {
		return x.Enum
	}
	return nil
}

func (x *Parameter) GetDefault() string {
	if x != nil {
		return x.Default
	}
	return ""
}

func (x *Parameter) GetExamples() []string {
	if x != nil {
		return x.Examples
	}
	return nil
}

func (x *Parameter) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

type Message struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Machine friendly name. Defaults to the message name.
	Name  string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Title string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	// Defaults to the first sentence of the message comment.
	Summary string `protobuf:"bytes,3,opt,name=summary,proto3" json:"summary,omitempty"`
	// Defaults to the message comment.
	Description string `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	// Overrides Document.default_content_type.
	ContentType string `protobuf:"bytes,5,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	// Message headers.
	Headers []*Header `protobuf:"bytes,6,rep,name=headers,proto3" json:"headers,omitempty"`
	// Runtime expression locating the correlation ID, e.g.
	// "$message.header#/Trace-Id". See also Field.correlation_id.
	CorrelationId string        `protobuf:"bytes,7,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	Examples      []*Example    `protobuf:"bytes,8,rep,name=examples,proto3" json:"examples,omitempty"`
	Tags          []*Tag        `protobuf:"bytes,9,rep,name=tags,proto3" json:"tags,omitempty"`
	ExternalDocs  *ExternalDocs `protobuf:"bytes,10,opt,name=external_docs,json=externalDocs,proto3" json:"external_docs,omitempty"`
	// Metadata of the message's own channel, for protocols that give messages
	// a channel (e.g. a NATS subject on the message).
	Channel *Channel `protobuf:"bytes,11,opt,name=channel,proto3" json:"channel,omitempty"`
	// Description of the correlation ID.
	CorrelationIdDescription string            `protobuf:"bytes,12,opt,name=correlation_id_description,json=correlationIdDescription,proto3" json:"correlation_id_description,omitempty"`
	Bindings                 []*Binding        `protobuf:"bytes,13,rep,name=bindings,proto3" json:"bindings,omitempty"`
	Extensions               map[string]string `protobuf:"bytes,14,rep,name=extensions,proto3" json:"extensions,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_asyncapi_v3_annotations_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_asyncapi_v3_annotations_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_asyncapi_v3_annotations_proto_rawDescGZIP(), []int{17}
}

func (x *Message) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Message) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Message) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *Message) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Message) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *Message) GetHeaders() []*Header {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *Message) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *Message) GetExamples() []*Example {
	if x != nil {
		return x.Examples
	}
	return nil
}

func (x *Message) GetTags() []*Tag {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Message) GetExternalDocs() *ExternalDocs {
	if x != nil {
		return x.ExternalDocs
	}
	return nil
}

func (x *Message) GetChannel() *Channel {
	if x != nil {
		return x.Channel
	}
	return nil
}

func (x *Message) GetCorrelationIdDescription() string {
	if x != nil {
		return x.CorrelationIdDescription
	}
	return ""
}

func (x *Message) GetBindings() []*Binding {
	if x != nil {
		return x.Bindings
	}
	return nil
}

func (x *Message) GetExtensions() map[string]string {
	if x != nil {
		return x.Extensions
	}
	return nil
}

type Header struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Header name, e.g. "Trace-Id".
	Name        string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description string   `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Required    bool     `protobuf:"varint,3,opt,name=required,proto3" json:"required,omitempty"`
	Enum        []string `protobuf:"bytes,4,rep,name=enum,proto3" json:"enum,omitempty"`
	Pattern     string   `protobuf:"bytes,5,opt,name=pattern,proto3" json:"pattern,omitempty"`
	// JSON Schema format, e.g. "uuid" or "date-time".
	Format        string   `protobuf:"bytes,6,opt,name=format,proto3" json:"format,omitempty"`
	Examples      []string `protobuf:"bytes,7,rep,name=examples,proto3" json:"examples,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Header) Reset() {
	*x = Header{}
	mi := &file_asyncapi_v3_annotations_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Header) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Header) ProtoMessage() {}

func (x *Header) ProtoReflect() protoreflect.Message {
	mi := &file_asyncapi_v3_annotations_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Header.ProtoReflect.Descriptor instead.
func (*Header) Descriptor() ([]byte, []int) {
	return file_asyncapi_v3_annotations_proto_rawDescGZIP(), []int{18}
}

func (x *Header) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Header) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Header) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

func (x *Header) GetEnum() []string {
	if x != nil {
		return x.Enum
	}
	return nil
}

func (x *Header) GetPattern() string {
	if x != nil {
		return x.Pattern
	}
	return ""
}

func (x *Header) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *Header) GetExamples() []string {
	if x != nil {
		return x.Examples
	}
	return nil
}

// Example mirrors the AsyncAPI Message Example Object.
type Example struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Name    string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Summary string                 `protobuf:"bytes,2,opt,name=summary,proto3" json:"summary,omitempty"`
	// Payload as JSON (Protobuf JSON mapping).
	Payload       string            `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	Headers       map[string]string `protobuf:"bytes,4,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Example) Reset() {
	*x = Example{}
	mi := &file_asyncapi_v3_annotations_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Example) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Example) ProtoMessage() {}

func (x *Example) ProtoReflect() protoreflect.Message {
	mi := &file_asyncapi_v3_annotations_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Example.ProtoReflect.Descriptor instead.
func (*Example) Descriptor() ([]byte, []int) {
	return file_asyncapi_v3_annotations_proto_rawDescGZIP(), []int{19}
}

func (x *Example) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Example) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *Example) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

func (x *Example) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

type Field struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Examples as JSON values, e.g. "\"ord_123\"" or "42".
	Examples []string `protobuf:"bytes,1,rep,name=examples,proto3" json:"examples,omitempty"`
	// Marks the field as required. Fields using proto2 `required`,
	// buf.validate `required` or google.api.field_behavior = REQUIRED are
	// required automatically.
	Required bool `protobuf:"varint,2,opt,name=required,proto3" json:"required,omitempty"`
	// Marks the field as correlation ID of its message.
	CorrelationId bool `protobuf:"varint,3,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	// JSON Schema format, e.g. "uuid", "email", "uri".
	Format string `protobuf:"bytes,4,opt,name=format,proto3" json:"format,omitempty"`
	// Hides the field from the generated schema.
	Hidden        bool `protobuf:"varint,5,opt,name=hidden,proto3" json:"hidden,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Field) Reset() {
	*x = Field{}
	mi := &file_asyncapi_v3_annotations_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Field) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Field) ProtoMessage() {}

func (x *Field) ProtoReflect() protoreflect.Message {
	mi := &file_asyncapi_v3_annotations_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Field.ProtoReflect.Descriptor instead.
func (*Field) Descriptor() ([]byte, []int) {
	return file_asyncapi_v3_annotations_proto_rawDescGZIP(), []int{20}
}

func (x *Field) GetExamples() []string {
	if x != nil {
		return x.Examples
	}
	return nil
}

func (x *Field) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

func (x *Field) GetCorrelationId() bool {
	if x != nil {
		return x.CorrelationId
	}
	return false
}

func (x *Field) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *Field) GetHidden() bool {
	if x != nil {
		return x.Hidden
	}
	return false
}

var file_asyncapi_v3_annotations_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.FileOptions)(nil),
		ExtensionType: (*Document)(nil),
		Field:         58300,
		Name:          "asyncapi.v3.document",
		Tag:           "bytes,58300,opt,name=document",
		Filename:      "asyncapi/v3/annotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.ServiceOptions)(nil),
		ExtensionType: (*Service)(nil),
		Field:         58300,
		Name:          "asyncapi.v3.service",
		Tag:           "bytes,58300,opt,name=service",
		Filename:      "asyncapi/v3/annotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*Operation)(nil),
		Field:         58300,
		Name:          "asyncapi.v3.operation",
		Tag:           "bytes,58300,opt,name=operation",
		Filename:      "asyncapi/v3/annotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*Message)(nil),
		Field:         58300,
		Name:          "asyncapi.v3.message",
		Tag:           "bytes,58300,opt,name=message",
		Filename:      "asyncapi/v3/annotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*Field)(nil),
		Field:         58300,
		Name:          "asyncapi.v3.field",
		Tag:           "bytes,58300,opt,name=field",
		Filename:      "asyncapi/v3/annotations.proto",
	},
}

// Extension fields to descriptorpb.FileOptions.
var (
	// Document-wide settings. When several files end up in one AsyncAPI
	// document, the settings of all files, and of the files they import, are
	// combined.
	//
	// optional asyncapi.v3.Document document = 58300;
	E_Document = &file_asyncapi_v3_annotations_proto_extTypes[0]
)

// Extension fields to descriptorpb.ServiceOptions.
var (
	// Defaults for every operation of the service.
	//
	// optional asyncapi.v3.Service service = 58300;
	E_Service = &file_asyncapi_v3_annotations_proto_extTypes[1]
)

// Extension fields to descriptorpb.MethodOptions.
var (
	// Overrides for the operation generated for an rpc.
	//
	// optional asyncapi.v3.Operation operation = 58300;
	E_Operation = &file_asyncapi_v3_annotations_proto_extTypes[2]
)

// Extension fields to descriptorpb.MessageOptions.
var (
	// Overrides for the message generated for a Protobuf message.
	//
	// optional asyncapi.v3.Message message = 58300;
	E_Message = &file_asyncapi_v3_annotations_proto_extTypes[3]
)

// Extension fields to descriptorpb.FieldOptions.
var (
	// Extra schema information for a field.
	//
	// optional asyncapi.v3.Field field = 58300;
	E_Field = &file_asyncapi_v3_annotations_proto_extTypes[4]
)

var File_asyncapi_v3_annotations_proto protoreflect.FileDescriptor

const file_asyncapi_v3_annotations_proto_rawDesc = "" +
	"\n" +
	"\x1dasyncapi/v3/annotations.proto\x12\vasyncapi.v3\x1a google/protobuf/descriptor.proto\"\xd6\x03\n" +
	"\bDocument\x12%\n" +
	"\x04info\x18\x01 \x01(\v2\x11.asyncapi.v3.InfoR\x04info\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x120\n" +
	"\x14default_content_type\x18\x03 \x01(\tR\x12defaultContentType\x12-\n" +
	"\aservers\x18\x04 \x03(\v2\x13.asyncapi.v3.ServerR\aservers\x12F\n" +
	"\x10security_schemes\x18\x05 \x03(\v2\x1b.asyncapi.v3.SecuritySchemeR\x0fsecuritySchemes\x12$\n" +
	"\x04tags\x18\x06 \x03(\v2\x10.asyncapi.v3.TagR\x04tags\x12>\n" +
	"\rexternal_docs\x18\a \x01(\v2\x19.asyncapi.v3.ExternalDocsR\fexternalDocs\x12E\n" +
	"\n" +
	"extensions\x18\b \x03(\v2%.asyncapi.v3.Document.ExtensionsEntryR\n" +
	"extensions\x1a=\n" +
	"\x0fExtensionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"9\n" +
	"\aBinding\x12\x1a\n" +
	"\bprotocol\x18\x01 \x01(\tR\bprotocol\x12\x12\n" +
	"\x04json\x18\x02 \x01(\tR\x04json\"\xfe\x02\n" +
	"\x04Info\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x18\n" +
	"\asummary\x18\x04 \x01(\tR\asummary\x12(\n" +
	"\x10terms_of_service\x18\x05 \x01(\tR\x0etermsOfService\x12.\n" +
	"\acontact\x18\x06 \x01(\v2\x14.asyncapi.v3.ContactR\acontact\x12.\n" +
	"\alicense\x18\a \x01(\v2\x14.asyncapi.v3.LicenseR\alicense\x12A\n" +
	"\n" +
	"extensions\x18\b \x03(\v2!.asyncapi.v3.Info.ExtensionsEntryR\n" +
	"extensions\x1a=\n" +
	"\x0fExtensionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"E\n" +
	"\aContact\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\"/\n" +
	"\aLicense\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\"{\n" +
	"\x03Tag\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12>\n" +
	"\rexternal_docs\x18\x03 \x01(\v2\x19.asyncapi.v3.ExternalDocsR\fexternalDocs\"B\n" +
	"\fExternalDocs\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\"\xd8\x04\n" +
	"\x06Server\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04host\x18\x02 \x01(\tR\x04host\x12\x1a\n" +
	"\bprotocol\x18\x03 \x01(\tR\bprotocol\x12)\n" +
	"\x10protocol_version\x18\x04 \x01(\tR\x0fprotocolVersion\x12\x1a\n" +
	"\bpathname\x18\x05 \x01(\tR\bpathname\x12\x14\n" +
	"\x05title\x18\x06 \x01(\tR\x05title\x12\x18\n" +
	"\asummary\x18\a \x01(\tR\asummary\x12 \n" +
	"\vdescription\x18\b \x01(\tR\vdescription\x129\n" +
	"\tvariables\x18\t \x03(\v2\x1b.asyncapi.v3.ServerVariableR\tvariables\x12\x1a\n" +
	"\bsecurity\x18\n" +
	" \x03(\tR\bsecurity\x12$\n" +
	"\x04tags\x18\v \x03(\v2\x10.asyncapi.v3.TagR\x04tags\x12>\n" +
	"\rexternal_docs\x18\f \x01(\v2\x19.asyncapi.v3.ExternalDocsR\fexternalDocs\x120\n" +
	"\bbindings\x18\r \x03(\v2\x14.asyncapi.v3.BindingR\bbindings\x12C\n" +
	"\n" +
	"extensions\x18\x0e \x03(\v2#.asyncapi.v3.Server.ExtensionsEntryR\n" +
	"extensions\x1a=\n" +
	"\x0fExtensionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x90\x01\n" +
	"\x0eServerVariable\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04enum\x18\x02 \x03(\tR\x04enum\x12\x18\n" +
	"\adefault\x18\x03 \x01(\tR\adefault\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1a\n" +
	"\bexamples\x18\x05 \x03(\tR\bexamples\"\xf1\x03\n" +
	"\x0eSecurityScheme\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x123\n" +
	"\x04type\x18\x02 \x01(\x0e2\x1f.asyncapi.v3.SecuritySchemeTypeR\x04type\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x0e\n" +
	"\x02in\x18\x04 \x01(\tR\x02in\x12%\n" +
	"\x0eparameter_name\x18\x05 \x01(\tR\rparameterName\x12\x16\n" +
	"\x06scheme\x18\x06 \x01(\tR\x06scheme\x12#\n" +
	"\rbearer_format\x18\a \x01(\tR\fbearerFormat\x12-\n" +
	"\x13open_id_connect_url\x18\b \x01(\tR\x10openIdConnectUrl\x12\x16\n" +
	"\x06scopes\x18\t \x03(\tR\x06scopes\x12-\n" +
	"\x05flows\x18\n" +
	" \x01(\v2\x17.asyncapi.v3.OAuthFlowsR\x05flows\x12K\n" +
	"\n" +
	"extensions\x18\v \x03(\v2+.asyncapi.v3.SecurityScheme.ExtensionsEntryR\n" +
	"extensions\x1a=\n" +
	"\x0fExtensionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x82\x02\n" +
	"\n" +
	"OAuthFlows\x122\n" +
	"\bimplicit\x18\x01 \x01(\v2\x16.asyncapi.v3.OAuthFlowR\bimplicit\x122\n" +
	"\bpassword\x18\x02 \x01(\v2\x16.asyncapi.v3.OAuthFlowR\bpassword\x12E\n" +
	"\x12client_credentials\x18\x03 \x01(\v2\x16.asyncapi.v3.OAuthFlowR\x11clientCredentials\x12E\n" +
	"\x12authorization_code\x18\x04 \x01(\v2\x16.asyncapi.v3.OAuthFlowR\x11authorizationCode\"\x92\x02\n" +
	"\tOAuthFlow\x12+\n" +
	"\x11authorization_url\x18\x01 \x01(\tR\x10authorizationUrl\x12\x1b\n" +
	"\ttoken_url\x18\x02 \x01(\tR\btokenUrl\x12\x1f\n" +
	"\vrefresh_url\x18\x03 \x01(\tR\n" +
	"refreshUrl\x12V\n" +
	"\x10available_scopes\x18\x04 \x03(\v2+.asyncapi.v3.OAuthFlow.AvailableScopesEntryR\x0favailableScopes\x1aB\n" +
	"\x14AvailableScopesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb9\x01\n" +
	"\aService\x12$\n" +
	"\x04tags\x18\x01 \x03(\v2\x10.asyncapi.v3.TagR\x04tags\x12>\n" +
	"\rexternal_docs\x18\x02 \x01(\v2\x19.asyncapi.v3.ExternalDocsR\fexternalDocs\x12\x1a\n" +
	"\bsecurity\x18\x03 \x03(\tR\bsecurity\x12\x18\n" +
	"\aservers\x18\x04 \x03(\tR\aservers\x12\x12\n" +
	"\x04skip\x18\x05 \x01(\bR\x04skip\"\xbf\x04\n" +
	"\tOperation\x12!\n" +
	"\foperation_id\x18\x01 \x01(\tR\voperationId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\asummary\x18\x03 \x01(\tR\asummary\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12$\n" +
	"\x04tags\x18\x05 \x03(\v2\x10.asyncapi.v3.TagR\x04tags\x12>\n" +
	"\rexternal_docs\x18\x06 \x01(\v2\x19.asyncapi.v3.ExternalDocsR\fexternalDocs\x12\x1a\n" +
	"\bsecurity\x18\a \x03(\tR\bsecurity\x12.\n" +
	"\achannel\x18\b \x01(\v2\x14.asyncapi.v3.ChannelR\achannel\x12\x12\n" +
	"\x04skip\x18\t \x01(\bR\x04skip\x12>\n" +
	"\rreply_address\x18\n" +
	" \x01(\v2\x19.asyncapi.v3.ReplyAddressR\freplyAddress\x120\n" +
	"\bbindings\x18\v \x03(\v2\x14.asyncapi.v3.BindingR\bbindings\x12F\n" +
	"\n" +
	"extensions\x18\f \x03(\v2&.asyncapi.v3.Operation.ExtensionsEntryR\n" +
	"extensions\x1a=\n" +
	"\x0fExtensionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"L\n" +
	"\fReplyAddress\x12 \n" +
	"\vdescription\x18\x01 \x01(\tR\vdescription\x12\x1a\n" +
	"\blocation\x18\x02 \x01(\tR\blocation\"\xda\x03\n" +
	"\aChannel\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\asummary\x18\x03 \x01(\tR\asummary\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x126\n" +
	"\n" +
	"parameters\x18\x05 \x03(\v2\x16.asyncapi.v3.ParameterR\n" +
	"parameters\x12\x18\n" +
	"\aservers\x18\x06 \x03(\tR\aservers\x12$\n" +
	"\x04tags\x18\a \x03(\v2\x10.asyncapi.v3.TagR\x04tags\x12>\n" +
	"\rexternal_docs\x18\b \x01(\v2\x19.asyncapi.v3.ExternalDocsR\fexternalDocs\x120\n" +
	"\bbindings\x18\t \x03(\v2\x14.asyncapi.v3.BindingR\bbindings\x12D\n" +
	"\n" +
	"extensions\x18\n" +
	" \x03(\v2$.asyncapi.v3.Channel.ExtensionsEntryR\n" +
	"extensions\x1a=\n" +
	"\x0fExtensionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa7\x01\n" +
	"\tParameter\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x12\n" +
	"\x04enum\x18\x03 \x03(\tR\x04enum\x12\x18\n" +
	"\adefault\x18\x04 \x01(\tR\adefault\x12\x1a\n" +
	"\bexamples\x18\x05 \x03(\tR\bexamples\x12\x1a\n" +
	"\blocation\x18\x06 \x01(\tR\blocation\"\xa5\x05\n" +
	"\aMessage\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\asummary\x18\x03 \x01(\tR\asummary\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12!\n" +
	"\fcontent_type\x18\x05 \x01(\tR\vcontentType\x12-\n" +
	"\aheaders\x18\x06 \x03(\v2\x13.asyncapi.v3.HeaderR\aheaders\x12%\n" +
	"\x0ecorrelation_id\x18\a \x01(\tR\rcorrelationId\x120\n" +
	"\bexamples\x18\b \x03(\v2\x14.asyncapi.v3.ExampleR\bexamples\x12$\n" +
	"\x04tags\x18\t \x03(\v2\x10.asyncapi.v3.TagR\x04tags\x12>\n" +
	"\rexternal_docs\x18\n" +
	" \x01(\v2\x19.asyncapi.v3.ExternalDocsR\fexternalDocs\x12.\n" +
	"\achannel\x18\v \x01(\v2\x14.asyncapi.v3.ChannelR\achannel\x12<\n" +
	"\x1acorrelation_id_description\x18\f \x01(\tR\x18correlationIdDescription\x120\n" +
	"\bbindings\x18\r \x03(\v2\x14.asyncapi.v3.BindingR\bbindings\x12D\n" +
	"\n" +
	"extensions\x18\x0e \x03(\v2$.asyncapi.v3.Message.ExtensionsEntryR\n" +
	"extensions\x1a=\n" +
	"\x0fExtensionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xbc\x01\n" +
	"\x06Header\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1a\n" +
	"\brequired\x18\x03 \x01(\bR\brequired\x12\x12\n" +
	"\x04enum\x18\x04 \x03(\tR\x04enum\x12\x18\n" +
	"\apattern\x18\x05 \x01(\tR\apattern\x12\x16\n" +
	"\x06format\x18\x06 \x01(\tR\x06format\x12\x1a\n" +
	"\bexamples\x18\a \x03(\tR\bexamples\"\xca\x01\n" +
	"\aExample\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\asummary\x18\x02 \x01(\tR\asummary\x12\x18\n" +
	"\apayload\x18\x03 \x01(\tR\apayload\x12;\n" +
	"\aheaders\x18\x04 \x03(\v2!.asyncapi.v3.Example.HeadersEntryR\aheaders\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x96\x01\n" +
	"\x05Field\x12\x1a\n" +
	"\bexamples\x18\x01 \x03(\tR\bexamples\x12\x1a\n" +
	"\brequired\x18\x02 \x01(\bR\brequired\x12%\n" +
	"\x0ecorrelation_id\x18\x03 \x01(\bR\rcorrelationId\x12\x16\n" +
	"\x06format\x18\x04 \x01(\tR\x06format\x12\x16\n" +
	"\x06hidden\x18\x05 \x01(\bR\x06hidden*\xa2\x04\n" +
	"\x12SecuritySchemeType\x12$\n" +
	" SECURITY_SCHEME_TYPE_UNSPECIFIED\x10\x00\x12&\n" +
	"\"SECURITY_SCHEME_TYPE_USER_PASSWORD\x10\x01\x12 \n" +
	"\x1cSECURITY_SCHEME_TYPE_API_KEY\x10\x02\x12\x1d\n" +
	"\x19SECURITY_SCHEME_TYPE_X509\x10\x03\x12-\n" +
	")SECURITY_SCHEME_TYPE_SYMMETRIC_ENCRYPTION\x10\x04\x12.\n" +
	"*SECURITY_SCHEME_TYPE_ASYMMETRIC_ENCRYPTION\x10\x05\x12%\n" +
	"!SECURITY_SCHEME_TYPE_HTTP_API_KEY\x10\x06\x12\x1d\n" +
	"\x19SECURITY_SCHEME_TYPE_HTTP\x10\a\x12\x1f\n" +
	"\x1bSECURITY_SCHEME_TYPE_OAUTH2\x10\b\x12(\n" +
	"$SECURITY_SCHEME_TYPE_OPEN_ID_CONNECT\x10\t\x12\x1e\n" +
	"\x1aSECURITY_SCHEME_TYPE_PLAIN\x10\n" +
	"\x12%\n" +
	"!SECURITY_SCHEME_TYPE_SCRAM_SHA256\x10\v\x12%\n" +
	"!SECURITY_SCHEME_TYPE_SCRAM_SHA512\x10\f\x12\x1f\n" +
	"\x1bSECURITY_SCHEME_TYPE_GSSAPI\x10\r:Q\n" +
	"\bdocument\x12\x1c.google.protobuf.FileOptions\x18\xbc\xc7\x03 \x01(\v2\x15.asyncapi.v3.DocumentR\bdocument:Q\n" +
	"\aservice\x12\x1f.google.protobuf.ServiceOptions\x18\xbc\xc7\x03 \x01(\v2\x14.asyncapi.v3.ServiceR\aservice:V\n" +
	"\toperation\x12\x1e.google.protobuf.MethodOptions\x18\xbc\xc7\x03 \x01(\v2\x16.asyncapi.v3.OperationR\toperation:Q\n" +
	"\amessage\x12\x1f.google.protobuf.MessageOptions\x18\xbc\xc7\x03 \x01(\v2\x14.asyncapi.v3.MessageR\amessage:I\n" +
	"\x05field\x12\x1d.google.protobuf.FieldOptions\x18\xbc\xc7\x03 \x01(\v2\x12.asyncapi.v3.FieldR\x05fieldBDZBgithub.com/AustinZhu/protoc-gen-asyncapi/pb/asyncapi/v3;asyncapiv3b\x06proto3"

var (
	file_asyncapi_v3_annotations_proto_rawDescOnce sync.Once
	file_asyncapi_v3_annotations_proto_rawDescData []byte
)

func file_asyncapi_v3_annotations_proto_rawDescGZIP() []byte {
	file_asyncapi_v3_annotations_proto_rawDescOnce.Do(func() {
		file_asyncapi_v3_annotations_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_asyncapi_v3_annotations_proto_rawDesc), len(file_asyncapi_v3_annotations_proto_rawDesc)))
	})
	return file_asyncapi_v3_annotations_proto_rawDescData
}

var file_asyncapi_v3_annotations_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_asyncapi_v3_annotations_proto_msgTypes = make([]protoimpl.MessageInfo, 30)
var file_asyncapi_v3_annotations_proto_goTypes = []any{
	(SecuritySchemeType)(0),             // 0: asyncapi.v3.SecuritySchemeType
	(*Document)(nil),                    // 1: asyncapi.v3.Document
	(*Binding)(nil),                     // 2: asyncapi.v3.Binding
	(*Info)(nil),                        // 3: asyncapi.v3.Info
	(*Contact)(nil),                     // 4: asyncapi.v3.Contact
	(*License)(nil),                     // 5: asyncapi.v3.License
	(*Tag)(nil),                         // 6: asyncapi.v3.Tag
	(*ExternalDocs)(nil),                // 7: asyncapi.v3.ExternalDocs
	(*Server)(nil),                      // 8: asyncapi.v3.Server
	(*ServerVariable)(nil),              // 9: asyncapi.v3.ServerVariable
	(*SecurityScheme)(nil),              // 10: asyncapi.v3.SecurityScheme
	(*OAuthFlows)(nil),                  // 11: asyncapi.v3.OAuthFlows
	(*OAuthFlow)(nil),                   // 12: asyncapi.v3.OAuthFlow
	(*Service)(nil),                     // 13: asyncapi.v3.Service
	(*Operation)(nil),                   // 14: asyncapi.v3.Operation
	(*ReplyAddress)(nil),                // 15: asyncapi.v3.ReplyAddress
	(*Channel)(nil),                     // 16: asyncapi.v3.Channel
	(*Parameter)(nil),                   // 17: asyncapi.v3.Parameter
	(*Message)(nil),                     // 18: asyncapi.v3.Message
	(*Header)(nil),                      // 19: asyncapi.v3.Header
	(*Example)(nil),                     // 20: asyncapi.v3.Example
	(*Field)(nil),                       // 21: asyncapi.v3.Field
	nil,                                 // 22: asyncapi.v3.Document.ExtensionsEntry
	nil,                                 // 23: asyncapi.v3.Info.ExtensionsEntry
	nil,                                 // 24: asyncapi.v3.Server.ExtensionsEntry
	nil,                                 // 25: asyncapi.v3.SecurityScheme.ExtensionsEntry
	nil,                                 // 26: asyncapi.v3.OAuthFlow.AvailableScopesEntry
	nil,                                 // 27: asyncapi.v3.Operation.ExtensionsEntry
	nil,                                 // 28: asyncapi.v3.Channel.ExtensionsEntry
	nil,                                 // 29: asyncapi.v3.Message.ExtensionsEntry
	nil,                                 // 30: asyncapi.v3.Example.HeadersEntry
	(*descriptorpb.FileOptions)(nil),    // 31: google.protobuf.FileOptions
	(*descriptorpb.ServiceOptions)(nil), // 32: google.protobuf.ServiceOptions
	(*descriptorpb.MethodOptions)(nil),  // 33: google.protobuf.MethodOptions
	(*descriptorpb.MessageOptions)(nil), // 34: google.protobuf.MessageOptions
	(*descriptorpb.FieldOptions)(nil),   // 35: google.protobuf.FieldOptions
}
var file_asyncapi_v3_annotations_proto_depIdxs = []int32{
	3,  // 0: asyncapi.v3.Document.info:type_name -> asyncapi.v3.Info
	8,  // 1: asyncapi.v3.Document.servers:type_name -> asyncapi.v3.Server
	10, // 2: asyncapi.v3.Document.security_schemes:type_name -> asyncapi.v3.SecurityScheme
	6,  // 3: asyncapi.v3.Document.tags:type_name -> asyncapi.v3.Tag
	7,  // 4: asyncapi.v3.Document.external_docs:type_name -> asyncapi.v3.ExternalDocs
	22, // 5: asyncapi.v3.Document.extensions:type_name -> asyncapi.v3.Document.ExtensionsEntry
	4,  // 6: asyncapi.v3.Info.contact:type_name -> asyncapi.v3.Contact
	5,  // 7: asyncapi.v3.Info.license:type_name -> asyncapi.v3.License
	23, // 8: asyncapi.v3.Info.extensions:type_name -> asyncapi.v3.Info.ExtensionsEntry
	7,  // 9: asyncapi.v3.Tag.external_docs:type_name -> asyncapi.v3.ExternalDocs
	9,  // 10: asyncapi.v3.Server.variables:type_name -> asyncapi.v3.ServerVariable
	6,  // 11: asyncapi.v3.Server.tags:type_name -> asyncapi.v3.Tag
	7,  // 12: asyncapi.v3.Server.external_docs:type_name -> asyncapi.v3.ExternalDocs
	2,  // 13: asyncapi.v3.Server.bindings:type_name -> asyncapi.v3.Binding
	24, // 14: asyncapi.v3.Server.extensions:type_name -> asyncapi.v3.Server.ExtensionsEntry
	0,  // 15: asyncapi.v3.SecurityScheme.type:type_name -> asyncapi.v3.SecuritySchemeType
	11, // 16: asyncapi.v3.SecurityScheme.flows:type_name -> asyncapi.v3.OAuthFlows
	25, // 17: asyncapi.v3.SecurityScheme.extensions:type_name -> asyncapi.v3.SecurityScheme.ExtensionsEntry
	12, // 18: asyncapi.v3.OAuthFlows.implicit:type_name -> asyncapi.v3.OAuthFlow
	12, // 19: asyncapi.v3.OAuthFlows.password:type_name -> asyncapi.v3.OAuthFlow
	12, // 20: asyncapi.v3.OAuthFlows.client_credentials:type_name -> asyncapi.v3.OAuthFlow
	12, // 21: asyncapi.v3.OAuthFlows.authorization_code:type_name -> asyncapi.v3.OAuthFlow
	26, // 22: asyncapi.v3.OAuthFlow.available_scopes:type_name -> asyncapi.v3.OAuthFlow.AvailableScopesEntry
	6,  // 23: asyncapi.v3.Service.tags:type_name -> asyncapi.v3.Tag
	7,  // 24: asyncapi.v3.Service.external_docs:type_name -> asyncapi.v3.ExternalDocs
	6,  // 25: asyncapi.v3.Operation.tags:type_name -> asyncapi.v3.Tag
	7,  // 26: asyncapi.v3.Operation.external_docs:type_name -> asyncapi.v3.ExternalDocs
	16, // 27: asyncapi.v3.Operation.channel:type_name -> asyncapi.v3.Channel
	15, // 28: asyncapi.v3.Operation.reply_address:type_name -> asyncapi.v3.ReplyAddress
	2,  // 29: asyncapi.v3.Operation.bindings:type_name -> asyncapi.v3.Binding
	27, // 30: asyncapi.v3.Operation.extensions:type_name -> asyncapi.v3.Operation.ExtensionsEntry
	17, // 31: asyncapi.v3.Channel.parameters:type_name -> asyncapi.v3.Parameter
	6,  // 32: asyncapi.v3.Channel.tags:type_name -> asyncapi.v3.Tag
	7,  // 33: asyncapi.v3.Channel.external_docs:type_name -> asyncapi.v3.ExternalDocs
	2,  // 34: asyncapi.v3.Channel.bindings:type_name -> asyncapi.v3.Binding
	28, // 35: asyncapi.v3.Channel.extensions:type_name -> asyncapi.v3.Channel.ExtensionsEntry
	19, // 36: asyncapi.v3.Message.headers:type_name -> asyncapi.v3.Header
	20, // 37: asyncapi.v3.Message.examples:type_name -> asyncapi.v3.Example
	6,  // 38: asyncapi.v3.Message.tags:type_name -> asyncapi.v3.Tag
	7,  // 39: asyncapi.v3.Message.external_docs:type_name -> asyncapi.v3.ExternalDocs
	16, // 40: asyncapi.v3.Message.channel:type_name -> asyncapi.v3.Channel
	2,  // 41: asyncapi.v3.Message.bindings:type_name -> asyncapi.v3.Binding
	29, // 42: asyncapi.v3.Message.extensions:type_name -> asyncapi.v3.Message.ExtensionsEntry
	30, // 43: asyncapi.v3.Example.headers:type_name -> asyncapi.v3.Example.HeadersEntry
	31, // 44: asyncapi.v3.document:extendee -> google.protobuf.FileOptions
	32, // 45: asyncapi.v3.service:extendee -> google.protobuf.ServiceOptions
	33, // 46: asyncapi.v3.operation:extendee -> google.protobuf.MethodOptions
	34, // 47: asyncapi.v3.message:extendee -> google.protobuf.MessageOptions
	35, // 48: asyncapi.v3.field:extendee -> google.protobuf.FieldOptions
	1,  // 49: asyncapi.v3.document:type_name -> asyncapi.v3.Document
	13, // 50: asyncapi.v3.service:type_name -> asyncapi.v3.Service
	14, // 51: asyncapi.v3.operation:type_name -> asyncapi.v3.Operation
	18, // 52: asyncapi.v3.message:type_name -> asyncapi.v3.Message
	21, // 53: asyncapi.v3.field:type_name -> asyncapi.v3.Field
	54, // [54:54] is the sub-list for method output_type
	54, // [54:54] is the sub-list for method input_type
	49, // [49:54] is the sub-list for extension type_name
	44, // [44:49] is the sub-list for extension extendee
	0,  // [0:44] is the sub-list for field type_name
}

func init() { file_asyncapi_v3_annotations_proto_init() }
func file_asyncapi_v3_annotations_proto_init() {
	if File_asyncapi_v3_annotations_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_asyncapi_v3_annotations_proto_rawDesc), len(file_asyncapi_v3_annotations_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   30,
			NumExtensions: 5,
			NumServices:   0,
		},
		GoTypes:           file_asyncapi_v3_annotations_proto_goTypes,
		DependencyIndexes: file_asyncapi_v3_annotations_proto_depIdxs,
		EnumInfos:         file_asyncapi_v3_annotations_proto_enumTypes,
		MessageInfos:      file_asyncapi_v3_annotations_proto_msgTypes,
		ExtensionInfos:    file_asyncapi_v3_annotations_proto_extTypes,
	}.Build()
	File_asyncapi_v3_annotations_proto = out.File
	file_asyncapi_v3_annotations_proto_goTypes = nil
	file_asyncapi_v3_annotations_proto_depIdxs = nil
}
