package core

import (
	"fmt"
	"strings"

	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/types/descriptorpb"
	"google.golang.org/protobuf/types/pluginpb"

	"github.com/AustinZhu/protoc-gen-asyncapi/internal/asyncapi"
)

// Plugin describes one protoc plugin binary: its name and the protocols it
// documents, in claim order.
type Plugin struct {
	// Name of the binary, e.g. "protoc-gen-nats-asyncapi".
	Name string
	// Protocols returns fresh protocol instances for one run.
	Protocols func() []Protocol
}

// AllOptions returns the shared options followed by the protocols' own.
func (pl Plugin) AllOptions(p *Params, protocols []Protocol) []Option {
	opts := p.Options()
	for _, pr := range protocols {
		opts = append(opts, pr.Options()...)
	}
	return opts
}

// Usage returns the option list of the plugin.
func (pl Plugin) Usage() string {
	return Usage(pl.AllOptions(DefaultParams(), pl.Protocols()))
}

// Run handles one CodeGeneratorRequest. Generation errors are reported in
// the response, as the plugin protocol requires.
func (pl Plugin) Run(req *pluginpb.CodeGeneratorRequest, version string) *pluginpb.CodeGeneratorResponse {
	// protogen insists on Go import paths, which are irrelevant here: give
	// every file without go_package a placeholder so that non-Go projects
	// do not need Go specific options.
	for _, f := range req.GetProtoFile() {
		if f.GetOptions().GetGoPackage() == "" {
			if f.Options == nil {
				f.Options = &descriptorpb.FileOptions{}
			}
			f.Options.GoPackage = proto.String("invalid.example/" + f.GetName() + ";pb")
		}
	}
	params := DefaultParams()
	protocols := pl.Protocols()
	opts := pl.AllOptions(params, protocols)
	plugin, err := protogen.Options{ParamFunc: func(name, value string) error {
		return parseParams(name+"="+value, opts)
	}}.New(req)
	if err != nil {
		return &pluginpb.CodeGeneratorResponse{Error: proto.String(err.Error())}
	}
	if err := pl.generate(plugin, params, protocols, version); err != nil {
		plugin.Error(err)
	}
	return plugin.Response()
}

func (pl Plugin) generate(plugin *protogen.Plugin, p *Params, protocols []Protocol, version string) error {
	plugin.SupportedFeatures = uint64(pluginpb.CodeGeneratorResponse_FEATURE_PROTO3_OPTIONAL |
		pluginpb.CodeGeneratorResponse_FEATURE_SUPPORTS_EDITIONS)
	plugin.SupportedEditionsMinimum = descriptorpb.Edition_EDITION_PROTO2
	plugin.SupportedEditionsMaximum = descriptorpb.Edition_EDITION_2024

	var groups [][]*protogen.File
	if p.Merge {
		var all []*protogen.File
		for _, f := range plugin.Files {
			if f.Generate {
				all = append(all, f)
			}
		}
		if len(all) > 0 {
			groups = append(groups, all)
		}
	} else {
		for _, f := range plugin.Files {
			if f.Generate {
				groups = append(groups, []*protogen.File{f})
			}
		}
	}

	for _, files := range groups {
		b := newBuilder(p, plugin, files, protocols)
		doc, err := b.build()
		if err != nil {
			return err
		}
		if doc == nil {
			continue
		}
		if err := asyncapi.Validate(doc); err != nil {
			return fmt.Errorf("the generated document is not valid AsyncAPI %s; this is a bug in %s or in an annotation:\n%w", doc.AsyncAPI, pl.Name, err)
		}
		name := p.MergeFileName + p.extension()
		header := fmt.Sprintf("# Code generated by %s %s. DO NOT EDIT.\n", pl.Name, version)
		if !p.Merge {
			base := strings.TrimSuffix(files[0].Desc.Path(), ".proto")
			if p.Format == "jsonschema" {
				name = base + p.extension()
			} else {
				name = base + ".asyncapi" + p.extension()
			}
			header += "# source: " + files[0].Desc.Path() + "\n"
		}
		var content []byte
		switch p.Format {
		case "json":
			content, err = asyncapi.MarshalJSON(doc)
		case "jsonschema":
			content, err = asyncapi.MarshalJSON(jsonSchemaDocument(doc))
		default:
			content, err = asyncapi.MarshalYAML(doc, header)
		}
		if err != nil {
			return fmt.Errorf("%s: %w", name, err)
		}
		out := plugin.NewGeneratedFile(name, "")
		if _, err := out.Write(content); err != nil {
			return err
		}
	}
	return nil
}

// jsonSchemaDocument turns the payload schemas of a document into a
// standalone JSON Schema (draft 2020-12): every schema under $defs, and the
// payloads of the document's messages listed by message id in "anyOf" at the
// root, so a payload validates against the file as a whole.
func jsonSchemaDocument(doc *asyncapi.Document) *asyncapi.Schema {
	root := &asyncapi.Schema{
		SchemaURI:   "https://json-schema.org/draft/2020-12/schema",
		ID:          doc.ID,
		Title:       doc.Info.Title,
		Description: doc.Info.Description,
	}
	defs := asyncapi.NewMap[*asyncapi.Schema]()
	if c := doc.Components; c != nil {
		for _, k := range c.Schemas.Keys() {
			s, _ := c.Schemas.Get(k)
			defs.Set(k, rewriteRefs(s))
		}
		for _, k := range c.Messages.Keys() {
			m, _ := c.Messages.Get(k)
			if s, ok := m.Payload.(*asyncapi.Schema); ok {
				root.AnyOf = append(root.AnyOf, rewriteRefs(s))
			}
		}
	}
	if defs.Len() > 0 {
		root.Extensions = asyncapi.Extensions{"$defs": defs}
	}
	return root
}

// rewriteRefs copies a schema tree, pointing component references at $defs.
func rewriteRefs(s *asyncapi.Schema) *asyncapi.Schema {
	if s == nil {
		return nil
	}
	c := s.Clone()
	if strings.HasPrefix(c.Ref, "#/components/schemas/") {
		c.Ref = "#/$defs/" + strings.TrimPrefix(c.Ref, "#/components/schemas/")
	}
	each := func(list []*asyncapi.Schema) []*asyncapi.Schema {
		var out []*asyncapi.Schema
		for _, x := range list {
			out = append(out, rewriteRefs(x))
		}
		return out
	}
	mapped := func(m *asyncapi.Map[*asyncapi.Schema]) *asyncapi.Map[*asyncapi.Schema] {
		if m == nil {
			return nil
		}
		out := asyncapi.NewMap[*asyncapi.Schema]()
		for _, k := range m.Keys() {
			v, _ := m.Get(k)
			out.Set(k, rewriteRefs(v))
		}
		return out
	}
	c.Properties = mapped(c.Properties)
	c.PatternProperties = mapped(c.PatternProperties)
	c.Definitions = mapped(c.Definitions)
	c.AllOf, c.AnyOf, c.OneOf = each(c.AllOf), each(c.AnyOf), each(c.OneOf)
	c.Not, c.If, c.Then, c.Else = rewriteRefs(c.Not), rewriteRefs(c.If), rewriteRefs(c.Then), rewriteRefs(c.Else)
	c.PropertyNames, c.Contains = rewriteRefs(c.PropertyNames), rewriteRefs(c.Contains)
	if it, ok := c.Items.(*asyncapi.Schema); ok {
		c.Items = rewriteRefs(it)
	}
	if ap, ok := c.AdditionalProperties.(*asyncapi.Schema); ok {
		c.AdditionalProperties = rewriteRefs(ap)
	}
	return c
}
