// MQTT annotations for protoc-gen-asyncapi (protoc-gen-mqtt-asyncapi).
//
// These annotations carry only MQTT concepts: topics and topic filters,
// QoS and retained messages, shared subscriptions and subscription options,
// MQTT 5 request/response, and MQTT specifics of connections, servers and
// authentication. Everything generic (info, servers, security schemes, tags,
// summaries, examples, headers, ...) uses the asyncapi.v3 annotations
// (asyncapi/v3/annotations.proto). MQTT 5 user properties are documented as
// message headers.
//
// The generated documents use the official AsyncAPI MQTT bindings (0.2.0);
// what they do not define is added to them as x-mqtt extensions. Features
// of MQTT 5 are rejected when every declared server speaks MQTT 3.1.1.
//
// A service only needs enough annotations to say "this is an MQTT API";
// everything else is inferred from the Protobuf schema and its comments:
//
//   - publish vs. subscribe vs. request/response is inferred from the rpc
//     shape, as documented on Pattern;
//   - topics default to "<package>/<service>/<method>" in snake_case, with
//     the package's dots as levels;
//   - `{name}` levels in topics are channel parameters, bound to payload
//     fields with the same name; subscribers match them with "+".
//
// Durations are strings in Go syntax, e.g. "30s", "10m", "24h".

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: mqtt/asyncapi/v1/annotations.proto

package mqttv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Version is an MQTT protocol version.
type Version int32

const (
	Version_VERSION_UNSPECIFIED Version = 0
	Version_VERSION_3_1_1       Version = 1
	Version_VERSION_5           Version = 2
)

// Enum value maps for Version.
var (
	Version_name = map[int32]string{
		0: "VERSION_UNSPECIFIED",
		1: "VERSION_3_1_1",
		2: "VERSION_5",
	}
	Version_value = map[string]int32{
		"VERSION_UNSPECIFIED": 0,
		"VERSION_3_1_1":       1,
		"VERSION_5":           2,
	}
)

func (x Version) Enum() *Version {
	p := new(Version)
	*p = x
	return p
}

func (x Version) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Version) Descriptor() protoreflect.EnumDescriptor {
	return file_mqtt_asyncapi_v1_annotations_proto_enumTypes[0].Descriptor()
}

func (Version) Type() protoreflect.EnumType {
	return &file_mqtt_asyncapi_v1_annotations_proto_enumTypes[0]
}

func (x Version) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Version.Descriptor instead.
func (Version) EnumDescriptor() ([]byte, []int) {
	return file_mqtt_asyncapi_v1_annotations_proto_rawDescGZIP(), []int{0}
}

// AuthMethod lists the MQTT authentication methods.
type AuthMethod int32

const (
	AuthMethod_AUTH_METHOD_UNSPECIFIED AuthMethod = 0
	// Username and password in CONNECT (userPassword).
	AuthMethod_AUTH_METHOD_USERNAME_PASSWORD AuthMethod = 1
	// TLS client certificates (X509).
	AuthMethod_AUTH_METHOD_CLIENT_CERTIFICATE AuthMethod = 2
	// MQTT 5 enhanced authentication with AUTH packets.
	AuthMethod_AUTH_METHOD_ENHANCED AuthMethod = 3
)

// Enum value maps for AuthMethod.
var (
	AuthMethod_name = map[int32]string{
		0: "AUTH_METHOD_UNSPECIFIED",
		1: "AUTH_METHOD_USERNAME_PASSWORD",
		2: "AUTH_METHOD_CLIENT_CERTIFICATE",
		3: "AUTH_METHOD_ENHANCED",
	}
	AuthMethod_value = map[string]int32{
		"AUTH_METHOD_UNSPECIFIED":        0,
		"AUTH_METHOD_USERNAME_PASSWORD":  1,
		"AUTH_METHOD_CLIENT_CERTIFICATE": 2,
		"AUTH_METHOD_ENHANCED":           3,
	}
)

func (x AuthMethod) Enum() *AuthMethod {
	p := new(AuthMethod)
	*p = x
	return p
}

func (x AuthMethod) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AuthMethod) Descriptor() protoreflect.EnumDescriptor {
	return file_mqtt_asyncapi_v1_annotations_proto_enumTypes[1].Descriptor()
}

func (AuthMethod) Type() protoreflect.EnumType {
	return &file_mqtt_asyncapi_v1_annotations_proto_enumTypes[1]
}

func (x AuthMethod) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AuthMethod.Descriptor instead.
func (AuthMethod) EnumDescriptor() ([]byte, []int) {
	return file_mqtt_asyncapi_v1_annotations_proto_rawDescGZIP(), []int{1}
}

// Qos is an MQTT quality of service level.
type Qos int32

const (
	Qos_QOS_UNSPECIFIED Qos = 0
	// QoS 0: at most once.
	Qos_QOS_AT_MOST_ONCE Qos = 1
	// QoS 1: at least once.
	Qos_QOS_AT_LEAST_ONCE Qos = 2
	// QoS 2: exactly once.
	Qos_QOS_EXACTLY_ONCE Qos = 3
)

// Enum value maps for Qos.
var (
	Qos_name = map[int32]string{
		0: "QOS_UNSPECIFIED",
		1: "QOS_AT_MOST_ONCE",
		2: "QOS_AT_LEAST_ONCE",
		3: "QOS_EXACTLY_ONCE",
	}
	Qos_value = map[string]int32{
		"QOS_UNSPECIFIED":   0,
		"QOS_AT_MOST_ONCE":  1,
		"QOS_AT_LEAST_ONCE": 2,
		"QOS_EXACTLY_ONCE":  3,
	}
)

func (x Qos) Enum() *Qos {
	p := new(Qos)
	*p = x
	return p
}

func (x Qos) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Qos) Descriptor() protoreflect.EnumDescriptor {
	return file_mqtt_asyncapi_v1_annotations_proto_enumTypes[2].Descriptor()
}

func (Qos) Type() protoreflect.EnumType {
	return &file_mqtt_asyncapi_v1_annotations_proto_enumTypes[2]
}

func (x Qos) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Qos.Descriptor instead.
func (Qos) EnumDescriptor() ([]byte, []int) {
	return file_mqtt_asyncapi_v1_annotations_proto_rawDescGZIP(), []int{2}
}

// Pattern is the messaging pattern of an rpc. When unspecified it is
// inferred from the rpc's shape, which only picks core AsyncAPI operations:
//
//   - an rpc with a response, streaming or not, is REQUEST_REPLY;
//   - a server streaming rpc without request (google.protobuf.Empty)
//     PUBLISHes;
//   - an rpc returning google.protobuf.Empty SUBSCRIBEs;
//   - a bidirectional streaming rpc is a PROCESS.
//
// A client streaming rpc with a response must set the pattern.
type Pattern int32

const (
	Pattern_PATTERN_UNSPECIFIED Pattern = 0
	// MQTT 5 request/response: requests carry a response topic and
	// correlation data; the service answers on the response topic.
	Pattern_PATTERN_REQUEST_REPLY Pattern = 1
	// The service publishes messages.
	Pattern_PATTERN_PUBLISH Pattern = 2
	// The service subscribes to messages.
	Pattern_PATTERN_SUBSCRIBE Pattern = 3
	// The service receives the input on the operation's channel and sends the
	// output (the response) on the output channel, without replying: two
	// operations, e.g. a stream processor.
	Pattern_PATTERN_PROCESS Pattern = 4
)

// Enum value maps for Pattern.
var (
	Pattern_name = map[int32]string{
		0: "PATTERN_UNSPECIFIED",
		1: "PATTERN_REQUEST_REPLY",
		2: "PATTERN_PUBLISH",
		3: "PATTERN_SUBSCRIBE",
		4: "PATTERN_PROCESS",
	}
	Pattern_value = map[string]int32{
		"PATTERN_UNSPECIFIED":   0,
		"PATTERN_REQUEST_REPLY": 1,
		"PATTERN_PUBLISH":       2,
		"PATTERN_SUBSCRIBE":     3,
		"PATTERN_PROCESS":       4,
	}
)

func (x Pattern) Enum() *Pattern {
	p := new(Pattern)
	*p = x
	return p
}

func (x Pattern) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Pattern) Descriptor() protoreflect.EnumDescriptor {
	return file_mqtt_asyncapi_v1_annotations_proto_enumTypes[3].Descriptor()
}

func (Pattern) Type() protoreflect.EnumType {
	return &file_mqtt_asyncapi_v1_annotations_proto_enumTypes[3]
}

func (x Pattern) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Pattern.Descriptor instead.
func (Pattern) EnumDescriptor() ([]byte, []int) {
	return file_mqtt_asyncapi_v1_annotations_proto_rawDescGZIP(), []int{3}
}

// RetainHandling is the Retain Handling subscription option.
type RetainHandling int32

const (
	RetainHandling_RETAIN_HANDLING_UNSPECIFIED RetainHandling = 0
	// 0: send retained messages at subscribe.
	RetainHandling_RETAIN_HANDLING_SEND_AT_SUBSCRIBE RetainHandling = 1
	// 1: send them only for new subscriptions.
	RetainHandling_RETAIN_HANDLING_SEND_IF_NEW RetainHandling = 2
	// 2: never send them.
	RetainHandling_RETAIN_HANDLING_DO_NOT_SEND RetainHandling = 3
)

// Enum value maps for RetainHandling.
var (
	RetainHandling_name = map[int32]string{
		0: "RETAIN_HANDLING_UNSPECIFIED",
		1: "RETAIN_HANDLING_SEND_AT_SUBSCRIBE",
		2: "RETAIN_HANDLING_SEND_IF_NEW",
		3: "RETAIN_HANDLING_DO_NOT_SEND",
	}
	RetainHandling_value = map[string]int32{
		"RETAIN_HANDLING_UNSPECIFIED":       0,
		"RETAIN_HANDLING_SEND_AT_SUBSCRIBE": 1,
		"RETAIN_HANDLING_SEND_IF_NEW":       2,
		"RETAIN_HANDLING_DO_NOT_SEND":       3,
	}
)

func (x RetainHandling) Enum() *RetainHandling {
	p := new(RetainHandling)
	*p = x
	return p
}

func (x RetainHandling) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RetainHandling) Descriptor() protoreflect.EnumDescriptor {
	return file_mqtt_asyncapi_v1_annotations_proto_enumTypes[4].Descriptor()
}

func (RetainHandling) Type() protoreflect.EnumType {
	return &file_mqtt_asyncapi_v1_annotations_proto_enumTypes[4]
}

func (x RetainHandling) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RetainHandling.Descriptor instead.
func (RetainHandling) EnumDescriptor() ([]byte, []int) {
	return file_mqtt_asyncapi_v1_annotations_proto_rawDescGZIP(), []int{4}
}

// Document holds the MQTT specifics of a document. When several files are
// merged into one AsyncAPI document, the settings of all files (and of the
// files they import) are combined.
type Document struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// MQTT details of servers declared in (asyncapi.v3.document).servers.
	Servers []*Server `protobuf:"bytes,1,rep,name=servers,proto3" json:"servers,omitempty"`
	// Authentication method of security schemes declared in
	// (asyncapi.v3.document).security_schemes.
	Auth          []*Auth `protobuf:"bytes,2,rep,name=auth,proto3" json:"auth,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Document) Reset() {
	*x = Document{}
	mi := &file_mqtt_asyncapi_v1_annotations_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Document) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Document) ProtoMessage() {}

func (x *Document) ProtoReflect() protoreflect.Message {
	mi := &file_mqtt_asyncapi_v1_annotations_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Document.ProtoReflect.Descriptor instead.
func (*Document) Descriptor() ([]byte, []int) {
	return file_mqtt_asyncapi_v1_annotations_proto_rawDescGZIP(), []int{0}
}

func (x *Document) GetServers() []*Server {
	if x != nil {
		return x.Servers
	}
	return nil
}

func (x *Document) GetAuth() []*Auth {
	if x != nil {
		return x.Auth
	}
	return nil
}

// Server adds the connection settings of MQTT clients to a server (a
// broker) declared with the asyncapi.v3 annotations.
type Server struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name of the (asyncapi.v3.document) server.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// MQTT version the clients speak. Defaults to MQTT 5.
	Version Version `protobuf:"varint,2,opt,name=version,proto3,enum=mqtt.asyncapi.v1.Version" json:"version,omitempty"`
	// Client identifier, e.g. "sensor-{device_id}".
	ClientId string `protobuf:"bytes,3,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	// Clean start (MQTT 5) or clean session (MQTT 3.1.1): discard any
	// previous session. Unset keeps the broker's default of a clean session.
	CleanStart *bool `protobuf:"varint,4,opt,name=clean_start,json=cleanStart,proto3,oneof" json:"clean_start,omitempty"`
	// Keep alive interval, at most 65535s, e.g. "60s".
	KeepAlive string `protobuf:"bytes,5,opt,name=keep_alive,json=keepAlive,proto3" json:"keep_alive,omitempty"`
	// Session expiry interval (MQTT 5): how long the broker keeps the
	// session after a disconnect.
	SessionExpiry string `protobuf:"bytes,6,opt,name=session_expiry,json=sessionExpiry,proto3" json:"session_expiry,omitempty"`
	// Largest packet in bytes the client accepts.
	MaximumPacketSize uint32 `protobuf:"varint,7,opt,name=maximum_packet_size,json=maximumPacketSize,proto3" json:"maximum_packet_size,omitempty"`
	// Receive maximum (MQTT 5): most unacknowledged QoS 1 and 2 publications
	// the client accepts.
	ReceiveMaximum uint32 `protobuf:"varint,8,opt,name=receive_maximum,json=receiveMaximum,proto3" json:"receive_maximum,omitempty"`
	// Topic alias maximum (MQTT 5) the client accepts.
	TopicAliasMaximum uint32 `protobuf:"varint,9,opt,name=topic_alias_maximum,json=topicAliasMaximum,proto3" json:"topic_alias_maximum,omitempty"`
	// Last will and testament, published by the broker when the client
	// disconnects ungracefully.
	LastWill      *LastWill `protobuf:"bytes,10,opt,name=last_will,json=lastWill,proto3" json:"last_will,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Server) Reset() {
	*x = Server{}
	mi := &file_mqtt_asyncapi_v1_annotations_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server) ProtoMessage() {}

func (x *Server) ProtoReflect() protoreflect.Message {
	mi := &file_mqtt_asyncapi_v1_annotations_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server.ProtoReflect.Descriptor instead.
func (*Server) Descriptor() ([]byte, []int) {
	return file_mqtt_asyncapi_v1_annotations_proto_rawDescGZIP(), []int{1}
}

func (x *Server) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Server) GetVersion() Version {
	if x != nil {
		return x.Version
	}
	return Version_VERSION_UNSPECIFIED
}

func (x *Server) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *Server) GetCleanStart() bool {
	if x != nil && x.CleanStart != nil {
		return *x.CleanStart
	}
	return false
}

func (x *Server) GetKeepAlive() string {
	if x != nil {
		return x.KeepAlive
	}
	return ""
}

func (x *Server) GetSessionExpiry() string {
	if x != nil {
		return x.SessionExpiry
	}
	return ""
}

func (x *Server) GetMaximumPacketSize() uint32 {
	if x != nil {
		return x.MaximumPacketSize
	}
	return 0
}

func (x *Server) GetReceiveMaximum() uint32 {
	if x != nil {
		return x.ReceiveMaximum
	}
	return 0
}

func (x *Server) GetTopicAliasMaximum() uint32 {
	if x != nil {
		return x.TopicAliasMaximum
	}
	return 0
}

func (x *Server) GetLastWill() *LastWill {
	if x != nil {
		return x.LastWill
	}
	return nil
}

// LastWill is the last will and testament of a client.
type LastWill struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Topic the will is published to.
	Topic string `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Qos   Qos    `protobuf:"varint,2,opt,name=qos,proto3,enum=mqtt.asyncapi.v1.Qos" json:"qos,omitempty"`
	// Payload of the will.
	Message string `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Retain  bool   `protobuf:"varint,4,opt,name=retain,proto3" json:"retain,omitempty"`
	// Will delay interval (MQTT 5): wait this long before publishing.
	Delay         string `protobuf:"bytes,5,opt,name=delay,proto3" json:"delay,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LastWill) Reset() {
	*x = LastWill{}
	mi := &file_mqtt_asyncapi_v1_annotations_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LastWill) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LastWill) ProtoMessage() {}

func (x *LastWill) ProtoReflect() protoreflect.Message {
	mi := &file_mqtt_asyncapi_v1_annotations_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LastWill.ProtoReflect.Descriptor instead.
func (*LastWill) Descriptor() ([]byte, []int) {
	return file_mqtt_asyncapi_v1_annotations_proto_rawDescGZIP(), []int{2}
}

func (x *LastWill) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *LastWill) GetQos() Qos {
	if x != nil {
		return x.Qos
	}
	return Qos_QOS_UNSPECIFIED
}

func (x *LastWill) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LastWill) GetRetain() bool {
	if x != nil {
		return x.Retain
	}
	return false
}

func (x *LastWill) GetDelay() string {
	if x != nil {
		return x.Delay
	}
	return ""
}

// Auth sets the authentication method of a security scheme. The scheme
// type is derived from it unless the scheme sets one.
type Auth struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name of the (asyncapi.v3.document) security scheme.
	Scheme string     `protobuf:"bytes,1,opt,name=scheme,proto3" json:"scheme,omitempty"`
	Method AuthMethod `protobuf:"varint,2,opt,name=method,proto3,enum=mqtt.asyncapi.v1.AuthMethod" json:"method,omitempty"`
	// ENHANCED: the MQTT 5 authentication method, e.g. "SCRAM-SHA-256".
	EnhancedMethod string `protobuf:"bytes,3,opt,name=enhanced_method,json=enhancedMethod,proto3" json:"enhanced_method,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Auth) Reset() {
	*x = Auth{}
	mi := &file_mqtt_asyncapi_v1_annotations_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Auth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Auth) ProtoMessage() {}

func (x *Auth) ProtoReflect() protoreflect.Message {
	mi := &file_mqtt_asyncapi_v1_annotations_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Auth.ProtoReflect.Descriptor instead.
func (*Auth) Descriptor() ([]byte, []int) {
	return file_mqtt_asyncapi_v1_annotations_proto_rawDescGZIP(), []int{3}
}

func (x *Auth) GetScheme() string {
	if x != nil {
		return x.Scheme
	}
	return ""
}

func (x *Auth) GetMethod() AuthMethod {
	if x != nil {
		return x.Method
	}
	return AuthMethod_AUTH_METHOD_UNSPECIFIED
}

func (x *Auth) GetEnhancedMethod() string {
	if x != nil {
		return x.EnhancedMethod
	}
	return ""
}

// Service holds defaults for every rpc of a service.
type Service struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Prefix of the topics of the service's rpcs, joined with '/'.
	TopicPrefix string `protobuf:"bytes,1,opt,name=topic_prefix,json=topicPrefix,proto3" json:"topic_prefix,omitempty"`
	// Default QoS of the service's operations.
	Qos Qos `protobuf:"varint,2,opt,name=qos,proto3,enum=mqtt.asyncapi.v1.Qos" json:"qos,omitempty"`
	// Shared subscription group (MQTT 5) of the service's subscribers, so
	// instances share the load: "$share/<group>/<filter>".
	SharedGroup   string `protobuf:"bytes,3,opt,name=shared_group,json=sharedGroup,proto3" json:"shared_group,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Service) Reset() {
	*x = Service{}
	mi := &file_mqtt_asyncapi_v1_annotations_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Service) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Service) ProtoMessage() {}

func (x *Service) ProtoReflect() protoreflect.Message {
	mi := &file_mqtt_asyncapi_v1_annotations_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Service.ProtoReflect.Descriptor instead.
func (*Service) Descriptor() ([]byte, []int) {
	return file_mqtt_asyncapi_v1_annotations_proto_rawDescGZIP(), []int{4}
}

func (x *Service) GetTopicPrefix() string {
	if x != nil {
		return x.TopicPrefix
	}
	return ""
}

func (x *Service) GetQos() Qos {
	if x != nil {
		return x.Qos
	}
	return Qos_QOS_UNSPECIFIED
}

func (x *Service) GetSharedGroup() string {
	if x != nil {
		return x.SharedGroup
	}
	return ""
}

// Operation describes the MQTT operation of an rpc.
type Operation struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Messaging pattern; inferred when unspecified.
	Pattern Pattern `protobuf:"varint,1,opt,name=pattern,proto3,enum=mqtt.asyncapi.v1.Pattern" json:"pattern,omitempty"`
	// Topic, relative to the service's topic_prefix. Subscribers may use
	// the "+" and "#" wildcards.
	Topic string `protobuf:"bytes,2,opt,name=topic,proto3" json:"topic,omitempty"`
	// QoS of publications, or the maximum QoS of subscriptions. Defaults to
	// the service's.
	Qos Qos `protobuf:"varint,3,opt,name=qos,proto3,enum=mqtt.asyncapi.v1.Qos" json:"qos,omitempty"`
	// Publishers: the broker retains the last message of the topic.
	Retain bool `protobuf:"varint,4,opt,name=retain,proto3" json:"retain,omitempty"`
	// Publishers (MQTT 5): message expiry interval, e.g. "1h".
	MessageExpiry string `protobuf:"bytes,5,opt,name=message_expiry,json=messageExpiry,proto3" json:"message_expiry,omitempty"`
	// Subscribers: shared subscription group (MQTT 5); defaults to the
	// service's for its own subscribers.
	SharedGroup string `protobuf:"bytes,6,opt,name=shared_group,json=sharedGroup,proto3" json:"shared_group,omitempty"`
	// Subscribers (MQTT 5): when retained messages are sent.
	RetainHandling RetainHandling `protobuf:"varint,7,opt,name=retain_handling,json=retainHandling,proto3,enum=mqtt.asyncapi.v1.RetainHandling" json:"retain_handling,omitempty"`
	// Subscribers (MQTT 5): do not receive the client's own publications.
	NoLocal bool `protobuf:"varint,8,opt,name=no_local,json=noLocal,proto3" json:"no_local,omitempty"`
	// Subscribers (MQTT 5): keep the retain flag of forwarded messages.
	RetainAsPublished bool `protobuf:"varint,9,opt,name=retain_as_published,json=retainAsPublished,proto3" json:"retain_as_published,omitempty"`
	// REQUEST_REPLY: the response topic requesters set, relative to the
	// service's topic_prefix, e.g. "responses/{client_id}". Defaults to a
	// response topic chosen by each requester.
	ReplyTopic string `protobuf:"bytes,10,opt,name=reply_topic,json=replyTopic,proto3" json:"reply_topic,omitempty"`
	// REQUEST_REPLY: additional reply messages (full Protobuf names), e.g.
	// an error message.
	ReplyMessages []string `protobuf:"bytes,11,rep,name=reply_messages,json=replyMessages,proto3" json:"reply_messages,omitempty"`
	// PROCESS: Topic the output is published to, relative to the service's
	// topic_prefix. Defaults to the input topic followed by "/output".
	Output        string `protobuf:"bytes,12,opt,name=output,proto3" json:"output,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Operation) Reset() {
	*x = Operation{}
	mi := &file_mqtt_asyncapi_v1_annotations_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Operation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Operation) ProtoMessage() {}

func (x *Operation) ProtoReflect() protoreflect.Message {
	mi := &file_mqtt_asyncapi_v1_annotations_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Operation.ProtoReflect.Descriptor instead.
func (*Operation) Descriptor() ([]byte, []int) {
	return file_mqtt_asyncapi_v1_annotations_proto_rawDescGZIP(), []int{5}
}

func (x *Operation) GetPattern() Pattern {
	if x != nil {
		return x.Pattern
	}
	return Pattern_PATTERN_UNSPECIFIED
}

func (x *Operation) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *Operation) GetQos() Qos {
	if x != nil {
		return x.Qos
	}
	return Qos_QOS_UNSPECIFIED
}

func (x *Operation) GetRetain() bool {
	if x != nil {
		return x.Retain
	}
	return false
}

func (x *Operation) GetMessageExpiry() string {
	if x != nil {
		return x.MessageExpiry
	}
	return ""
}

func (x *Operation) GetSharedGroup() string {
	if x != nil {
		return x.SharedGroup
	}
	return ""
}

func (x *Operation) GetRetainHandling() RetainHandling {
	if x != nil {
		return x.RetainHandling
	}
	return RetainHandling_RETAIN_HANDLING_UNSPECIFIED
}

func (x *Operation) GetNoLocal() bool {
	if x != nil {
		return x.NoLocal
	}
	return false
}

func (x *Operation) GetRetainAsPublished() bool {
	if x != nil {
		return x.RetainAsPublished
	}
	return false
}

func (x *Operation) GetReplyTopic() string {
	if x != nil {
		return x.ReplyTopic
	}
	return ""
}

func (x *Operation) GetReplyMessages() []string {
	if x != nil {
		return x.ReplyMessages
	}
	return nil
}

func (x *Operation) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

// Message holds MQTT properties of a message, and optionally gives it its
// own topic, documented even when no rpc uses it.
type Message struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Topic of the message's own channel.
	Topic string `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	// Payload format indicator (MQTT 5): the payload is UTF-8 text.
	Utf8 bool `protobuf:"varint,2,opt,name=utf8,proto3" json:"utf8,omitempty"`
	// Content Type property (MQTT 5), e.g. "application/json".
	ContentType   string `protobuf:"bytes,3,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_mqtt_asyncapi_v1_annotations_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_mqtt_asyncapi_v1_annotations_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_mqtt_asyncapi_v1_annotations_proto_rawDescGZIP(), []int{6}
}

func (x *Message) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *Message) GetUtf8() bool {
	if x != nil {
		return x.Utf8
	}
	return false
}

func (x *Message) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

var file_mqtt_asyncapi_v1_annotations_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.FileOptions)(nil),
		ExtensionType: (*Document)(nil),
		Field:         58370,
		Name:          "mqtt.asyncapi.v1.document",
		Tag:           "bytes,58370,opt,name=document",
		Filename:      "mqtt/asyncapi/v1/annotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.ServiceOptions)(nil),
		ExtensionType: (*Service)(nil),
		Field:         58370,
		Name:          "mqtt.asyncapi.v1.service",
		Tag:           "bytes,58370,opt,name=service",
		Filename:      "mqtt/asyncapi/v1/annotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*Operation)(nil),
		Field:         58370,
		Name:          "mqtt.asyncapi.v1.operation",
		Tag:           "bytes,58370,opt,name=operation",
		Filename:      "mqtt/asyncapi/v1/annotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*Message)(nil),
		Field:         58370,
		Name:          "mqtt.asyncapi.v1.message",
		Tag:           "bytes,58370,opt,name=message",
		Filename:      "mqtt/asyncapi/v1/annotations.proto",
	},
}

// Extension fields to descriptorpb.FileOptions.
var (
	// MQTT specifics of the document: connection and authentication details.
	//
	// optional mqtt.asyncapi.v1.Document document = 58370;
	E_Document = &file_mqtt_asyncapi_v1_annotations_proto_extTypes[0]
)

// Extension fields to descriptorpb.ServiceOptions.
var (
	// MQTT defaults applied to every rpc of the service.
	//
	// optional mqtt.asyncapi.v1.Service service = 58370;
	E_Service = &file_mqtt_asyncapi_v1_annotations_proto_extTypes[1]
)

// Extension fields to descriptorpb.MethodOptions.
var (
	// Describes the MQTT operation implemented by an rpc.
	//
	// optional mqtt.asyncapi.v1.Operation operation = 58370;
	E_Operation = &file_mqtt_asyncapi_v1_annotations_proto_extTypes[2]
)

// Extension fields to descriptorpb.MessageOptions.
var (
	// MQTT properties of a message, and optionally its own topic.
	//
	// optional mqtt.asyncapi.v1.Message message = 58370;
	E_Message = &file_mqtt_asyncapi_v1_annotations_proto_extTypes[3]
)

var File_mqtt_asyncapi_v1_annotations_proto protoreflect.FileDescriptor

const file_mqtt_asyncapi_v1_annotations_proto_rawDesc = "" +
	"\n" +
	"\"mqtt/asyncapi/v1/annotations.proto\x12\x10mqtt.asyncapi.v1\x1a google/protobuf/descriptor.proto\"j\n" +
	"\bDocument\x122\n" +
	"\aservers\x18\x01 \x03(\v2\x18.mqtt.asyncapi.v1.ServerR\aservers\x12*\n" +
	"\x04auth\x18\x02 \x03(\v2\x16.mqtt.asyncapi.v1.AuthR\x04auth\"\xac\x03\n" +
	"\x06Server\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x123\n" +
	"\aversion\x18\x02 \x01(\x0e2\x19.mqtt.asyncapi.v1.VersionR\aversion\x12\x1b\n" +
	"\tclient_id\x18\x03 \x01(\tR\bclientId\x12$\n" +
	"\vclean_start\x18\x04 \x01(\bH\x00R\n" +
	"cleanStart\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"keep_alive\x18\x05 \x01(\tR\tkeepAlive\x12%\n" +
	"\x0esession_expiry\x18\x06 \x01(\tR\rsessionExpiry\x12.\n" +
	"\x13maximum_packet_size\x18\a \x01(\rR\x11maximumPacketSize\x12'\n" +
	"\x0freceive_maximum\x18\b \x01(\rR\x0ereceiveMaximum\x12.\n" +
	"\x13topic_alias_maximum\x18\t \x01(\rR\x11topicAliasMaximum\x127\n" +
	"\tlast_will\x18\n" +
	" \x01(\v2\x1a.mqtt.asyncapi.v1.LastWillR\blastWillB\x0e\n" +
	"\f_clean_start\"\x91\x01\n" +
	"\bLastWill\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x12'\n" +
	"\x03qos\x18\x02 \x01(\x0e2\x15.mqtt.asyncapi.v1.QosR\x03qos\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x16\n" +
	"\x06retain\x18\x04 \x01(\bR\x06retain\x12\x14\n" +
	"\x05delay\x18\x05 \x01(\tR\x05delay\"}\n" +
	"\x04Auth\x12\x16\n" +
	"\x06scheme\x18\x01 \x01(\tR\x06scheme\x124\n" +
	"\x06method\x18\x02 \x01(\x0e2\x1c.mqtt.asyncapi.v1.AuthMethodR\x06method\x12'\n" +
	"\x0fenhanced_method\x18\x03 \x01(\tR\x0eenhancedMethod\"x\n" +
	"\aService\x12!\n" +
	"\ftopic_prefix\x18\x01 \x01(\tR\vtopicPrefix\x12'\n" +
	"\x03qos\x18\x02 \x01(\x0e2\x15.mqtt.asyncapi.v1.QosR\x03qos\x12!\n" +
	"\fshared_group\x18\x03 \x01(\tR\vsharedGroup\"\xd7\x03\n" +
	"\tOperation\x123\n" +
	"\apattern\x18\x01 \x01(\x0e2\x19.mqtt.asyncapi.v1.PatternR\apattern\x12\x14\n" +
	"\x05topic\x18\x02 \x01(\tR\x05topic\x12'\n" +
	"\x03qos\x18\x03 \x01(\x0e2\x15.mqtt.asyncapi.v1.QosR\x03qos\x12\x16\n" +
	"\x06retain\x18\x04 \x01(\bR\x06retain\x12%\n" +
	"\x0emessage_expiry\x18\x05 \x01(\tR\rmessageExpiry\x12!\n" +
	"\fshared_group\x18\x06 \x01(\tR\vsharedGroup\x12I\n" +
	"\x0fretain_handling\x18\a \x01(\x0e2 .mqtt.asyncapi.v1.RetainHandlingR\x0eretainHandling\x12\x19\n" +
	"\bno_local\x18\b \x01(\bR\anoLocal\x12.\n" +
	"\x13retain_as_published\x18\t \x01(\bR\x11retainAsPublished\x12\x1f\n" +
	"\vreply_topic\x18\n" +
	" \x01(\tR\n" +
	"replyTopic\x12%\n" +
	"\x0ereply_messages\x18\v \x03(\tR\rreplyMessages\x12\x16\n" +
	"\x06output\x18\f \x01(\tR\x06output\"V\n" +
	"\aMessage\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x12\x12\n" +
	"\x04utf8\x18\x02 \x01(\bR\x04utf8\x12!\n" +
	"\fcontent_type\x18\x03 \x01(\tR\vcontentType*D\n" +
	"\aVersion\x12\x17\n" +
	"\x13VERSION_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rVERSION_3_1_1\x10\x01\x12\r\n" +
	"\tVERSION_5\x10\x02*\x8a\x01\n" +
	"\n" +
	"AuthMethod\x12\x1b\n" +
	"\x17AUTH_METHOD_UNSPECIFIED\x10\x00\x12!\n" +
	"\x1dAUTH_METHOD_USERNAME_PASSWORD\x10\x01\x12\"\n" +
	"\x1eAUTH_METHOD_CLIENT_CERTIFICATE\x10\x02\x12\x18\n" +
	"\x14AUTH_METHOD_ENHANCED\x10\x03*]\n" +
	"\x03Qos\x12\x13\n" +
	"\x0fQOS_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10QOS_AT_MOST_ONCE\x10\x01\x12\x15\n" +
	"\x11QOS_AT_LEAST_ONCE\x10\x02\x12\x14\n" +
	"\x10QOS_EXACTLY_ONCE\x10\x03*~\n" +
	"\aPattern\x12\x17\n" +
	"\x13PATTERN_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15PATTERN_REQUEST_REPLY\x10\x01\x12\x13\n" +
	"\x0fPATTERN_PUBLISH\x10\x02\x12\x15\n" +
	"\x11PATTERN_SUBSCRIBE\x10\x03\x12\x13\n" +
	"\x0fPATTERN_PROCESS\x10\x04*\x9a\x01\n" +
	"\x0eRetainHandling\x12\x1f\n" +
	"\x1bRETAIN_HANDLING_UNSPECIFIED\x10\x00\x12%\n" +
	"!RETAIN_HANDLING_SEND_AT_SUBSCRIBE\x10\x01\x12\x1f\n" +
	"\x1bRETAIN_HANDLING_SEND_IF_NEW\x10\x02\x12\x1f\n" +
	"\x1bRETAIN_HANDLING_DO_NOT_SEND\x10\x03:V\n" +
	"\bdocument\x12\x1c.google.protobuf.FileOptions\x18\x82\xc8\x03 \x01(\v2\x1a.mqtt.asyncapi.v1.DocumentR\bdocument:V\n" +
	"\aservice\x12\x1f.google.protobuf.ServiceOptions\x18\x82\xc8\x03 \x01(\v2\x19.mqtt.asyncapi.v1.ServiceR\aservice:[\n" +
	"\toperation\x12\x1e.google.protobuf.MethodOptions\x18\x82\xc8\x03 \x01(\v2\x1b.mqtt.asyncapi.v1.OperationR\toperation:V\n" +
	"\amessage\x12\x1f.google.protobuf.MessageOptions\x18\x82\xc8\x03 \x01(\v2\x19.mqtt.asyncapi.v1.MessageR\amessageBEZCgithub.com/AustinZhu/protoc-gen-asyncapi/pb/mqtt/asyncapi/v1;mqttv1b\x06proto3"

var (
	file_mqtt_asyncapi_v1_annotations_proto_rawDescOnce sync.Once
	file_mqtt_asyncapi_v1_annotations_proto_rawDescData []byte
)

func file_mqtt_asyncapi_v1_annotations_proto_rawDescGZIP() []byte {
	file_mqtt_asyncapi_v1_annotations_proto_rawDescOnce.Do(func() {
		file_mqtt_asyncapi_v1_annotations_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mqtt_asyncapi_v1_annotations_proto_rawDesc), len(file_mqtt_asyncapi_v1_annotations_proto_rawDesc)))
	})
	return file_mqtt_asyncapi_v1_annotations_proto_rawDescData
}

var file_mqtt_asyncapi_v1_annotations_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_mqtt_asyncapi_v1_annotations_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_mqtt_asyncapi_v1_annotations_proto_goTypes = []any{
	(Version)(0),                        // 0: mqtt.asyncapi.v1.Version
	(AuthMethod)(0),                     // 1: mqtt.asyncapi.v1.AuthMethod
	(Qos)(0),                            // 2: mqtt.asyncapi.v1.Qos
	(Pattern)(0),                        // 3: mqtt.asyncapi.v1.Pattern
	(RetainHandling)(0),                 // 4: mqtt.asyncapi.v1.RetainHandling
	(*Document)(nil),                    // 5: mqtt.asyncapi.v1.Document
	(*Server)(nil),                      // 6: mqtt.asyncapi.v1.Server
	(*LastWill)(nil),                    // 7: mqtt.asyncapi.v1.LastWill
	(*Auth)(nil),                        // 8: mqtt.asyncapi.v1.Auth
	(*Service)(nil),                     // 9: mqtt.asyncapi.v1.Service
	(*Operation)(nil),                   // 10: mqtt.asyncapi.v1.Operation
	(*Message)(nil),                     // 11: mqtt.asyncapi.v1.Message
	(*descriptorpb.FileOptions)(nil),    // 12: google.protobuf.FileOptions
	(*descriptorpb.ServiceOptions)(nil), // 13: google.protobuf.ServiceOptions
	(*descriptorpb.MethodOptions)(nil),  // 14: google.protobuf.MethodOptions
	(*descriptorpb.MessageOptions)(nil), // 15: google.protobuf.MessageOptions
}
var file_mqtt_asyncapi_v1_annotations_proto_depIdxs = []int32{
	6,  // 0: mqtt.asyncapi.v1.Document.servers:type_name -> mqtt.asyncapi.v1.Server
	8,  // 1: mqtt.asyncapi.v1.Document.auth:type_name -> mqtt.asyncapi.v1.Auth
	0,  // 2: mqtt.asyncapi.v1.Server.version:type_name -> mqtt.asyncapi.v1.Version
	7,  // 3: mqtt.asyncapi.v1.Server.last_will:type_name -> mqtt.asyncapi.v1.LastWill
	2,  // 4: mqtt.asyncapi.v1.LastWill.qos:type_name -> mqtt.asyncapi.v1.Qos
	1,  // 5: mqtt.asyncapi.v1.Auth.method:type_name -> mqtt.asyncapi.v1.AuthMethod
	2,  // 6: mqtt.asyncapi.v1.Service.qos:type_name -> mqtt.asyncapi.v1.Qos
	3,  // 7: mqtt.asyncapi.v1.Operation.pattern:type_name -> mqtt.asyncapi.v1.Pattern
	2,  // 8: mqtt.asyncapi.v1.Operation.qos:type_name -> mqtt.asyncapi.v1.Qos
	4,  // 9: mqtt.asyncapi.v1.Operation.retain_handling:type_name -> mqtt.asyncapi.v1.RetainHandling
	12, // 10: mqtt.asyncapi.v1.document:extendee -> google.protobuf.FileOptions
	13, // 11: mqtt.asyncapi.v1.service:extendee -> google.protobuf.ServiceOptions
	14, // 12: mqtt.asyncapi.v1.operation:extendee -> google.protobuf.MethodOptions
	15, // 13: mqtt.asyncapi.v1.message:extendee -> google.protobuf.MessageOptions
	5,  // 14: mqtt.asyncapi.v1.document:type_name -> mqtt.asyncapi.v1.Document
	9,  // 15: mqtt.asyncapi.v1.service:type_name -> mqtt.asyncapi.v1.Service
	10, // 16: mqtt.asyncapi.v1.operation:type_name -> mqtt.asyncapi.v1.Operation
	11, // 17: mqtt.asyncapi.v1.message:type_name -> mqtt.asyncapi.v1.Message
	18, // [18:18] is the sub-list for method output_type
	18, // [18:18] is the sub-list for method input_type
	14, // [14:18] is the sub-list for extension type_name
	10, // [10:14] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_mqtt_asyncapi_v1_annotations_proto_init() }
func file_mqtt_asyncapi_v1_annotations_proto_init() {
	if File_mqtt_asyncapi_v1_annotations_proto != nil {
		return
	}
	file_mqtt_asyncapi_v1_annotations_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mqtt_asyncapi_v1_annotations_proto_rawDesc), len(file_mqtt_asyncapi_v1_annotations_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   7,
			NumExtensions: 4,
			NumServices:   0,
		},
		GoTypes:           file_mqtt_asyncapi_v1_annotations_proto_goTypes,
		DependencyIndexes: file_mqtt_asyncapi_v1_annotations_proto_depIdxs,
		EnumInfos:         file_mqtt_asyncapi_v1_annotations_proto_enumTypes,
		MessageInfos:      file_mqtt_asyncapi_v1_annotations_proto_msgTypes,
		ExtensionInfos:    file_mqtt_asyncapi_v1_annotations_proto_extTypes,
	}.Build()
	File_mqtt_asyncapi_v1_annotations_proto = out.File
	file_mqtt_asyncapi_v1_annotations_proto_goTypes = nil
	file_mqtt_asyncapi_v1_annotations_proto_depIdxs = nil
}
