// Package generator implements protoc-gen-temporal-asyncapi: it discovers the
// Temporal operations declared by (temporal.asyncapi.v1.*) annotations on
// services and rpcs, and renders them as AsyncAPI 3.0/3.1 documents.
package generator

import (
	"fmt"
	"strings"

	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/reflect/protodesc"
	"google.golang.org/protobuf/reflect/protoreflect"
	"google.golang.org/protobuf/reflect/protoregistry"
	"google.golang.org/protobuf/types/descriptorpb"
	"google.golang.org/protobuf/types/dynamicpb"
	"google.golang.org/protobuf/types/pluginpb"

	"github.com/AustinZhu/protoc-gen-temporal-asyncapi/internal/asyncapi"
)

// Run handles one CodeGeneratorRequest. Problems with the input (bad options,
// invalid annotations) are reported in the response's error field, which
// protoc and buf surface as a generation failure; no file is emitted then.
func Run(req *pluginpb.CodeGeneratorRequest, version string) *pluginpb.CodeGeneratorResponse {
	resp := &pluginpb.CodeGeneratorResponse{
		SupportedFeatures: proto.Uint64(uint64(pluginpb.CodeGeneratorResponse_FEATURE_PROTO3_OPTIONAL |
			pluginpb.CodeGeneratorResponse_FEATURE_SUPPORTS_EDITIONS)),
		MinimumEdition: proto.Int32(int32(descriptorpb.Edition_EDITION_PROTO2)),
		MaximumEdition: proto.Int32(int32(descriptorpb.Edition_EDITION_2024)),
	}
	files, err := Generate(req, version)
	if err != nil {
		resp.Error = proto.String(err.Error())
		return resp
	}
	resp.File = files
	return resp
}

// Generate renders one AsyncAPI document per file to generate that declares
// operations, named <file>.asyncapi.yaml next to the source path, or a single
// merged document with merge=true.
func Generate(req *pluginpb.CodeGeneratorRequest, version string) ([]*pluginpb.CodeGeneratorResponse_File, error) {
	params, err := ParseParams(req.GetParameter())
	if err != nil {
		return nil, err
	}
	registry, err := protodesc.NewFiles(&descriptorpb.FileDescriptorSet{File: req.GetProtoFile()})
	if err != nil {
		return nil, fmt.Errorf("reading descriptors: %w", err)
	}
	var files []protoreflect.FileDescriptor
	for _, name := range req.GetFileToGenerate() {
		fd, err := registry.FindFileByPath(name)
		if err != nil {
			return nil, fmt.Errorf("file to generate %s: %w", name, err)
		}
		files = append(files, fd)
	}
	// Discover across every file at once: Temporal names are global within a
	// namespace, so duplicates are errors even across separate documents.
	ops, err := Discover(files)
	if err != nil {
		return nil, err
	}

	groups := [][]protoreflect.FileDescriptor{files}
	if !params.Merge {
		groups = groups[:0]
		for _, f := range files {
			groups = append(groups, []protoreflect.FileDescriptor{f})
		}
	}

	var out []*pluginpb.CodeGeneratorResponse_File
	for _, group := range groups {
		groupOps := opsIn(ops, group)
		if len(groupOps) == 0 {
			continue // files that declare nothing produce no document
		}
		doc, err := document(params, registry, groupOps, group)
		if err != nil {
			return nil, err
		}
		name := params.MergeFileName + params.extension()
		header := fmt.Sprintf("# Code generated by protoc-gen-temporal-asyncapi %s. DO NOT EDIT.\n", version)
		if !params.Merge {
			name = strings.TrimSuffix(group[0].Path(), ".proto") + ".asyncapi" + params.extension()
			header += "# source: " + group[0].Path() + "\n"
		}
		var content []byte
		if params.Format == "json" {
			content, err = asyncapi.MarshalJSON(doc)
		} else {
			content, err = asyncapi.MarshalYAML(doc, header)
		}
		if err != nil {
			return nil, fmt.Errorf("%s: %w", name, err)
		}
		out = append(out, &pluginpb.CodeGeneratorResponse_File{Name: proto.String(name), Content: proto.String(string(content))})
	}
	return out, nil
}

func document(params Params, registry *protoregistry.Files, ops []*Operation, files []protoreflect.FileDescriptor) (*asyncapi.Document, error) {
	schemaOpts := SchemaOptions{UseProtoNames: !params.JSONNames}
	if params.Protovalidate {
		schemaOpts.Protovalidate = dynamicpb.NewTypes(registry)
	}
	conv := NewConverter(schemaOpts)

	pkg := ops[0].Package()
	cfg := Config{
		AsyncAPIVersion: params.AsyncAPIVersion,
		Title:           params.Title,
		Version:         params.Version,
		Description:     params.Description,
		ID:              params.ID,
		ServerURL:       params.ServerURL,
		Namespace:       params.Namespace,
		Perspective:     Perspective(params.Perspective),
	}
	if cfg.Title == "" {
		cfg.Title = pkg
	}
	if cfg.ID == "" {
		cfg.ID = "urn:temporal:" + pkg
	}
	if !params.TrimUnusedSchemas {
		cfg.Extra = declaredTypes(files)
	}
	return Build(ops, conv, cfg)
}

// opsIn returns the operations declared in files, in order.
func opsIn(ops []*Operation, files []protoreflect.FileDescriptor) []*Operation {
	in := map[string]bool{}
	for _, f := range files {
		in[f.Path()] = true
	}
	var out []*Operation
	for _, op := range ops {
		if in[op.Method.ParentFile().Path()] {
			out = append(out, op)
		}
	}
	return out
}

// declaredTypes lists every message and enum declared in files.
func declaredTypes(files []protoreflect.FileDescriptor) []protoreflect.Descriptor {
	var out []protoreflect.Descriptor
	var walk func(protoreflect.MessageDescriptors, protoreflect.EnumDescriptors)
	walk = func(msgs protoreflect.MessageDescriptors, enums protoreflect.EnumDescriptors) {
		for i := 0; i < enums.Len(); i++ {
			out = append(out, enums.Get(i))
		}
		for i := 0; i < msgs.Len(); i++ {
			md := msgs.Get(i)
			if md.IsMapEntry() {
				continue
			}
			out = append(out, md)
			walk(md.Messages(), md.Enums())
		}
	}
	for _, f := range files {
		walk(f.Messages(), f.Enums())
	}
	return out
}
